package com.xlerp.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bascontract", "id", Bascontract.class);
		arp.addMapping("bascontractitem", "id", Bascontractitem.class);
		arp.addMapping("basdepartment", "id", Basdepartment.class);
		arp.addMapping("basitem", "id", Basitem.class);
		arp.addMapping("basitemclass", "id", Basitemclass.class);
		arp.addMapping("basmaterial", "id", Basmaterial.class);
		arp.addMapping("basorg", "id", Basorg.class);
		arp.addMapping("basPurchaseOrder", "id", BasPurchaseOrder.class);
		arp.addMapping("hruser", "id", Hruser.class);
		arp.addMapping("sysmenu", "id", Sysmenu.class);
		arp.addMapping("systerm", "id", Systerm.class);
		arp.addMapping("sysuser", "id", Sysuser.class);
		arp.addMapping("sysusermenu", "id", Sysusermenu.class);
	}
}


