package com.xlerp.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bascontract", "id", Bascontract.class);
		arp.addMapping("bascontractitem", "id", Bascontractitem.class);
		arp.addMapping("basdepartment", "id", Basdepartment.class);
		arp.addMapping("basitem", "id", Basitem.class);
		arp.addMapping("basitemclass", "id", Basitemclass.class);
		arp.addMapping("basmaterial", "id", Basmaterial.class);
		arp.addMapping("basorg", "id", Basorg.class);
		arp.addMapping("basPurchaseOrder", "id", BasPurchaseOrder.class);
		arp.addMapping("bastuzhi", "id", Bastuzhi.class);
		arp.addMapping("bastuzhicailiao", "id", Bastuzhicailiao.class);
		arp.addMapping("cl_bgxjsbxj_fc", "id", ClBgxjsbxjFc.class);
		arp.addMapping("cl_bgxjsbxj_lc", "id", ClBgxjsbxjLc.class);
		arp.addMapping("cl_fzc_fc", "id", ClFzcFc.class);
		arp.addMapping("cl_fzc_lc", "id", ClFzcLc.class);
		arp.addMapping("cl_jgb_fc", "id", ClJgbFc.class);
		arp.addMapping("cl_jgb_lc", "id", ClJgbLc.class);
		arp.addMapping("cl_jxjj_gc", "id", ClJxjjGc.class);
		arp.addMapping("cl_jxjj_lbgx", "id", ClJxjjLbgx.class);
		arp.addMapping("cl_jxjj_lc", "id", ClJxjjLc.class);
		arp.addMapping("cl_jyh_fc", "id", ClJyhFc.class);
		arp.addMapping("cl_jyh_lc", "id", ClJyhLc.class);
		arp.addMapping("cl_ljjj_fc", "id", ClLjjjFc.class);
		arp.addMapping("cl_ljjj_gc", "id", ClLjjjGc.class);
		arp.addMapping("cl_nzxj_fc", "id", ClNzxjFc.class);
		arp.addMapping("cl_nzxj_gc", "id", ClNzxjGc.class);
		arp.addMapping("cl_nzxj_lbgx", "id", ClNzxjLbgx.class);
		arp.addMapping("cl_nzxj_lc", "id", ClNzxjLc.class);
		arp.addMapping("cl_xcxj_fc", "id", ClXcxjFc.class);
		arp.addMapping("cl_xcxj_lc", "id", ClXcxjLc.class);
		arp.addMapping("hruser", "id", Hruser.class);
		arp.addMapping("plbeiliaojihua", "id", Plbeiliaojihua.class);
		arp.addMapping("pldingdanitem", "id", Pldingdanitem.class);
		arp.addMapping("plentityid", "id", Plentityid.class);
		arp.addMapping("plgongdanitem", "id", Plgongdanitem.class);
		arp.addMapping("plinoutstore", "id", Plinoutstore.class);
		arp.addMapping("plshengchandingdan", "id", Plshengchandingdan.class);
		arp.addMapping("plshengchangongdan", "id", Plshengchangongdan.class);
		arp.addMapping("sysmenu", "id", Sysmenu.class);
		arp.addMapping("systerm", "id", Systerm.class);
		arp.addMapping("sysuser", "id", Sysuser.class);
		arp.addMapping("sysusermenu", "id", Sysusermenu.class);
	}
}


