package com.xlerp.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bascontract", "id", Bascontract.class);
		arp.addMapping("bascontractitem", "id", Bascontractitem.class);
		arp.addMapping("basdepartment", "id", Basdepartment.class);
		arp.addMapping("basitem", "id", Basitem.class);
		arp.addMapping("basitemclass", "id", Basitemclass.class);
		arp.addMapping("basmaterial", "id", Basmaterial.class);
		arp.addMapping("basno", "id", Basno.class);
		arp.addMapping("basorg", "id", Basorg.class);
		arp.addMapping("basPurchaseOrder", "id", BasPurchaseOrder.class);
		arp.addMapping("bastuzhi", "id", Bastuzhi.class);
		arp.addMapping("bastuzhicailiao", "id", Bastuzhicailiao.class);
		arp.addMapping("cl_gb", "id", ClGb.class);
		arp.addMapping("cl_ld", "id", ClLd.class);
		arp.addMapping("cl_production_data", "id", ClProductionData.class);
		arp.addMapping("cl_wfg", "id", ClWfg.class);
		arp.addMapping("cl_xj", "id", ClXj.class);
		arp.addMapping("cl_yg", "id", ClYg.class);
		arp.addMapping("hruser", "id", Hruser.class);
		arp.addMapping("pl_mat_inout_doc", "id", PlMatInoutDoc.class);
		arp.addMapping("pl_mat_inout_item", "id", PlMatInoutItem.class);
		arp.addMapping("pl_production_order", "id", PlProductionOrder.class);
		arp.addMapping("pl_report_work_order", "id", PlReportWorkOrder.class);
		arp.addMapping("pl_schedule_plan", "id", PlSchedulePlan.class);
		arp.addMapping("pl_work_order", "id", PlWorkOrder.class);
		arp.addMapping("plbeiliaojihua", "id", Plbeiliaojihua.class);
		arp.addMapping("plchuchangchoujian", "id", Plchuchangchoujian.class);
		arp.addMapping("plchuchangshiyanshuju", "id", Plchuchangshiyanshuju.class);
		arp.addMapping("plentityid", "id", Plentityid.class);
		arp.addMapping("sysmenu", "id", Sysmenu.class);
		arp.addMapping("systerm", "id", Systerm.class);
		arp.addMapping("sysuser", "id", Sysuser.class);
		arp.addMapping("sysusermenu", "id", Sysusermenu.class);
	}
}


