package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasContractMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasContractMaterial extends BaseBasContractMaterial<BasContractMaterial> {
	
}

