package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBascontractitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bascontractitem extends BaseBascontractitem<Bascontractitem> {
	
}

