package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasdepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basdepartment extends BaseBasdepartment<Basdepartment> {
	
}

