package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasItemRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasItemRelation extends BaseBasItemRelation<BasItemRelation> {
	
}

