package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasItemClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasItemClass extends BaseBasItemClass<BasItemClass> {
	
}

