package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasitemclass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basitemclass extends BaseBasitemclass<Basitemclass> {
	
}

