package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasmaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Basmaterial extends BaseBasmaterial<Basmaterial> {
	
}

