package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasPurchaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasPurchaseOrder extends BaseBasPurchaseOrder<BasPurchaseOrder> {
	
}

