package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBasProcessRoute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasProcessRoute extends BaseBasProcessRoute<BasProcessRoute> {
	
}

