package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBastuzhi;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bastuzhi extends BaseBastuzhi<Bastuzhi> {
	
}

