package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseBastuzhicailiao;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Bastuzhicailiao extends BaseBastuzhicailiao<Bastuzhicailiao> {
	
}

