package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClBgxjsbxjFc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClBgxjsbxjFc extends BaseClBgxjsbxjFc<ClBgxjsbxjFc> {
	
}

