package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClJxjjLc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClJxjjLc extends BaseClJxjjLc<ClJxjjLc> {
	
}

