package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClJxjjLbgx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClJxjjLbgx extends BaseClJxjjLbgx<ClJxjjLbgx> {
	
}

