package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClJxjjGc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClJxjjGc extends BaseClJxjjGc<ClJxjjGc> {
	
}

