package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClLjjjGc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClLjjjGc extends BaseClLjjjGc<ClLjjjGc> {
	
}

