package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClLjjjFc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClLjjjFc extends BaseClLjjjFc<ClLjjjFc> {
	
}

