package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClNzxjLbgx;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClNzxjLbgx extends BaseClNzxjLbgx<ClNzxjLbgx> {
	
}

