package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClNzxjLc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClNzxjLc extends BaseClNzxjLc<ClNzxjLc> {
	
}

