package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClNzxjFc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClNzxjFc extends BaseClNzxjFc<ClNzxjFc> {
	
}

