package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClNzxjGc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClNzxjGc extends BaseClNzxjGc<ClNzxjGc> {
	
}

