package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClProductionData;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClProductionData extends BaseClProductionData<ClProductionData> {
	
}

