package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClXcxjLc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClXcxjLc extends BaseClXcxjLc<ClXcxjLc> {
	
}

