package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseClXcxjFc;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClXcxjFc extends BaseClXcxjFc<ClXcxjFc> {
	
}

