package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlbaogongdan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plbaogongdan extends BasePlbaogongdan<Plbaogongdan> {
	
}

