package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlbeiliaojihua;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plbeiliaojihua extends BasePlbeiliaojihua<Plbeiliaojihua> {
	
}

