package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlchuchangchoujian;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plchuchangchoujian extends BasePlchuchangchoujian<Plchuchangchoujian> {
	
}

