package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlchuchangshiyanshuju;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plchuchangshiyanshuju extends BasePlchuchangshiyanshuju<Plchuchangshiyanshuju> {
	
}

