package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePldingdanitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pldingdanitem extends BasePldingdanitem<Pldingdanitem> {
	
}

