package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlentityid;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plentityid extends BasePlentityid<Plentityid> {
	
}

