package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlFinishInoutList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlFinishInoutList extends BasePlFinishInoutList<PlFinishInoutList> {
	
}

