package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlgongdanitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plgongdanitem extends BasePlgongdanitem<Plgongdanitem> {
	
}

