package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlInspResult;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlInspResult extends BasePlInspResult<PlInspResult> {
	
}

