package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlInspStdItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlInspStdItem extends BasePlInspStdItem<PlInspStdItem> {
	
}

