package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlinoutstore;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plinoutstore extends BasePlinoutstore<Plinoutstore> {
	
}

