package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlInspItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlInspItem extends BasePlInspItem<PlInspItem> {
	
}

