package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlInspOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlInspOrder extends BasePlInspOrder<PlInspOrder> {
	
}

