package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlInspStd;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlInspStd extends BasePlInspStd<PlInspStd> {
	
}

