package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlMaterialRequestAllocation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlMaterialRequestAllocation extends BasePlMaterialRequestAllocation<PlMaterialRequestAllocation> {
	
}

