package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlMaterialRequestDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlMaterialRequestDetail extends BasePlMaterialRequestDetail<PlMaterialRequestDetail> {
	
}

