package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlMatInoutList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlMatInoutList extends BasePlMatInoutList<PlMatInoutList> {
	
}

