package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlMatInoutItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlMatInoutItem extends BasePlMatInoutItem<PlMatInoutItem> {
	
}

