package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlMaterialRequestMain;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlMaterialRequestMain extends BasePlMaterialRequestMain<PlMaterialRequestMain> {
	
}

