package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlProductionOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlProductionOrder extends BasePlProductionOrder<PlProductionOrder> {
	
}

