package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlPurchaseOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlPurchaseOrder extends BasePlPurchaseOrder<PlPurchaseOrder> {
	
}

