package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlReporderMaterial;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlReporderMaterial extends BasePlReporderMaterial<PlReporderMaterial> {
	
}

