package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlReportWorkOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlReportWorkOrder extends BasePlReportWorkOrder<PlReportWorkOrder> {
	
}

