package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlSchedulePlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlSchedulePlan extends BasePlSchedulePlan<PlSchedulePlan> {
	
}

