package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlshengchandingdan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plshengchandingdan extends BasePlshengchandingdan<Plshengchandingdan> {
	
}

