package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlshengchangongdan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Plshengchangongdan extends BasePlshengchangongdan<Plshengchangongdan> {
	
}

