package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlSupplyOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlSupplyOrder extends BasePlSupplyOrder<PlSupplyOrder> {
	
}

