package com.xlerp.common.model;

import com.xlerp.common.model.base.BasePlWorkOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PlWorkOrder extends BasePlWorkOrder<PlWorkOrder> {
	
}

