package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseSysusermenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sysusermenu extends BaseSysusermenu<Sysusermenu> {
	
}

