package com.xlerp.common.model;

import com.xlerp.common.model.base.BaseSysUploadLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysUploadLog extends BaseSysUploadLog<SysUploadLog> {
	
}

