package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlProductionOrder<M extends BasePlProductionOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 订单类型
	 */
	public void setIpoType(java.lang.Integer ipoType) {
		set("ipoType", ipoType);
	}
	
	/**
	 * 订单类型
	 */
	public java.lang.Integer getIpoType() {
		return getInt("ipoType");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 生产订单号
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 生产订单号
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 品类编码
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 排产计划编码
	 */
	public void setScheduleCode(java.lang.String scheduleCode) {
		set("scheduleCode", scheduleCode);
	}
	
	/**
	 * 排产计划编码
	 */
	public java.lang.String getScheduleCode() {
		return getStr("scheduleCode");
	}
	
	/**
	 * 采购订单行项目ID（供货单行项目ID）或销售订单号
	 */
	public void setPoItemId(java.lang.Long poItemId) {
		set("poItemId", poItemId);
	}
	
	/**
	 * 采购订单行项目ID（供货单行项目ID）或销售订单号
	 */
	public java.lang.Long getPoItemId() {
		return getLong("poItemId");
	}
	
	/**
	 * 数据关联类型
	 */
	public void setDataType(java.lang.Integer dataType) {
		set("dataType", dataType);
	}
	
	/**
	 * 数据关联类型
	 */
	public java.lang.Integer getDataType() {
		return getInt("dataType");
	}
	
	/**
	 * 销售订单行项目号
	 */
	public void setSoItemNo(java.lang.Long soItemNo) {
		set("soItemNo", soItemNo);
	}
	
	/**
	 * 销售订单行项目号
	 */
	public java.lang.Long getSoItemNo() {
		return getLong("soItemNo");
	}
	
	/**
	 * 厂家物料编码
	 */
	public void setMaterialsCode(java.lang.String materialsCode) {
		set("materialsCode", materialsCode);
	}
	
	/**
	 * 厂家物料编码
	 */
	public java.lang.String getMaterialsCode() {
		return getStr("materialsCode");
	}
	
	/**
	 * 厂家物料名称
	 */
	public void setMaterialsName(java.lang.String materialsName) {
		set("materialsName", materialsName);
	}
	
	/**
	 * 厂家物料名称
	 */
	public java.lang.String getMaterialsName() {
		return getStr("materialsName");
	}
	
	/**
	 * 厂家物资单位
	 */
	public void setMaterialsUnit(java.lang.String materialsUnit) {
		set("materialsUnit", materialsUnit);
	}
	
	/**
	 * 厂家物资单位
	 */
	public java.lang.String getMaterialsUnit() {
		return getStr("materialsUnit");
	}
	
	/**
	 * 厂家物料描述
	 */
	public void setMaterialsDesc(java.lang.String materialsDesc) {
		set("materialsDesc", materialsDesc);
	}
	
	/**
	 * 厂家物料描述
	 */
	public java.lang.String getMaterialsDesc() {
		return getStr("materialsDesc");
	}
	
	/**
	 * 生产数量
	 */
	public void setAmount(java.math.BigDecimal amount) {
		set("amount", amount);
	}
	
	/**
	 * 生产数量
	 */
	public java.math.BigDecimal getAmount() {
		return get("amount");
	}
	
	/**
	 * 计量单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 计量单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 物资ID分组
	 */
	public void setProductIdGrpNo(java.lang.String productIdGrpNo) {
		set("productIdGrpNo", productIdGrpNo);
	}
	
	/**
	 * 物资ID分组
	 */
	public java.lang.String getProductIdGrpNo() {
		return getStr("productIdGrpNo");
	}
	
	/**
	 * 物资ID类型
	 */
	public void setProductIdType(java.lang.String productIdType) {
		set("productIdType", productIdType);
	}
	
	/**
	 * 物资ID类型
	 */
	public java.lang.String getProductIdType() {
		return getStr("productIdType");
	}
	
	/**
	 * 产品型号
	 */
	public void setProductModel(java.lang.String productModel) {
		set("productModel", productModel);
	}
	
	/**
	 * 产品型号
	 */
	public java.lang.String getProductModel() {
		return getStr("productModel");
	}
	
	/**
	 * 计划开始日期
	 */
	public void setPlanStartDate(java.util.Date planStartDate) {
		set("planStartDate", planStartDate);
	}
	
	/**
	 * 计划开始日期
	 */
	public java.util.Date getPlanStartDate() {
		return getDate("planStartDate");
	}
	
	/**
	 * 计划完成日期
	 */
	public void setPlanFinishDate(java.util.Date planFinishDate) {
		set("planFinishDate", planFinishDate);
	}
	
	/**
	 * 计划完成日期
	 */
	public java.util.Date getPlanFinishDate() {
		return getDate("planFinishDate");
	}
	
	/**
	 * 实际开始日期
	 */
	public void setActualStartDate(java.util.Date actualStartDate) {
		set("actualStartDate", actualStartDate);
	}
	
	/**
	 * 实际开始日期
	 */
	public java.util.Date getActualStartDate() {
		return getDate("actualStartDate");
	}
	
	/**
	 * 实际完成日期
	 */
	public void setActualFinishDate(java.util.Date actualFinishDate) {
		set("actualFinishDate", actualFinishDate);
	}
	
	/**
	 * 实际完成日期
	 */
	public java.util.Date getActualFinishDate() {
		return getDate("actualFinishDate");
	}
	
	/**
	 * 生产工厂名称
	 */
	public void setPlantName(java.lang.String plantName) {
		set("plantName", plantName);
	}
	
	/**
	 * 生产工厂名称
	 */
	public java.lang.String getPlantName() {
		return getStr("plantName");
	}
	
	/**
	 * 生产车间名称
	 */
	public void setWorkshopName(java.lang.String workshopName) {
		set("workshopName", workshopName);
	}
	
	/**
	 * 生产车间名称
	 */
	public java.lang.String getWorkshopName() {
		return getStr("workshopName");
	}
	
	/**
	 * 生产订单状态
	 */
	public void setIpoStatus(java.lang.Integer ipoStatus) {
		set("ipoStatus", ipoStatus);
	}
	
	/**
	 * 生产订单状态
	 */
	public java.lang.Integer getIpoStatus() {
		return getInt("ipoStatus");
	}
	
	/**
	 * 生产中心
	 */
	public void setCenter(java.lang.String center) {
		set("center", center);
	}
	
	/**
	 * 生产中心
	 */
	public java.lang.String getCenter() {
		return getStr("center");
	}
	
	/**
	 * 数据来源
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 数据拥有方
	 */
	public void setOwnerId(java.lang.String ownerId) {
		set("ownerId", ownerId);
	}
	
	/**
	 * 数据拥有方
	 */
	public java.lang.String getOwnerId() {
		return getStr("ownerId");
	}
	
	/**
	 * 数据可见方
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 数据可见方
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}
	
	/**
	 * 记录创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("createdTime", createdTime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("createdTime");
	}
	
	/**
	 * 记录更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updatedTime", updatedTime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updatedTime");
	}
	
	/**
	 * 10为录入，20为确认
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 10为录入，20为确认
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
}

