package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasitem<M extends BaseBasitem<M>> extends Model<M> implements IBean {

	/**
	 * 唯一标识ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 唯一标识ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 物料编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 物料编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 物料名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 物料名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 计量单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 计量单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 规格型号
	 */
	public void setSpec(java.lang.String spec) {
		set("spec", spec);
	}
	
	/**
	 * 规格型号
	 */
	public java.lang.String getSpec() {
		return getStr("spec");
	}
	
	/**
	 * 物料描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	/**
	 * 物料描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 颜色
	 */
	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	/**
	 * 颜色
	 */
	public java.lang.String getColor() {
		return getStr("color");
	}
	
	/**
	 * 备注信息
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 标志位
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志位
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 物料类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 物料类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 重量
	 */
	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}
	
	/**
	 * 保管规则(XML格式)
	 */
	public void setKeeperRule(java.lang.String keeperRule) {
		set("keeper_rule", keeperRule);
	}
	
	/**
	 * 保管规则(XML格式)
	 */
	public java.lang.String getKeeperRule() {
		return getStr("keeper_rule");
	}
	
	/**
	 * 计划价格
	 */
	public void setPlannedPrice(java.math.BigDecimal plannedPrice) {
		set("planned_price", plannedPrice);
	}
	
	/**
	 * 计划价格
	 */
	public java.math.BigDecimal getPlannedPrice() {
		return get("planned_price");
	}
	
	/**
	 * 平均价格
	 */
	public void setAvgPrice(java.math.BigDecimal avgPrice) {
		set("avg_price", avgPrice);
	}
	
	/**
	 * 平均价格
	 */
	public java.math.BigDecimal getAvgPrice() {
		return get("avg_price");
	}
	
	/**
	 * 存放位置
	 */
	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	/**
	 * 存放位置
	 */
	public java.lang.String getLocation() {
		return getStr("location");
	}
	
	/**
	 * 技术备注
	 */
	public void setTechMemo(java.lang.String techMemo) {
		set("tech_memo", techMemo);
	}
	
	/**
	 * 技术备注
	 */
	public java.lang.String getTechMemo() {
		return getStr("tech_memo");
	}
	
	/**
	 * 状态(0-正常,1-停用等)
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态(0-正常,1-停用等)
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 所属分类
	 */
	public void setInclass(java.lang.String inclass) {
		set("inclass", inclass);
	}
	
	/**
	 * 所属分类
	 */
	public java.lang.String getInclass() {
		return getStr("inclass");
	}
	
	/**
	 * 是否删除(0-未删除,1-已删除)
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 是否删除(0-未删除,1-已删除)
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
}

