package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBastuzhicailiao<M extends BaseBastuzhicailiao<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 关联的bastuzhi表，图纸id
	 */
	public void setTuzhiid(java.lang.Integer tuzhiid) {
		set("tuzhiid", tuzhiid);
	}
	
	/**
	 * 关联的bastuzhi表，图纸id
	 */
	public java.lang.Integer getTuzhiid() {
		return getInt("tuzhiid");
	}
	
	/**
	 * 关联的basitem表里的id字段
	 */
	public void setBasitemid(java.lang.Integer basitemid) {
		set("basitemid", basitemid);
	}
	
	/**
	 * 关联的basitem表里的id字段
	 */
	public java.lang.Integer getBasitemid() {
		return getInt("basitemid");
	}
	
	/**
	 * 所需材料的数量
	 */
	public void setShuliang(java.lang.String shuliang) {
		set("shuliang", shuliang);
	}
	
	/**
	 * 所需材料的数量
	 */
	public java.lang.String getShuliang() {
		return getStr("shuliang");
	}
	
	/**
	 * 预留字段
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 预留字段
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 预留字段
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 数据写入时间
	 */
	public void setWritetime(java.lang.String writetime) {
		set("writetime", writetime);
	}
	
	/**
	 * 数据写入时间
	 */
	public java.lang.String getWritetime() {
		return getStr("writetime");
	}
	
	/**
	 * 数据写入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 数据写入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
}

