package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasitemclass<M extends BaseBasitemclass<M>> extends Model<M> implements IBean {

	/**
	 * 分类ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 分类ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 分类编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 分类编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 是否删除(0-未删除,1-已删除)
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 是否删除(0-未删除,1-已删除)
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 分类名称
	 */
	public void setItemclassname(java.lang.String itemclassname) {
		set("itemclassname", itemclassname);
	}
	
	/**
	 * 分类名称
	 */
	public java.lang.String getItemclassname() {
		return getStr("itemclassname");
	}
	
	/**
	 * 分类类型
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 分类类型
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 标志位
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志位
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 备注信息
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注信息
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
}

