package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysterm<M extends BaseSysterm<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 期间
	 */
	public void setTerm(java.lang.String term) {
		set("term", term);
	}
	
	/**
	 * 期间
	 */
	public java.lang.String getTerm() {
		return getStr("term");
	}
	
	/**
	 * 是否是当前期间(0否1是2是上一期间3是下一个期间)
	 */
	public void setIscurrent(java.lang.Integer iscurrent) {
		set("iscurrent", iscurrent);
	}
	
	/**
	 * 是否是当前期间(0否1是2是上一期间3是下一个期间)
	 */
	public java.lang.Integer getIscurrent() {
		return getInt("iscurrent");
	}
	
	/**
	 * 开始时间期间
	 */
	public void setBegindate(java.util.Date begindate) {
		set("begindate", begindate);
	}
	
	/**
	 * 开始时间期间
	 */
	public java.util.Date getBegindate() {
		return getDate("begindate");
	}
	
	/**
	 * 期间结束时间
	 */
	public void setEnddate(java.util.Date enddate) {
		set("enddate", enddate);
	}
	
	/**
	 * 期间结束时间
	 */
	public java.util.Date getEnddate() {
		return getDate("enddate");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
}

