package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlInspStd<M extends BasePlInspStd<M>> extends Model<M> implements IBean {

	/**
	 * 主键，系统自动生成
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键，系统自动生成
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 标准编号，如 GB/T 228-2022，唯一
	 */
	public void setStandardNo(java.lang.String standardNo) {
		set("standardNo", standardNo);
	}
	
	/**
	 * 标准编号，如 GB/T 228-2022，唯一
	 */
	public java.lang.String getStandardNo() {
		return getStr("standardNo");
	}
	
	/**
	 * 用于材料名称，如 铝管/铝板
	 */
	public void setMaterials(java.lang.String materials) {
		set("materials", materials);
	}
	
	/**
	 * 用于材料名称，如 铝管/铝板
	 */
	public java.lang.String getMaterials() {
		return getStr("materials");
	}
	
	/**
	 * 材料牌号，如 Q235B、304（可选，多个用逗号分隔）
	 */
	public void setMatNo(java.lang.String matNo) {
		set("matNo", matNo);
	}
	
	/**
	 * 材料牌号，如 Q235B、304（可选，多个用逗号分隔）
	 */
	public java.lang.String getMatNo() {
		return getStr("matNo");
	}
	
	/**
	 * 标准备注，如适用范围、修订说明
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 标准备注，如适用范围、修订说明
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 业务标记位（预留）
	 */
	public void setFlag(java.lang.Short flag) {
		set("flag", flag);
	}
	
	/**
	 * 业务标记位（预留）
	 */
	public java.lang.Short getFlag() {
		return getShort("flag");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
}

