package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClCt<M extends BaseClCt<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 孔实际测量值
	 */
	public void setKong1(java.math.BigDecimal kong1) {
		set("kong1", kong1);
	}
	
	/**
	 * 孔实际测量值
	 */
	public java.math.BigDecimal getKong1() {
		return get("kong1");
	}
	
	/**
	 * 总长实际测量值
	 */
	public void setZongChang1(java.math.BigDecimal zongChang1) {
		set("zongChang1", zongChang1);
	}
	
	/**
	 * 总长实际测量值
	 */
	public java.math.BigDecimal getZongChang1() {
		return get("zongChang1");
	}
	
	/**
	 * 宽实际测量值
	 */
	public void setKuan1(java.math.BigDecimal kuan1) {
		set("kuan1", kuan1);
	}
	
	/**
	 * 宽实际测量值
	 */
	public java.math.BigDecimal getKuan1() {
		return get("kuan1");
	}
	
	/**
	 * 头宽实际测量值
	 */
	public void setTouKuan1(java.math.BigDecimal touKuan1) {
		set("touKuan1", touKuan1);
	}
	
	/**
	 * 头宽实际测量值
	 */
	public java.math.BigDecimal getTouKuan1() {
		return get("touKuan1");
	}
	
	/**
	 * 孔标准尺寸
	 */
	public void setKongRequired(java.math.BigDecimal kongRequired) {
		set("kongRequired", kongRequired);
	}
	
	/**
	 * 孔标准尺寸
	 */
	public java.math.BigDecimal getKongRequired() {
		return get("kongRequired");
	}
	
	/**
	 * 总长标准尺寸
	 */
	public void setZongChangRequired(java.math.BigDecimal zongChangRequired) {
		set("zongChangRequired", zongChangRequired);
	}
	
	/**
	 * 总长标准尺寸
	 */
	public java.math.BigDecimal getZongChangRequired() {
		return get("zongChangRequired");
	}
	
	/**
	 * 宽标准尺寸
	 */
	public void setKuanRequired(java.math.BigDecimal kuanRequired) {
		set("kuanRequired", kuanRequired);
	}
	
	/**
	 * 宽标准尺寸
	 */
	public java.math.BigDecimal getKuanRequired() {
		return get("kuanRequired");
	}
	
	/**
	 * 头宽标准尺寸
	 */
	public void setTouKuanRequired(java.math.BigDecimal touKuanRequired) {
		set("touKuanRequired", touKuanRequired);
	}
	
	/**
	 * 头宽标准尺寸
	 */
	public java.math.BigDecimal getTouKuanRequired() {
		return get("touKuanRequired");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeaveFactoryDate(java.util.Date leaveFactoryDate) {
		set("leaveFactoryDate", leaveFactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeaveFactoryDate() {
		return getDate("leaveFactoryDate");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录人，20检验单确认，待审核，30请检单验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录人，20检验单确认，待审核，30请检单验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 重量实测值
	 */
	public void setZhongLiang1(java.math.BigDecimal zhongLiang1) {
		set("zhongLiang1", zhongLiang1);
	}
	
	/**
	 * 重量实测值
	 */
	public java.math.BigDecimal getZhongLiang1() {
		return get("zhongLiang1");
	}
	
	/**
	 * 重量标准值
	 */
	public void setZhongLiangRequired(java.math.BigDecimal zhongLiangRequired) {
		set("zhongLiangRequired", zhongLiangRequired);
	}
	
	/**
	 * 重量标准值
	 */
	public java.math.BigDecimal getZhongLiangRequired() {
		return get("zhongLiangRequired");
	}
	
	/**
	 * 规格
	 */
	public void setGuiGe(java.lang.String guiGe) {
		set("guiGe", guiGe);
	}
	
	/**
	 * 规格
	 */
	public java.lang.String getGuiGe() {
		return getStr("guiGe");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.math.BigDecimal storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.math.BigDecimal getStorageTime() {
		return get("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setComplnspQty(java.math.BigDecimal complnspQty) {
		set("complnspQty", complnspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getComplnspQty() {
		return get("complnspQty");
	}
	
	/**
	 * 尺寸检验抽检数量，默认为五件
	 */
	public void setMechinspQty(java.math.BigDecimal mechinspQty) {
		set("mechinspQty", mechinspQty);
	}
	
	/**
	 * 尺寸检验抽检数量，默认为五件
	 */
	public java.math.BigDecimal getMechinspQty() {
		return get("mechinspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 化学成分-C
	 */
	public void setChemC(java.math.BigDecimal chemC) {
		set("chemC", chemC);
	}
	
	/**
	 * 化学成分-C
	 */
	public java.math.BigDecimal getChemC() {
		return get("chemC");
	}
	
	/**
	 * 化学成分-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分-P
	 */
	public void setChemP(java.math.BigDecimal chemP) {
		set("chemP", chemP);
	}
	
	/**
	 * 化学成分-P
	 */
	public java.math.BigDecimal getChemP() {
		return get("chemP");
	}
	
	/**
	 * 化学成分-S
	 */
	public void setChemS(java.math.BigDecimal chemS) {
		set("chemS", chemS);
	}
	
	/**
	 * 化学成分-S
	 */
	public java.math.BigDecimal getChemS() {
		return get("chemS");
	}
	
	/**
	 * 抗拉强度
	 */
	public void setTensileStrength(java.math.BigDecimal tensileStrength) {
		set("tensileStrength", tensileStrength);
	}
	
	/**
	 * 抗拉强度
	 */
	public java.math.BigDecimal getTensileStrength() {
		return get("tensileStrength");
	}
	
	/**
	 * 延伸率
	 */
	public void setElongation(java.math.BigDecimal elongation) {
		set("elongation", elongation);
	}
	
	/**
	 * 延伸率
	 */
	public java.math.BigDecimal getElongation() {
		return get("elongation");
	}
	
	/**
	 * 屈服强度
	 */
	public void setYieldStrength(java.math.BigDecimal yieldStrength) {
		set("yieldStrength", yieldStrength);
	}
	
	/**
	 * 屈服强度
	 */
	public java.math.BigDecimal getYieldStrength() {
		return get("yieldStrength");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号，录入请检单用
	 */
	public void setBasNo(java.lang.String basNo) {
		set("basNo", basNo);
	}
	
	/**
	 * 单据号，录入请检单用
	 */
	public java.lang.String getBasNo() {
		return getStr("basNo");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 总抽检数量
	 */
	public void setSampleQuantity(java.math.BigDecimal sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 总抽检数量
	 */
	public java.math.BigDecimal getSampleQuantity() {
		return get("sampleQuantity");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸是否合格
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸是否合格
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 孔判断结果
	 */
	public void setKongJudgmentResult(java.lang.String kongJudgmentResult) {
		set("kongJudgmentResult", kongJudgmentResult);
	}
	
	/**
	 * 孔判断结果
	 */
	public java.lang.String getKongJudgmentResult() {
		return getStr("kongJudgmentResult");
	}
	
	/**
	 * 外形判断结果
	 */
	public void setAppearanceJudgmentResult(java.lang.String appearanceJudgmentResult) {
		set("appearanceJudgmentResult", appearanceJudgmentResult);
	}
	
	/**
	 * 外形判断结果
	 */
	public java.lang.String getAppearanceJudgmentResult() {
		return getStr("appearanceJudgmentResult");
	}
	
	/**
	 * 机械性能判断结果
	 */
	public void setMachineryJudgmentResult(java.lang.String machineryJudgmentResult) {
		set("machineryJudgmentResult", machineryJudgmentResult);
	}
	
	/**
	 * 机械性能判断结果
	 */
	public java.lang.String getMachineryJudgmentResult() {
		return getStr("machineryJudgmentResult");
	}
	
	/**
	 * 外形
	 */
	public void setAppearance(java.lang.String appearance) {
		set("appearance", appearance);
	}
	
	/**
	 * 外形
	 */
	public java.lang.String getAppearance() {
		return getStr("appearance");
	}
	
	/**
	 * 孔实际测量值
	 */
	public void setKong2(java.math.BigDecimal kong2) {
		set("kong2", kong2);
	}
	
	/**
	 * 孔实际测量值
	 */
	public java.math.BigDecimal getKong2() {
		return get("kong2");
	}
	
	/**
	 * 孔实际测量值
	 */
	public void setKong3(java.math.BigDecimal kong3) {
		set("kong3", kong3);
	}
	
	/**
	 * 孔实际测量值
	 */
	public java.math.BigDecimal getKong3() {
		return get("kong3");
	}
	
	/**
	 * 孔实际测量值
	 */
	public void setKong4(java.math.BigDecimal kong4) {
		set("kong4", kong4);
	}
	
	/**
	 * 孔实际测量值
	 */
	public java.math.BigDecimal getKong4() {
		return get("kong4");
	}
	
	/**
	 * 孔实际测量值
	 */
	public void setKong5(java.math.BigDecimal kong5) {
		set("kong5", kong5);
	}
	
	/**
	 * 孔实际测量值
	 */
	public java.math.BigDecimal getKong5() {
		return get("kong5");
	}
	
	/**
	 * 总长实际测量值
	 */
	public void setZongChang2(java.math.BigDecimal zongChang2) {
		set("zongChang2", zongChang2);
	}
	
	/**
	 * 总长实际测量值
	 */
	public java.math.BigDecimal getZongChang2() {
		return get("zongChang2");
	}
	
	/**
	 * 总长实际测量值
	 */
	public void setZongChang3(java.math.BigDecimal zongChang3) {
		set("zongChang3", zongChang3);
	}
	
	/**
	 * 总长实际测量值
	 */
	public java.math.BigDecimal getZongChang3() {
		return get("zongChang3");
	}
	
	/**
	 * 总长实际测量值
	 */
	public void setZongChang4(java.math.BigDecimal zongChang4) {
		set("zongChang4", zongChang4);
	}
	
	/**
	 * 总长实际测量值
	 */
	public java.math.BigDecimal getZongChang4() {
		return get("zongChang4");
	}
	
	/**
	 * 总长实际测量值
	 */
	public void setZongChang5(java.math.BigDecimal zongChang5) {
		set("zongChang5", zongChang5);
	}
	
	/**
	 * 总长实际测量值
	 */
	public java.math.BigDecimal getZongChang5() {
		return get("zongChang5");
	}
	
	/**
	 * 宽实际测量值
	 */
	public void setKuan2(java.math.BigDecimal kuan2) {
		set("kuan2", kuan2);
	}
	
	/**
	 * 宽实际测量值
	 */
	public java.math.BigDecimal getKuan2() {
		return get("kuan2");
	}
	
	/**
	 * 宽实际测量值
	 */
	public void setKuan3(java.math.BigDecimal kuan3) {
		set("kuan3", kuan3);
	}
	
	/**
	 * 宽实际测量值
	 */
	public java.math.BigDecimal getKuan3() {
		return get("kuan3");
	}
	
	/**
	 * 宽实际测量值
	 */
	public void setKuan4(java.math.BigDecimal kuan4) {
		set("kuan4", kuan4);
	}
	
	/**
	 * 宽实际测量值
	 */
	public java.math.BigDecimal getKuan4() {
		return get("kuan4");
	}
	
	/**
	 * 宽实际测量值
	 */
	public void setKuan5(java.math.BigDecimal kuan5) {
		set("kuan5", kuan5);
	}
	
	/**
	 * 宽实际测量值
	 */
	public java.math.BigDecimal getKuan5() {
		return get("kuan5");
	}
	
	/**
	 * 头宽实际测量值
	 */
	public void setTouKuan2(java.math.BigDecimal touKuan2) {
		set("touKuan2", touKuan2);
	}
	
	/**
	 * 头宽实际测量值
	 */
	public java.math.BigDecimal getTouKuan2() {
		return get("touKuan2");
	}
	
	/**
	 * 头宽实际测量值
	 */
	public void setTouKuan3(java.math.BigDecimal touKuan3) {
		set("touKuan3", touKuan3);
	}
	
	/**
	 * 头宽实际测量值
	 */
	public java.math.BigDecimal getTouKuan3() {
		return get("touKuan3");
	}
	
	/**
	 * 头宽实际测量值
	 */
	public void setTouKuan4(java.math.BigDecimal touKuan4) {
		set("touKuan4", touKuan4);
	}
	
	/**
	 * 头宽实际测量值
	 */
	public java.math.BigDecimal getTouKuan4() {
		return get("touKuan4");
	}
	
	/**
	 * 头宽实际测量值
	 */
	public void setTouKuan5(java.math.BigDecimal touKuan5) {
		set("touKuan5", touKuan5);
	}
	
	/**
	 * 头宽实际测量值
	 */
	public java.math.BigDecimal getTouKuan5() {
		return get("touKuan5");
	}
	
	/**
	 * 重量实际测量值
	 */
	public void setZhongLiang2(java.math.BigDecimal zhongLiang2) {
		set("zhongLiang2", zhongLiang2);
	}
	
	/**
	 * 重量实际测量值
	 */
	public java.math.BigDecimal getZhongLiang2() {
		return get("zhongLiang2");
	}
	
	/**
	 * 重量实际测量值
	 */
	public void setZhongLiang3(java.math.BigDecimal zhongLiang3) {
		set("zhongLiang3", zhongLiang3);
	}
	
	/**
	 * 重量实际测量值
	 */
	public java.math.BigDecimal getZhongLiang3() {
		return get("zhongLiang3");
	}
	
	/**
	 * 重量实际测量值
	 */
	public void setZhongLiang4(java.math.BigDecimal zhongLiang4) {
		set("zhongLiang4", zhongLiang4);
	}
	
	/**
	 * 重量实际测量值
	 */
	public java.math.BigDecimal getZhongLiang4() {
		return get("zhongLiang4");
	}
	
	/**
	 * 重量实际测量值
	 */
	public void setZhongLiang5(java.math.BigDecimal zhongLiang5) {
		set("zhongLiang5", zhongLiang5);
	}
	
	/**
	 * 重量实际测量值
	 */
	public java.math.BigDecimal getZhongLiang5() {
		return get("zhongLiang5");
	}
	
	/**
	 * 重量实测值平均数
	 */
	public void setZhongLiangAverage(java.math.BigDecimal zhongLiangAverage) {
		set("zhongLiangAverage", zhongLiangAverage);
	}
	
	/**
	 * 重量实测值平均数
	 */
	public java.math.BigDecimal getZhongLiangAverage() {
		return get("zhongLiangAverage");
	}
	
	/**
	 * 总长判断结果
	 */
	public void setZongChangJudgmentResult(java.lang.String zongChangJudgmentResult) {
		set("zongChangJudgmentResult", zongChangJudgmentResult);
	}
	
	/**
	 * 总长判断结果
	 */
	public java.lang.String getZongChangJudgmentResult() {
		return getStr("zongChangJudgmentResult");
	}
	
	/**
	 * 宽判断结果
	 */
	public void setKuanJudgmentResult(java.lang.String kuanJudgmentResult) {
		set("kuanJudgmentResult", kuanJudgmentResult);
	}
	
	/**
	 * 宽判断结果
	 */
	public java.lang.String getKuanJudgmentResult() {
		return getStr("kuanJudgmentResult");
	}
	
	/**
	 * 头宽判断结果
	 */
	public void setTouKuanJudgmentResult(java.lang.String touKuanJudgmentResult) {
		set("touKuanJudgmentResult", touKuanJudgmentResult);
	}
	
	/**
	 * 头宽判断结果
	 */
	public java.lang.String getTouKuanJudgmentResult() {
		return getStr("touKuanJudgmentResult");
	}
	
	/**
	 * 复检单号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 外形标准
	 */
	public void setAppearanceRequired(java.lang.String appearanceRequired) {
		set("appearanceRequired", appearanceRequired);
	}
	
	/**
	 * 外形标准
	 */
	public java.lang.String getAppearanceRequired() {
		return getStr("appearanceRequired");
	}
	
}

