package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBascontract<M extends BaseBascontract<M>> extends Model<M> implements IBean {

	/**
	 * 合同的ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 合同的ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 电网合同编号
	 */
	public void setGridno(java.lang.String gridno) {
		set("gridno", gridno);
	}
	
	/**
	 * 电网合同编号
	 */
	public java.lang.String getGridno() {
		return getStr("gridno");
	}
	
	/**
	 * 国网经法合同编号
	 */
	public void setEcpno(java.lang.String ecpno) {
		set("ecpno", ecpno);
	}
	
	/**
	 * 国网经法合同编号
	 */
	public java.lang.String getEcpno() {
		return getStr("ecpno");
	}
	
	/**
	 * 器材合同编号
	 */
	public void setEquipno(java.lang.String equipno) {
		set("equipno", equipno);
	}
	
	/**
	 * 器材合同编号
	 */
	public java.lang.String getEquipno() {
		return getStr("equipno");
	}
	
	/**
	 * 合同的场内编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 合同的场内编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 合同的工程名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 合同的工程名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 合同的签订日期
	 */
	public void setSigndate(java.util.Date signdate) {
		set("signdate", signdate);
	}
	
	/**
	 * 合同的签订日期
	 */
	public java.util.Date getSigndate() {
		return getDate("signdate");
	}
	
	/**
	 * 合同的客户、供货商、运输商的顺序号
	 */
	public void setCustomerid(java.lang.Long customerid) {
		set("customerid", customerid);
	}
	
	/**
	 * 合同的客户、供货商、运输商的顺序号
	 */
	public java.lang.Long getCustomerid() {
		return getLong("customerid");
	}
	
	/**
	 * 运输费用的承担方，木箱
	 */
	public void setTranscost(java.math.BigDecimal transcost) {
		set("transcost", transcost);
	}
	
	/**
	 * 运输费用的承担方，木箱
	 */
	public java.math.BigDecimal getTranscost() {
		return get("transcost");
	}
	
	/**
	 * 销售员的id，纸箱
	 */
	public void setSalesmanid(java.lang.Long salesmanid) {
		set("salesmanid", salesmanid);
	}
	
	/**
	 * 销售员的id，纸箱
	 */
	public java.lang.Long getSalesmanid() {
		return getLong("salesmanid");
	}
	
	/**
	 * 合同的录入日期
	 */
	public void setIndate(java.util.Date indate) {
		set("indate", indate);
	}
	
	/**
	 * 合同的录入日期
	 */
	public java.util.Date getIndate() {
		return getDate("indate");
	}
	
	/**
	 * 包装费用的承担方，其他包装
	 */
	public void setCasingcost(java.math.BigDecimal casingcost) {
		set("casingcost", casingcost);
	}
	
	/**
	 * 包装费用的承担方，其他包装
	 */
	public java.math.BigDecimal getCasingcost() {
		return get("casingcost");
	}
	
	/**
	 * 交（提）货方式，货物运到期限
	 */
	public void setPicktype(java.lang.String picktype) {
		set("picktype", picktype);
	}
	
	/**
	 * 交（提）货方式，货物运到期限
	 */
	public java.lang.String getPicktype() {
		return getStr("picktype");
	}
	
	/**
	 * 运输方式，运输合同收货联系人电话
	 */
	public void setTranstype(java.lang.String transtype) {
		set("transtype", transtype);
	}
	
	/**
	 * 运输方式，运输合同收货联系人电话
	 */
	public java.lang.String getTranstype() {
		return getStr("transtype");
	}
	
	/**
	 * 到货地点，在采购合同中存放合约条款，运输合同货物到达地点
	 */
	public void setDestination(java.lang.String destination) {
		set("destination", destination);
	}
	
	/**
	 * 到货地点，在采购合同中存放合约条款，运输合同货物到达地点
	 */
	public java.lang.String getDestination() {
		return getStr("destination");
	}
	
	/**
	 * 接货人，外协产品协作加工合同表示审核人，在运输合同中表示到货单位详细地址
	 */
	public void setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
	}
	
	/**
	 * 接货人，外协产品协作加工合同表示审核人，在运输合同中表示到货单位详细地址
	 */
	public java.lang.String getReceiver() {
		return getStr("receiver");
	}
	
	/**
	 * 验收方式
	 */
	public void setChecktype(java.lang.String checktype) {
		set("checktype", checktype);
	}
	
	/**
	 * 验收方式
	 */
	public java.lang.String getChecktype() {
		return getStr("checktype");
	}
	
	/**
	 * -1表示已删除  合同所处的状态，10--录入，20--确认，30--下计划，40--生产中，50--发货，60--完成； 对于生产部，10--录入，20--已确认
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * -1表示已删除  合同所处的状态，10--录入，20--确认，30--下计划，40--生产中，50--发货，60--完成； 对于生产部，10--录入，20--已确认
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 大于0表示附加合同
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 大于0表示附加合同
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 合同所属的部门，10代表市场营销销售合同，11--市场营销运输合同，20代表物资供应采购合同，30-----生产部（外购产品）
	 */
	public void setOwner(java.lang.Integer owner) {
		set("owner", owner);
	}
	
	/**
	 * 合同所属的部门，10代表市场营销销售合同，11--市场营销运输合同，20代表物资供应采购合同，30-----生产部（外购产品）
	 */
	public java.lang.Integer getOwner() {
		return getInt("owner");
	}
	
	/**
	 * 其他事项，外协产品协作加工合同表示批准人，在运输合同中表示货物的起运地点
	 */
	public void setOther(java.lang.String other) {
		set("other", other);
	}
	
	/**
	 * 其他事项，外协产品协作加工合同表示批准人，在运输合同中表示货物的起运地点
	 */
	public java.lang.String getOther() {
		return getStr("other");
	}
	
	/**
	 * 合同所属的期间
	 */
	public void setTerm(java.lang.Integer term) {
		set("term", term);
	}
	
	/**
	 * 合同所属的期间
	 */
	public java.lang.Integer getTerm() {
		return getInt("term");
	}
	
	/**
	 * 合同录入的用户
	 */
	public void setUserid(java.lang.Long userid) {
		set("userid", userid);
	}
	
	/**
	 * 合同录入的用户
	 */
	public java.lang.Long getUserid() {
		return getLong("userid");
	}
	
	/**
	 * 合同的规则
	 */
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	/**
	 * 合同的规则
	 */
	public java.lang.String getRule() {
		return getStr("rule");
	}
	
	/**
	 * 合同的电压等级，1表220KV以下、2表330KV以上、3表3300KV以上
	 */
	public void setPressurestage(java.lang.Integer pressurestage) {
		set("pressurestage", pressurestage);
	}
	
	/**
	 * 合同的电压等级，1表220KV以下、2表330KV以上、3表3300KV以上
	 */
	public java.lang.Integer getPressurestage() {
		return getInt("pressurestage");
	}
	
	/**
	 * 客户的法定代表人
	 */
	public void setLegalrepresent(java.lang.String legalrepresent) {
		set("legalrepresent", legalrepresent);
	}
	
	/**
	 * 客户的法定代表人
	 */
	public java.lang.String getLegalrepresent() {
		return getStr("legalrepresent");
	}
	
	/**
	 * 客户的委托代理人
	 */
	public void setAgent(java.lang.String agent) {
		set("agent", agent);
	}
	
	/**
	 * 客户的委托代理人
	 */
	public java.lang.String getAgent() {
		return getStr("agent");
	}
	
	/**
	 * 客户的电话
	 */
	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	/**
	 * 客户的电话
	 */
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}
	
	/**
	 * 客户的传真
	 */
	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}
	
	/**
	 * 客户的传真
	 */
	public java.lang.String getFax() {
		return getStr("fax");
	}
	
	/**
	 * 客户的开户银行
	 */
	public void setBank(java.lang.String bank) {
		set("bank", bank);
	}
	
	/**
	 * 客户的开户银行
	 */
	public java.lang.String getBank() {
		return getStr("bank");
	}
	
	/**
	 * 客户的银行账号
	 */
	public void setBankcode(java.lang.String bankcode) {
		set("bankcode", bankcode);
	}
	
	/**
	 * 客户的银行账号
	 */
	public java.lang.String getBankcode() {
		return getStr("bankcode");
	}
	
	/**
	 * 客户的邮政编码
	 */
	public void setPostalcode(java.lang.String postalcode) {
		set("postalcode", postalcode);
	}
	
	/**
	 * 客户的邮政编码
	 */
	public java.lang.String getPostalcode() {
		return getStr("postalcode");
	}
	
	/**
	 * 客户的税务登记号
	 */
	public void setTaxnum(java.lang.String taxnum) {
		set("taxnum", taxnum);
	}
	
	/**
	 * 客户的税务登记号
	 */
	public java.lang.String getTaxnum() {
		return getStr("taxnum");
	}
	
	/**
	 * 附加合同的签订时间
	 */
	public void setAppenddate(java.util.Date appenddate) {
		set("appenddate", appenddate);
	}
	
	/**
	 * 附加合同的签订时间
	 */
	public java.util.Date getAppenddate() {
		return getDate("appenddate");
	}
	
	/**
	 * 合同类型
	 */
	public void setItemtype(java.lang.String itemtype) {
		set("itemtype", itemtype);
	}
	
	/**
	 * 合同类型
	 */
	public java.lang.String getItemtype() {
		return getStr("itemtype");
	}
	
	public void setOrgid(java.lang.Long orgid) {
		set("orgid", orgid);
	}
	
	public java.lang.Long getOrgid() {
		return getLong("orgid");
	}
	
	/**
	 * 0正常，1删除
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 0正常，1删除
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 交货时间
	 */
	public void setItemsenddate(java.util.Date itemsenddate) {
		set("itemsenddate", itemsenddate);
	}
	
	/**
	 * 交货时间
	 */
	public java.util.Date getItemsenddate() {
		return getDate("itemsenddate");
	}
	
}

