package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlinoutstore<M extends BasePlinoutstore<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 物料编号
	 */
	public void setMaterialno(java.lang.String materialno) {
		set("materialno", materialno);
	}
	
	/**
	 * 物料编号
	 */
	public java.lang.String getMaterialno() {
		return getStr("materialno");
	}
	
	/**
	 * 物料名称
	 */
	public void setMaterialname(java.lang.String materialname) {
		set("materialname", materialname);
	}
	
	/**
	 * 物料名称
	 */
	public java.lang.String getMaterialname() {
		return getStr("materialname");
	}
	
	/**
	 * 物料的单位(套、个、件等)
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 物料的单位(套、个、件等)
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 入出库数量
	 */
	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 入出库数量
	 */
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}
	
	/**
	 * 单价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 金额
	 */
	public void setTotalmoney(java.math.BigDecimal totalmoney) {
		set("totalmoney", totalmoney);
	}
	
	/**
	 * 金额
	 */
	public java.math.BigDecimal getTotalmoney() {
		return get("totalmoney");
	}
	
	/**
	 * 送货单位
	 */
	public void setDeliverunit(java.lang.String deliverunit) {
		set("deliverunit", deliverunit);
	}
	
	/**
	 * 送货单位
	 */
	public java.lang.String getDeliverunit() {
		return getStr("deliverunit");
	}
	
	/**
	 * 收货单位
	 */
	public void setReceiveunit(java.lang.String receiveunit) {
		set("receiveunit", receiveunit);
	}
	
	/**
	 * 收货单位
	 */
	public java.lang.String getReceiveunit() {
		return getStr("receiveunit");
	}
	
	/**
	 * 仓库(入出的哪个仓库)
	 */
	public void setStore(java.lang.String store) {
		set("store", store);
	}
	
	/**
	 * 仓库(入出的哪个仓库)
	 */
	public java.lang.String getStore() {
		return getStr("store");
	}
	
	/**
	 * 经手人
	 */
	public void setHandleperson(java.lang.String handleperson) {
		set("handleperson", handleperson);
	}
	
	/**
	 * 经手人
	 */
	public java.lang.String getHandleperson() {
		return getStr("handleperson");
	}
	
	/**
	 * 收发日期
	 */
	public void setReceivedate(java.util.Date receivedate) {
		set("receivedate", receivedate);
	}
	
	/**
	 * 收发日期
	 */
	public java.util.Date getReceivedate() {
		return getDate("receivedate");
	}
	
	/**
	 * 收发单号
	 */
	public void setOrderno(java.lang.String orderno) {
		set("orderno", orderno);
	}
	
	/**
	 * 收发单号
	 */
	public java.lang.String getOrderno() {
		return getStr("orderno");
	}
	
	/**
	 * 入库或出库(1入2出)
	 */
	public void setIsin(java.math.BigDecimal isin) {
		set("isin", isin);
	}
	
	/**
	 * 入库或出库(1入2出)
	 */
	public java.math.BigDecimal getIsin() {
		return get("isin");
	}
	
	/**
	 * 1表示销售出库2表示领用出库3调拨出库4表示其它出库10原材料库20一进一出帐
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 1表示销售出库2表示领用出库3调拨出库4表示其它出库10原材料库20一进一出帐
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setStatus(java.math.BigDecimal status) {
		set("status", status);
	}
	
	public java.math.BigDecimal getStatus() {
		return get("status");
	}
	
	public void setType(java.math.BigDecimal type) {
		set("type", type);
	}
	
	public java.math.BigDecimal getType() {
		return get("type");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 出入库时的期间
	 */
	public void setTerm(java.math.BigDecimal term) {
		set("term", term);
	}
	
	/**
	 * 出入库时的期间
	 */
	public java.math.BigDecimal getTerm() {
		return get("term");
	}
	
	/**
	 * 子单据号
	 */
	public void setChildorderno(java.lang.String childorderno) {
		set("childorderno", childorderno);
	}
	
	/**
	 * 子单据号
	 */
	public java.lang.String getChildorderno() {
		return getStr("childorderno");
	}
	
	/**
	 * 物料规格型号
	 */
	public void setSpec(java.lang.String spec) {
		set("spec", spec);
	}
	
	/**
	 * 物料规格型号
	 */
	public java.lang.String getSpec() {
		return getStr("spec");
	}
	
	/**
	 * 订单状态(录入,确认,入库)
	 */
	public void setOrderstatus(java.lang.String orderstatus) {
		set("orderstatus", orderstatus);
	}
	
	/**
	 * 订单状态(录入,确认,入库)
	 */
	public java.lang.String getOrderstatus() {
		return getStr("orderstatus");
	}
	
	/**
	 * 库保员帐号
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 库保员帐号
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	/**
	 * 该记录是否被删除(没删除0删除-1)
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 该记录是否被删除(没删除0删除-1)
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 规则
	 */
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	/**
	 * 规则
	 */
	public java.lang.String getRule() {
		return getStr("rule");
	}
	
	/**
	 * 合同号
	 */
	public void setContactno(java.lang.String contactno) {
		set("contactno", contactno);
	}
	
	/**
	 * 合同号
	 */
	public java.lang.String getContactno() {
		return getStr("contactno");
	}
	
	/**
	 * 工程名称
	 */
	public void setProjectname(java.lang.String projectname) {
		set("projectname", projectname);
	}
	
	/**
	 * 工程名称
	 */
	public java.lang.String getProjectname() {
		return getStr("projectname");
	}
	
	/**
	 * 领料人
	 */
	public void setLingliaoperson(java.lang.String lingliaoperson) {
		set("lingliaoperson", lingliaoperson);
	}
	
	/**
	 * 领料人
	 */
	public java.lang.String getLingliaoperson() {
		return getStr("lingliaoperson");
	}
	
	/**
	 * 类别
	 */
	public void setLeibie(java.lang.String leibie) {
		set("leibie", leibie);
	}
	
	/**
	 * 类别
	 */
	public java.lang.String getLeibie() {
		return getStr("leibie");
	}
	
	/**
	 * 图号
	 */
	public void setTuhao(java.lang.String tuhao) {
		set("tuhao", tuhao);
	}
	
	/**
	 * 图号
	 */
	public java.lang.String getTuhao() {
		return getStr("tuhao");
	}
	
	/**
	 * 检查部门
	 */
	public void setJianchaunit(java.lang.String jianchaunit) {
		set("jianchaunit", jianchaunit);
	}
	
	/**
	 * 检查部门
	 */
	public java.lang.String getJianchaunit() {
		return getStr("jianchaunit");
	}
	
	/**
	 * 单重
	 */
	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	/**
	 * 单重
	 */
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}
	
	/**
	 * 是否有发票,0无发票,1有发票,lgq
	 */
	public void setFapiao(java.lang.Integer fapiao) {
		set("fapiao", fapiao);
	}
	
	/**
	 * 是否有发票,0无发票,1有发票,lgq
	 */
	public java.lang.Integer getFapiao() {
		return getInt("fapiao");
	}
	
	/**
	 * 0正常出入库，1盘赢，2盘亏
	 */
	public void setPandian(java.lang.Integer pandian) {
		set("pandian", pandian);
	}
	
	/**
	 * 0正常出入库，1盘赢，2盘亏
	 */
	public java.lang.Integer getPandian() {
		return getInt("pandian");
	}
	
	/**
	 * 请领数量
	 */
	public void setQingling(java.math.BigDecimal qingling) {
		set("qingling", qingling);
	}
	
	/**
	 * 请领数量
	 */
	public java.math.BigDecimal getQingling() {
		return get("qingling");
	}
	
	/**
	 * 现行价格
	 */
	public void setNowprice(java.math.BigDecimal nowprice) {
		set("nowprice", nowprice);
	}
	
	/**
	 * 现行价格
	 */
	public java.math.BigDecimal getNowprice() {
		return get("nowprice");
	}
	
	/**
	 * 运输方式
	 */
	public void setTransportway(java.lang.String transportway) {
		set("transportway", transportway);
	}
	
	/**
	 * 运输方式
	 */
	public java.lang.String getTransportway() {
		return getStr("transportway");
	}
	
	/**
	 * 负责人
	 */
	public void setFuzeren(java.lang.String fuzeren) {
		set("fuzeren", fuzeren);
	}
	
	/**
	 * 负责人
	 */
	public java.lang.String getFuzeren() {
		return getStr("fuzeren");
	}
	
	public void setGouhuounitname(java.lang.String gouhuounitname) {
		set("gouhuounitname", gouhuounitname);
	}
	
	public java.lang.String getGouhuounitname() {
		return getStr("gouhuounitname");
	}
	
}

