package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasitem<M extends BaseBasitem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}
	
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	public void setSpec(java.lang.String spec) {
		set("spec", spec);
	}
	
	public java.lang.String getSpec() {
		return getStr("spec");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	public void setColor(java.lang.String color) {
		set("color", color);
	}
	
	public java.lang.String getColor() {
		return getStr("color");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}
	
	public void setPlannedPrice(java.math.BigDecimal plannedPrice) {
		set("planned_price", plannedPrice);
	}
	
	public java.math.BigDecimal getPlannedPrice() {
		return get("planned_price");
	}
	
	public void setAvgPrice(java.math.BigDecimal avgPrice) {
		set("avg_price", avgPrice);
	}
	
	public java.math.BigDecimal getAvgPrice() {
		return get("avg_price");
	}
	
	public void setLocation(java.lang.String location) {
		set("location", location);
	}
	
	public java.lang.String getLocation() {
		return getStr("location");
	}
	
	public void setTechMemo(java.lang.String techMemo) {
		set("tech_memo", techMemo);
	}
	
	public java.lang.String getTechMemo() {
		return getStr("tech_memo");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	public void setInclass(java.lang.String inclass) {
		set("inclass", inclass);
	}
	
	public java.lang.String getInclass() {
		return getStr("inclass");
	}
	
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 等级
	 */
	public void setGrade(java.lang.String grade) {
		set("grade", grade);
	}
	
	/**
	 * 等级
	 */
	public java.lang.String getGrade() {
		return getStr("grade");
	}
	
	/**
	 * 物料版本
	 */
	public void setMaterialVersion(java.lang.String materialVersion) {
		set("material_version", materialVersion);
	}
	
	/**
	 * 物料版本
	 */
	public java.lang.String getMaterialVersion() {
		return getStr("material_version");
	}
	
	/**
	 * 辅助属性
	 */
	public void setAuxiliaryAttribute(java.lang.String auxiliaryAttribute) {
		set("auxiliary_attribute", auxiliaryAttribute);
	}
	
	/**
	 * 辅助属性
	 */
	public java.lang.String getAuxiliaryAttribute() {
		return getStr("auxiliary_attribute");
	}
	
	/**
	 * 物料属性
	 */
	public void setMaterialAttribute(java.lang.String materialAttribute) {
		set("material_attribute", materialAttribute);
	}
	
	/**
	 * 物料属性
	 */
	public java.lang.String getMaterialAttribute() {
		return getStr("material_attribute");
	}
	
	/**
	 * 图号
	 */
	public void setTuzhiNo(java.lang.String tuzhiNo) {
		set("tuzhiNo", tuzhiNo);
	}
	
	/**
	 * 图号
	 */
	public java.lang.String getTuzhiNo() {
		return getStr("tuzhiNo");
	}
	
	/**
	 * 关联basItemClass表的id，存的是第三级分类
	 */
	public void setClassId(java.lang.Integer classId) {
		set("classId", classId);
	}
	
	/**
	 * 关联basItemClass表的id，存的是第三级分类
	 */
	public java.lang.Integer getClassId() {
		return getInt("classId");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 执行标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 执行标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 录入时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 设计重量
	 */
	public void setPlanWeight(java.math.BigDecimal planWeight) {
		set("planWeight", planWeight);
	}
	
	/**
	 * 设计重量
	 */
	public java.math.BigDecimal getPlanWeight() {
		return get("planWeight");
	}
	
}

