package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClJyhLc<M extends BaseClJyhLc<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库单号
	 */
	public void setOrderno(java.lang.String orderno) {
		set("orderno", orderno);
	}
	
	/**
	 * 入库单号
	 */
	public java.lang.String getOrderno() {
		return getStr("orderno");
	}
	
	/**
	 * 来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 化学成分分析-Al
	 */
	public void setChemAl(java.math.BigDecimal chemAl) {
		set("chemAl", chemAl);
	}
	
	/**
	 * 化学成分分析-Al
	 */
	public java.math.BigDecimal getChemAl() {
		return get("chemAl");
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分分析-Fe
	 */
	public void setChemFe(java.math.BigDecimal chemFe) {
		set("chemFe", chemFe);
	}
	
	/**
	 * 化学成分分析-Fe
	 */
	public java.math.BigDecimal getChemFe() {
		return get("chemFe");
	}
	
	/**
	 * 化学成分分析-Cu
	 */
	public void setChemCu(java.math.BigDecimal chemCu) {
		set("chemCu", chemCu);
	}
	
	/**
	 * 化学成分分析-Cu
	 */
	public java.math.BigDecimal getChemCu() {
		return get("chemCu");
	}
	
	/**
	 * 化学成分分析-Mg
	 */
	public void setChemMg(java.math.BigDecimal chemMg) {
		set("chemMg", chemMg);
	}
	
	/**
	 * 化学成分分析-Mg
	 */
	public java.math.BigDecimal getChemMg() {
		return get("chemMg");
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分分析-Zn
	 */
	public void setChemZn(java.math.BigDecimal chemZn) {
		set("chemZn", chemZn);
	}
	
	/**
	 * 化学成分分析-Zn
	 */
	public java.math.BigDecimal getChemZn() {
		return get("chemZn");
	}
	
	/**
	 * 化学成分分析-Ti
	 */
	public void setChemTi(java.math.BigDecimal chemTi) {
		set("chemTi", chemTi);
	}
	
	/**
	 * 化学成分分析-Ti
	 */
	public java.math.BigDecimal getChemTi() {
		return get("chemTi");
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public void setChemCr(java.math.BigDecimal chemCr) {
		set("chemCr", chemCr);
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public java.math.BigDecimal getChemCr() {
		return get("chemCr");
	}
	
	/**
	 * 外观、表面质量
	 */
	public void setSurfaceQuality(java.lang.String surfaceQuality) {
		set("surfaceQuality", surfaceQuality);
	}
	
	/**
	 * 外观、表面质量
	 */
	public java.lang.String getSurfaceQuality() {
		return getStr("surfaceQuality");
	}
	
	/**
	 * 尺寸
	 */
	public void setSize(java.lang.String size) {
		set("size", size);
	}
	
	/**
	 * 尺寸
	 */
	public java.lang.String getSize() {
		return getStr("size");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeavefactoryDate(java.util.Date leavefactoryDate) {
		set("leavefactoryDate", leavefactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeavefactoryDate() {
		return getDate("leavefactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 合同编号，关联bascontract.no
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号，关联bascontract.no
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 生产工单号，关联plshengchangongdan.woNo
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 生产工单号，关联plshengchangongdan.woNo
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
	/**
	 * 生产订单号，根据woNo自动填充
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 生产订单号，根据woNo自动填充
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 录入人，关联登录用户realName
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人，关联登录用户realName
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间，自动生成
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 录入时间，自动生成
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 标志
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 删除标记，0为正常
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 删除标记，0为正常
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 单据号
	 */
	public void setBasno(java.lang.String basno) {
		set("basno", basno);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasno() {
		return getStr("basno");
	}
	
}

