package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlpaichanjihua<M extends BasePlpaichanjihua<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 采购订单行项目 ID
	 */
	public void setPoItemId(java.lang.Long poItemId) {
		set("poItemId", poItemId);
	}
	
	/**
	 * 采购订单行项目 ID
	 */
	public java.lang.Long getPoItemId() {
		return getLong("poItemId");
	}
	
	/**
	 * 排产计划编码
	 */
	public void setScheduleCode(java.lang.String scheduleCode) {
		set("scheduleCode", scheduleCode);
	}
	
	/**
	 * 排产计划编码
	 */
	public java.lang.String getScheduleCode() {
		return getStr("scheduleCode");
	}
	
	/**
	 * 生成工单对应的物料ID，关联plgongdanitem表的id字段
	 */
	public void setGdItemId(java.lang.Long gdItemId) {
		set("gdItemId", gdItemId);
	}
	
	/**
	 * 生成工单对应的物料ID，关联plgongdanitem表的id字段
	 */
	public java.lang.Long getGdItemId() {
		return getLong("gdItemId");
	}
	
	/**
	 * 省公司单位编码
	 */
	public void setProvCoCode(java.lang.String provCoCode) {
		set("provCoCode", provCoCode);
	}
	
	/**
	 * 省公司单位编码
	 */
	public java.lang.String getProvCoCode() {
		return getStr("provCoCode");
	}
	
	/**
	 * 省公司单位名称
	 */
	public void setProvCoName(java.lang.String provCoName) {
		set("provCoName", provCoName);
	}
	
	/**
	 * 省公司单位名称
	 */
	public java.lang.String getProvCoName() {
		return getStr("provCoName");
	}
	
	/**
	 * 计划工期（天数）
	 */
	public void setPlanPeriod(java.lang.String planPeriod) {
		set("planPeriod", planPeriod);
	}
	
	/**
	 * 计划工期（天数）
	 */
	public java.lang.String getPlanPeriod() {
		return getStr("planPeriod");
	}
	
	/**
	 * 实际工期
	 */
	public void setActualPeriod(java.lang.String actualPeriod) {
		set("actualPeriod", actualPeriod);
	}
	
	/**
	 * 实际工期
	 */
	public java.lang.String getActualPeriod() {
		return getStr("actualPeriod");
	}
	
	/**
	 * 进度
	 */
	public void setSchedule(java.lang.String schedule) {
		set("schedule", schedule);
	}
	
	/**
	 * 进度
	 */
	public java.lang.String getSchedule() {
		return getStr("schedule");
	}
	
	/**
	 * 交付日期（最后日期，底线）
	 */
	public void setDueDate(java.util.Date dueDate) {
		set("dueDate", dueDate);
	}
	
	/**
	 * 交付日期（最后日期，底线）
	 */
	public java.util.Date getDueDate() {
		return getDate("dueDate");
	}
	
	/**
	 * 计划开始日期
	 */
	public void setPlanStartDate(java.util.Date planStartDate) {
		set("planStartDate", planStartDate);
	}
	
	/**
	 * 计划开始日期
	 */
	public java.util.Date getPlanStartDate() {
		return getDate("planStartDate");
	}
	
	/**
	 * 计划完成日期
	 */
	public void setPlanFinishDate(java.util.Date planFinishDate) {
		set("planFinishDate", planFinishDate);
	}
	
	/**
	 * 计划完成日期
	 */
	public java.util.Date getPlanFinishDate() {
		return getDate("planFinishDate");
	}
	
	/**
	 * 实际开始日期
	 */
	public void setActualStartDate(java.util.Date actualStartDate) {
		set("actualStartDate", actualStartDate);
	}
	
	/**
	 * 实际开始日期
	 */
	public java.util.Date getActualStartDate() {
		return getDate("actualStartDate");
	}
	
	/**
	 * 实际完成日期
	 */
	public void setActualFinishDate(java.util.Date actualFinishDate) {
		set("actualFinishDate", actualFinishDate);
	}
	
	/**
	 * 实际完成日期
	 */
	public java.util.Date getActualFinishDate() {
		return getDate("actualFinishDate");
	}
	
	/**
	 * 品类编码
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 数据来源
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 数据拥有方
	 */
	public void setOwnerId(java.lang.String ownerId) {
		set("ownerId", ownerId);
	}
	
	/**
	 * 数据拥有方
	 */
	public java.lang.String getOwnerId() {
		return getStr("ownerId");
	}
	
	/**
	 * 数据可见方
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 数据可见方
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}
	
	/**
	 * 类型，预留
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型，预留
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 状态，预留
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，预留
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 标志，预留
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志，预留
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间
	 */
	public void setWritetime(java.util.Date writetime) {
		set("writetime", writetime);
	}
	
	/**
	 * 录入时间
	 */
	public java.util.Date getWritetime() {
		return getDate("writetime");
	}
	
	/**
	 * 删除标记，0为正常
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 删除标记，0为正常
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 关联的工单号
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 关联的工单号
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
	/**
	 * 厂内合同号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 厂内合同号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 关联的生产订单号
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 关联的生产订单号
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
}

