package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlReporderMaterial<M extends BasePlReporderMaterial<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * pl_report_work_order表的Id
	 */
	public void setRepOrderId(java.lang.Integer repOrderId) {
		set("repOrderId", repOrderId);
	}
	
	/**
	 * pl_report_work_order表的Id
	 */
	public java.lang.Integer getRepOrderId() {
		return getInt("repOrderId");
	}
	
	/**
	 * pl_material_request_detail表的Id
	 */
	public void setMatDetailId(java.lang.Integer matDetailId) {
		set("matDetailId", matDetailId);
	}
	
	/**
	 * pl_material_request_detail表的Id
	 */
	public java.lang.Integer getMatDetailId() {
		return getInt("matDetailId");
	}
	
	/**
	 * 使用数量
	 */
	public void setUsedQty(java.lang.Integer usedQty) {
		set("usedQty", usedQty);
	}
	
	/**
	 * 使用数量
	 */
	public java.lang.Integer getUsedQty() {
		return getInt("usedQty");
	}
	
	/**
	 * 报工人id
	 */
	public void setReportUserId(java.lang.Integer reportUserId) {
		set("reportUserId", reportUserId);
	}
	
	/**
	 * 报工人id
	 */
	public java.lang.Integer getReportUserId() {
		return getInt("reportUserId");
	}
	
	/**
	 * 报工人名字
	 */
	public void setReportUsername(java.lang.String reportUsername) {
		set("reportUsername", reportUsername);
	}
	
	/**
	 * 报工人名字
	 */
	public java.lang.String getReportUsername() {
		return getStr("reportUsername");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
}

