package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasItemRelation<M extends BaseBasItemRelation<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键，唯一标识一条物料父子关系记录
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增主键，唯一标识一条物料父子关系记录
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 父级物料ID，关联物料主表的主键，标识当前子物料的直接上级；产成品无父级时可为NULL
	 */
	public void setParentItemId(java.lang.Integer parentItemId) {
		set("parentItemId", parentItemId);
	}
	
	/**
	 * 父级物料ID，关联物料主表的主键，标识当前子物料的直接上级；产成品无父级时可为NULL
	 */
	public java.lang.Integer getParentItemId() {
		return getInt("parentItemId");
	}
	
	/**
	 * 子级物料ID，关联物料主表的主键，标识当前父物料的直接下级；原材料无下级时无对应记录
	 */
	public void setChildItemId(java.lang.Integer childItemId) {
		set("childItemId", childItemId);
	}
	
	/**
	 * 子级物料ID，关联物料主表的主键，标识当前父物料的直接下级；原材料无下级时无对应记录
	 */
	public java.lang.Integer getChildItemId() {
		return getInt("childItemId");
	}
	
	/**
	 * 父级物料类型：1=产成品（最终成品），2=半成品（需进一步拆分），3=原材料（不可拆分的基础物料）
	 */
	public void setParentItemType(java.lang.Integer parentItemType) {
		set("parentItemType", parentItemType);
	}
	
	/**
	 * 父级物料类型：1=产成品（最终成品），2=半成品（需进一步拆分），3=原材料（不可拆分的基础物料）
	 */
	public java.lang.Integer getParentItemType() {
		return getInt("parentItemType");
	}
	
	/**
	 * 子级物料类型：1=产成品，2=半成品（需继续拆分），3=原材料（拆分终止节点）
	 */
	public void setChildItemType(java.lang.Integer childItemType) {
		set("childItemType", childItemType);
	}
	
	/**
	 * 子级物料类型：1=产成品，2=半成品（需继续拆分），3=原材料（拆分终止节点）
	 */
	public java.lang.Integer getChildItemType() {
		return getInt("childItemType");
	}
	
	/**
	 * 子级物料的用量，根据业务场景表示数量（个）或重量（kg等），保留3位小数以支持高精度计量
	 */
	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 子级物料的用量，根据业务场景表示数量（个）或重量（kg等），保留3位小数以支持高精度计量
	 */
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}
	
	/**
	 * 备注信息，可存储物料拆分的特殊说明（如"此半成品需冷藏保存"、"用量需按批次调整"等）
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注信息，可存储物料拆分的特殊说明（如"此半成品需冷藏保存"、"用量需按批次调整"等）
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
}

