package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlMatInoutList<M extends BasePlMatInoutList<M>> extends Model<M> implements IBean {

	/**
	 * 明细主键（通用）
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 明细主键（通用）
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 关联检验单据号（通用）
	 */
	public void setInspOrderNo(java.lang.String inspOrderNo) {
		set("inspOrderNo", inspOrderNo);
	}
	
	/**
	 * 关联检验单据号（通用）
	 */
	public java.lang.String getInspOrderNo() {
		return getStr("inspOrderNo");
	}
	
	/**
	 * 操作仓库（通用）
	 */
	public void setWarehouse(java.lang.String warehouse) {
		set("warehouse", warehouse);
	}
	
	/**
	 * 操作仓库（通用）
	 */
	public java.lang.String getWarehouse() {
		return getStr("warehouse");
	}
	
	/**
	 * 关联合同编号（通用）
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 关联合同编号（通用）
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 关联合同名称（通用）
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 关联合同名称（通用）
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 供应商名称 （入库用）
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称 （入库用）
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 物料编号（通用）
	 */
	public void setMaterialCode(java.lang.String materialCode) {
		set("materialCode", materialCode);
	}
	
	/**
	 * 物料编号（通用）
	 */
	public java.lang.String getMaterialCode() {
		return getStr("materialCode");
	}
	
	/**
	 * 物料名称（通用）
	 */
	public void setMaterialName(java.lang.String materialName) {
		set("materialName", materialName);
	}
	
	/**
	 * 物料名称（通用）
	 */
	public java.lang.String getMaterialName() {
		return getStr("materialName");
	}
	
	/**
	 * 规格型号（通用）
	 */
	public void setMaterialSpec(java.lang.String materialSpec) {
		set("materialSpec", materialSpec);
	}
	
	/**
	 * 规格型号（通用）
	 */
	public java.lang.String getMaterialSpec() {
		return getStr("materialSpec");
	}
	
	/**
	 * 计量单位（通用）
	 */
	public void setMaterialUnit(java.lang.String materialUnit) {
		set("materialUnit", materialUnit);
	}
	
	/**
	 * 计量单位（通用）
	 */
	public java.lang.String getMaterialUnit() {
		return getStr("materialUnit");
	}
	
	/**
	 * 数量（入库正数，出库负数）（通用）
	 */
	public void setActualQuantity(java.math.BigDecimal actualQuantity) {
		set("actualQuantity", actualQuantity);
	}
	
	/**
	 * 数量（入库正数，出库负数）（通用）
	 */
	public java.math.BigDecimal getActualQuantity() {
		return get("actualQuantity");
	}
	
	/**
	 * 实际重量（入库正数，出库负数）（通用）
	 */
	public void setActualWeight(java.math.BigDecimal actualWeight) {
		set("actualWeight", actualWeight);
	}
	
	/**
	 * 实际重量（入库正数，出库负数）（通用）
	 */
	public java.math.BigDecimal getActualWeight() {
		return get("actualWeight");
	}
	
	/**
	 * 炉批号（通用）
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号（通用）
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 物料类别（通用）
	 */
	public void setInclass(java.lang.String inclass) {
		set("inclass", inclass);
	}
	
	/**
	 * 物料类别（通用）
	 */
	public java.lang.String getInclass() {
		return getStr("inclass");
	}
	
	/**
	 * 材质（通用）
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质（通用）
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 计划材质（入库用）
	 */
	public void setPlanMaterial(java.lang.String planMaterial) {
		set("planMaterial", planMaterial);
	}
	
	/**
	 * 计划材质（入库用）
	 */
	public java.lang.String getPlanMaterial() {
		return getStr("planMaterial");
	}
	
	/**
	 * 计划规格（入库用）
	 */
	public void setPlanSpec(java.lang.String planSpec) {
		set("planSpec", planSpec);
	}
	
	/**
	 * 计划规格（入库用）
	 */
	public java.lang.String getPlanSpec() {
		return getStr("planSpec");
	}
	
	/**
	 * 计划数量（入库用）
	 */
	public void setPlanQuantity(java.math.BigDecimal planQuantity) {
		set("planQuantity", planQuantity);
	}
	
	/**
	 * 计划数量（入库用）
	 */
	public java.math.BigDecimal getPlanQuantity() {
		return get("planQuantity");
	}
	
	/**
	 * 计划重量（入库用）
	 */
	public void setPlanWeight(java.math.BigDecimal planWeight) {
		set("planWeight", planWeight);
	}
	
	/**
	 * 计划重量（入库用）
	 */
	public java.math.BigDecimal getPlanWeight() {
		return get("planWeight");
	}
	
	/**
	 * 单价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 金额
	 */
	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("totalPrice", totalPrice);
	}
	
	/**
	 * 金额
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("totalPrice");
	}
	
	/**
	 * 明细备注（通用）
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 明细备注（通用）
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 出入库时间（通用）
	 */
	public void setOperateTime(java.util.Date operateTime) {
		set("operateTime", operateTime);
	}
	
	/**
	 * 出入库时间（通用）
	 */
	public java.util.Date getOperateTime() {
		return getDate("operateTime");
	}
	
	/**
	 * 明细状态（通用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 明细状态（通用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 盘点类型（通用）
	 */
	public void setInventoryCheckType(java.lang.Integer inventoryCheckType) {
		set("inventoryCheckType", inventoryCheckType);
	}
	
	/**
	 * 盘点类型（通用）
	 */
	public java.lang.Integer getInventoryCheckType() {
		return getInt("inventoryCheckType");
	}
	
	/**
	 * 出入库类型1入库，2出库
	 */
	public void setType(java.lang.Byte type) {
		set("type", type);
	}
	
	/**
	 * 出入库类型1入库，2出库
	 */
	public java.lang.Byte getType() {
		return getByte("type");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 期间
	 */
	public void setTerm(java.lang.String term) {
		set("term", term);
	}
	
	/**
	 * 期间
	 */
	public java.lang.String getTerm() {
		return getStr("term");
	}
	
	/**
	 * 重量单位
	 */
	public void setWeightUnit(java.lang.String weightUnit) {
		set("weightUnit", weightUnit);
	}
	
	/**
	 * 重量单位
	 */
	public java.lang.String getWeightUnit() {
		return getStr("weightUnit");
	}
	
	/**
	 * 剩余数量/重量
	 */
	public void setRemainingQuantity(java.math.BigDecimal remainingQuantity) {
		set("remainingQuantity", remainingQuantity);
	}
	
	/**
	 * 剩余数量/重量
	 */
	public java.math.BigDecimal getRemainingQuantity() {
		return get("remainingQuantity");
	}
	
	/**
	 * 出库用，关联本表表示出库的哪个入库记录
	 */
	public void setParentId(java.lang.Long parentId) {
		set("parentId", parentId);
	}
	
	/**
	 * 出库用，关联本表表示出库的哪个入库记录
	 */
	public java.lang.Long getParentId() {
		return getLong("parentId");
	}
	
}

