package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClBkx<M extends BaseClBkx<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库单号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库单号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分分析-C
	 */
	public void setChemC(java.math.BigDecimal chemC) {
		set("chemC", chemC);
	}
	
	/**
	 * 化学成分分析-C
	 */
	public java.math.BigDecimal getChemC() {
		return get("chemC");
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分分析-Ni
	 */
	public void setChemNi(java.math.BigDecimal chemNi) {
		set("chemNi", chemNi);
	}
	
	/**
	 * 化学成分分析-Ni
	 */
	public java.math.BigDecimal getChemNi() {
		return get("chemNi");
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public void setChemCr(java.math.BigDecimal chemCr) {
		set("chemCr", chemCr);
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public java.math.BigDecimal getChemCr() {
		return get("chemCr");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeavefactoryDate(java.util.Date leavefactoryDate) {
		set("leavefactoryDate", leavefactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeavefactoryDate() {
		return getDate("leavefactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasno(java.lang.String basno) {
		set("basno", basno);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasno() {
		return getStr("basno");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	public void setQuantity(java.lang.String quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.String getQuantity() {
		return getStr("quantity");
	}
	
	/**
	 * 总抽检数量
	 */
	public void setSampleQuantity(java.lang.String sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 总抽检数量
	 */
	public java.lang.String getSampleQuantity() {
		return getStr("sampleQuantity");
	}
	
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 规格
	 */
	public void setSpecs(java.lang.String specs) {
		set("specs", specs);
	}
	
	/**
	 * 规格
	 */
	public java.lang.String getSpecs() {
		return getStr("specs");
	}
	
	/**
	 * 尺寸
	 */
	public void setSize(java.lang.String size) {
		set("size", size);
	}
	
	/**
	 * 尺寸
	 */
	public java.lang.String getSize() {
		return getStr("size");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setCompInspQty(java.math.BigDecimal compInspQty) {
		set("compInspQty", compInspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getCompInspQty() {
		return get("compInspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public void setChemCRequired(java.math.BigDecimal chemCRequired) {
		set("chemCRequired", chemCRequired);
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public java.math.BigDecimal getChemCRequired() {
		return get("chemCRequired");
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public void setChemSiRequired(java.math.BigDecimal chemSiRequired) {
		set("chemSiRequired", chemSiRequired);
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public java.math.BigDecimal getChemSiRequired() {
		return get("chemSiRequired");
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public void setChemMnRequired(java.math.BigDecimal chemMnRequired) {
		set("chemMnRequired", chemMnRequired);
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public java.math.BigDecimal getChemMnRequired() {
		return get("chemMnRequired");
	}
	
	/**
	 * 化学成分要求值-Ni
	 */
	public void setChemNiRequired(java.math.BigDecimal chemNiRequired) {
		set("chemNiRequired", chemNiRequired);
	}
	
	/**
	 * 化学成分要求值-Ni
	 */
	public java.math.BigDecimal getChemNiRequired() {
		return get("chemNiRequired");
	}
	
	/**
	 * 化学成分要求值-Cr
	 */
	public void setChemCrRequired(java.math.BigDecimal chemCrRequired) {
		set("chemCrRequired", chemCrRequired);
	}
	
	/**
	 * 化学成分要求值-Cr
	 */
	public java.math.BigDecimal getChemCrRequired() {
		return get("chemCrRequired");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 尺寸s实测值1
	 */
	public void setSizeS1(java.math.BigDecimal sizeS1) {
		set("sizeS1", sizeS1);
	}
	
	/**
	 * 尺寸s实测值1
	 */
	public java.math.BigDecimal getSizeS1() {
		return get("sizeS1");
	}
	
	/**
	 * 尺寸s实测值2
	 */
	public void setSizeS2(java.math.BigDecimal sizeS2) {
		set("sizeS2", sizeS2);
	}
	
	/**
	 * 尺寸s实测值2
	 */
	public java.math.BigDecimal getSizeS2() {
		return get("sizeS2");
	}
	
	/**
	 * 尺寸s实测值3
	 */
	public void setSizeS3(java.math.BigDecimal sizeS3) {
		set("sizeS3", sizeS3);
	}
	
	/**
	 * 尺寸s实测值3
	 */
	public java.math.BigDecimal getSizeS3() {
		return get("sizeS3");
	}
	
	/**
	 * 尺寸s实测值4
	 */
	public void setSizeS4(java.math.BigDecimal sizeS4) {
		set("sizeS4", sizeS4);
	}
	
	/**
	 * 尺寸s实测值4
	 */
	public java.math.BigDecimal getSizeS4() {
		return get("sizeS4");
	}
	
	/**
	 * 尺寸s实测值5
	 */
	public void setSizeS5(java.math.BigDecimal sizeS5) {
		set("sizeS5", sizeS5);
	}
	
	/**
	 * 尺寸s实测值5
	 */
	public java.math.BigDecimal getSizeS5() {
		return get("sizeS5");
	}
	
	/**
	 * 尺寸s实测值6
	 */
	public void setSizeS6(java.math.BigDecimal sizeS6) {
		set("sizeS6", sizeS6);
	}
	
	/**
	 * 尺寸s实测值6
	 */
	public java.math.BigDecimal getSizeS6() {
		return get("sizeS6");
	}
	
	/**
	 * 尺寸s要求值
	 */
	public void setSizeSRequired(java.math.BigDecimal sizeSRequired) {
		set("sizeSRequired", sizeSRequired);
	}
	
	/**
	 * 尺寸s要求值
	 */
	public java.math.BigDecimal getSizeSRequired() {
		return get("sizeSRequired");
	}
	
	/**
	 * 尺寸d实测值1
	 */
	public void setSizeD1(java.math.BigDecimal sizeD1) {
		set("sizeD1", sizeD1);
	}
	
	/**
	 * 尺寸d实测值1
	 */
	public java.math.BigDecimal getSizeD1() {
		return get("sizeD1");
	}
	
	/**
	 * 尺寸d实测值2
	 */
	public void setSizeD2(java.math.BigDecimal sizeD2) {
		set("sizeD2", sizeD2);
	}
	
	/**
	 * 尺寸d实测值2
	 */
	public java.math.BigDecimal getSizeD2() {
		return get("sizeD2");
	}
	
	/**
	 * 尺寸d实测值3
	 */
	public void setSizeD3(java.math.BigDecimal sizeD3) {
		set("sizeD3", sizeD3);
	}
	
	/**
	 * 尺寸d实测值3
	 */
	public java.math.BigDecimal getSizeD3() {
		return get("sizeD3");
	}
	
	/**
	 * 尺寸d实测值4
	 */
	public void setSizeD4(java.math.BigDecimal sizeD4) {
		set("sizeD4", sizeD4);
	}
	
	/**
	 * 尺寸d实测值4
	 */
	public java.math.BigDecimal getSizeD4() {
		return get("sizeD4");
	}
	
	/**
	 * 尺寸d实测值5
	 */
	public void setSizeD5(java.math.BigDecimal sizeD5) {
		set("sizeD5", sizeD5);
	}
	
	/**
	 * 尺寸d实测值5
	 */
	public java.math.BigDecimal getSizeD5() {
		return get("sizeD5");
	}
	
	/**
	 * 尺寸d实测值6
	 */
	public void setSizeD6(java.math.BigDecimal sizeD6) {
		set("sizeD6", sizeD6);
	}
	
	/**
	 * 尺寸d实测值6
	 */
	public java.math.BigDecimal getSizeD6() {
		return get("sizeD6");
	}
	
	/**
	 * 尺寸d要求值
	 */
	public void setSizeDRequired(java.math.BigDecimal sizeDRequired) {
		set("sizeDRequired", sizeDRequired);
	}
	
	/**
	 * 尺寸d要求值
	 */
	public java.math.BigDecimal getSizeDRequired() {
		return get("sizeDRequired");
	}
	
	/**
	 * 尺寸D实测值1
	 */
	public void setSizeBigD1(java.math.BigDecimal sizeBigD1) {
		set("sizeBigD1", sizeBigD1);
	}
	
	/**
	 * 尺寸D实测值1
	 */
	public java.math.BigDecimal getSizeBigD1() {
		return get("sizeBigD1");
	}
	
	/**
	 * 尺寸D实测值2
	 */
	public void setSizeBigD2(java.math.BigDecimal sizeBigD2) {
		set("sizeBigD2", sizeBigD2);
	}
	
	/**
	 * 尺寸D实测值2
	 */
	public java.math.BigDecimal getSizeBigD2() {
		return get("sizeBigD2");
	}
	
	/**
	 * 尺寸D实测值3
	 */
	public void setSizeBigD3(java.math.BigDecimal sizeBigD3) {
		set("sizeBigD3", sizeBigD3);
	}
	
	/**
	 * 尺寸D实测值3
	 */
	public java.math.BigDecimal getSizeBigD3() {
		return get("sizeBigD3");
	}
	
	/**
	 * 尺寸D实测值4
	 */
	public void setSizeBigD4(java.math.BigDecimal sizeBigD4) {
		set("sizeBigD4", sizeBigD4);
	}
	
	/**
	 * 尺寸D实测值4
	 */
	public java.math.BigDecimal getSizeBigD4() {
		return get("sizeBigD4");
	}
	
	/**
	 * 尺寸D实测值5
	 */
	public void setSizeBigD5(java.math.BigDecimal sizeBigD5) {
		set("sizeBigD5", sizeBigD5);
	}
	
	/**
	 * 尺寸D实测值5
	 */
	public java.math.BigDecimal getSizeBigD5() {
		return get("sizeBigD5");
	}
	
	/**
	 * 尺寸D实测值6
	 */
	public void setSizeBigD6(java.math.BigDecimal sizeBigD6) {
		set("sizeBigD6", sizeBigD6);
	}
	
	/**
	 * 尺寸D实测值6
	 */
	public java.math.BigDecimal getSizeBigD6() {
		return get("sizeBigD6");
	}
	
	/**
	 * 尺寸D要求值
	 */
	public void setSizeBigDRequired(java.math.BigDecimal sizeBigDRequired) {
		set("sizeBigDRequired", sizeBigDRequired);
	}
	
	/**
	 * 尺寸D要求值
	 */
	public java.math.BigDecimal getSizeBigDRequired() {
		return get("sizeBigDRequired");
	}
	
	/**
	 * 尺寸L2实测值1
	 */
	public void setSizeL21(java.math.BigDecimal sizeL21) {
		set("sizeL21", sizeL21);
	}
	
	/**
	 * 尺寸L2实测值1
	 */
	public java.math.BigDecimal getSizeL21() {
		return get("sizeL21");
	}
	
	/**
	 * 尺寸L2实测值2
	 */
	public void setSizeL22(java.math.BigDecimal sizeL22) {
		set("sizeL22", sizeL22);
	}
	
	/**
	 * 尺寸L2实测值2
	 */
	public java.math.BigDecimal getSizeL22() {
		return get("sizeL22");
	}
	
	/**
	 * 尺寸L2实测值3
	 */
	public void setSizeL23(java.math.BigDecimal sizeL23) {
		set("sizeL23", sizeL23);
	}
	
	/**
	 * 尺寸L2实测值3
	 */
	public java.math.BigDecimal getSizeL23() {
		return get("sizeL23");
	}
	
	/**
	 * 尺寸L2实测值4
	 */
	public void setSizeL24(java.math.BigDecimal sizeL24) {
		set("sizeL24", sizeL24);
	}
	
	/**
	 * 尺寸L2实测值4
	 */
	public java.math.BigDecimal getSizeL24() {
		return get("sizeL24");
	}
	
	/**
	 * 尺寸L2实测值5
	 */
	public void setSizeL25(java.math.BigDecimal sizeL25) {
		set("sizeL25", sizeL25);
	}
	
	/**
	 * 尺寸L2实测值5
	 */
	public java.math.BigDecimal getSizeL25() {
		return get("sizeL25");
	}
	
	/**
	 * 尺寸L2实测值6
	 */
	public void setSizeL26(java.math.BigDecimal sizeL26) {
		set("sizeL26", sizeL26);
	}
	
	/**
	 * 尺寸L2实测值6
	 */
	public java.math.BigDecimal getSizeL26() {
		return get("sizeL26");
	}
	
	/**
	 * 尺寸L2要求值
	 */
	public void setSizeL2Required(java.math.BigDecimal sizeL2Required) {
		set("sizeL2Required", sizeL2Required);
	}
	
	/**
	 * 尺寸L2要求值
	 */
	public java.math.BigDecimal getSizeL2Required() {
		return get("sizeL2Required");
	}
	
}

