package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasmaterial<M extends BaseBasmaterial<M>> extends Model<M> implements IBean {

	/**
	 * 唯一标识ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 唯一标识ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 原材料编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 原材料编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 原材料名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 原材料名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 规格
	 */
	public void setSpec(java.lang.String spec) {
		set("spec", spec);
	}
	
	/**
	 * 规格
	 */
	public java.lang.String getSpec() {
		return getStr("spec");
	}
	
	/**
	 * 质量等级
	 */
	public void setQuality(java.lang.String quality) {
		set("quality", quality);
	}
	
	/**
	 * 质量等级
	 */
	public java.lang.String getQuality() {
		return getStr("quality");
	}
	
	/**
	 * 材料标题
	 */
	public void setMaterialTitle(java.lang.String materialTitle) {
		set("material_title", materialTitle);
	}
	
	/**
	 * 材料标题
	 */
	public java.lang.String getMaterialTitle() {
		return getStr("material_title");
	}
	
	/**
	 * 材料规格
	 */
	public void setMaterialSpec(java.lang.String materialSpec) {
		set("material_spec", materialSpec);
	}
	
	/**
	 * 材料规格
	 */
	public java.lang.String getMaterialSpec() {
		return getStr("material_spec");
	}
	
	/**
	 * 材料消耗量
	 */
	public void setMaterialConsume(java.math.BigDecimal materialConsume) {
		set("material_consume", materialConsume);
	}
	
	/**
	 * 材料消耗量
	 */
	public java.math.BigDecimal getMaterialConsume() {
		return get("material_consume");
	}
	
	/**
	 * 重量
	 */
	public void setWeight(java.math.BigDecimal weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.math.BigDecimal getWeight() {
		return get("weight");
	}
	
	/**
	 * 单价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 总价
	 */
	public void setSum(java.math.BigDecimal sum) {
		set("sum", sum);
	}
	
	/**
	 * 总价
	 */
	public java.math.BigDecimal getSum() {
		return get("sum");
	}
	
	/**
	 * 标志位
	 */
	public void setFlag(java.math.BigDecimal flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志位
	 */
	public java.math.BigDecimal getFlag() {
		return get("flag");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.math.BigDecimal status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.math.BigDecimal getStatus() {
		return get("status");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 是否删除(0-未删除,1-已删除)
	 */
	public void setIsdelete(java.math.BigDecimal isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 是否删除(0-未删除,1-已删除)
	 */
	public java.math.BigDecimal getIsdelete() {
		return get("isdelete");
	}
	
	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 是否自制(0-否,1-是)
	 */
	public void setIsmade(java.lang.Integer ismade) {
		set("ismade", ismade);
	}
	
	/**
	 * 是否自制(0-否,1-是)
	 */
	public java.lang.Integer getIsmade() {
		return getInt("ismade");
	}
	
}

