package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClGb<M extends BaseClGb<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库单号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库单号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分分析-C
	 */
	public void setChemC(java.math.BigDecimal chemC) {
		set("chemC", chemC);
	}
	
	/**
	 * 化学成分分析-C
	 */
	public java.math.BigDecimal getChemC() {
		return get("chemC");
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分分析-P
	 */
	public void setChemP(java.math.BigDecimal chemP) {
		set("chemP", chemP);
	}
	
	/**
	 * 化学成分分析-P
	 */
	public java.math.BigDecimal getChemP() {
		return get("chemP");
	}
	
	/**
	 * 化学成分分析-S
	 */
	public void setChemS(java.math.BigDecimal chemS) {
		set("chemS", chemS);
	}
	
	/**
	 * 化学成分分析-S
	 */
	public java.math.BigDecimal getChemS() {
		return get("chemS");
	}
	
	/**
	 * 化学成分分析-Nb
	 */
	public void setChemNb(java.math.BigDecimal chemNb) {
		set("chemNb", chemNb);
	}
	
	/**
	 * 化学成分分析-Nb
	 */
	public java.math.BigDecimal getChemNb() {
		return get("chemNb");
	}
	
	/**
	 * 化学成分分析-V
	 */
	public void setChemV(java.math.BigDecimal chemV) {
		set("chemV", chemV);
	}
	
	/**
	 * 化学成分分析-V
	 */
	public java.math.BigDecimal getChemV() {
		return get("chemV");
	}
	
	/**
	 * 化学成分分析-Ti
	 */
	public void setChemTi(java.math.BigDecimal chemTi) {
		set("chemTi", chemTi);
	}
	
	/**
	 * 化学成分分析-Ti
	 */
	public java.math.BigDecimal getChemTi() {
		return get("chemTi");
	}
	
	/**
	 * 化学成分分析-Cu
	 */
	public void setChemCu(java.math.BigDecimal chemCu) {
		set("chemCu", chemCu);
	}
	
	/**
	 * 化学成分分析-Cu
	 */
	public java.math.BigDecimal getChemCu() {
		return get("chemCu");
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public void setChemCr(java.math.BigDecimal chemCr) {
		set("chemCr", chemCr);
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public java.math.BigDecimal getChemCr() {
		return get("chemCr");
	}
	
	/**
	 * 化学成分分析-Ni
	 */
	public void setChemNi(java.math.BigDecimal chemNi) {
		set("chemNi", chemNi);
	}
	
	/**
	 * 化学成分分析-Ni
	 */
	public java.math.BigDecimal getChemNi() {
		return get("chemNi");
	}
	
	/**
	 * 化学成分分析-Mo
	 */
	public void setChemMo(java.math.BigDecimal chemMo) {
		set("chemMo", chemMo);
	}
	
	/**
	 * 化学成分分析-Mo
	 */
	public java.math.BigDecimal getChemMo() {
		return get("chemMo");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeavefactoryDate(java.util.Date leavefactoryDate) {
		set("leavefactoryDate", leavefactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeavefactoryDate() {
		return getDate("leavefactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasno(java.lang.String basno) {
		set("basno", basno);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasno() {
		return getStr("basno");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	public void setQuantity(java.lang.String quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.String getQuantity() {
		return getStr("quantity");
	}
	
	/**
	 * 总抽检数量
	 */
	public void setSampleQuantity(java.lang.String sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 总抽检数量
	 */
	public java.lang.String getSampleQuantity() {
		return getStr("sampleQuantity");
	}
	
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 审核人
	 */
	public void setAuditor(java.lang.String auditor) {
		set("auditor", auditor);
	}
	
	/**
	 * 审核人
	 */
	public java.lang.String getAuditor() {
		return getStr("auditor");
	}
	
	/**
	 * 检验人
	 */
	public void setChecker(java.lang.String checker) {
		set("checker", checker);
	}
	
	/**
	 * 检验人
	 */
	public java.lang.String getChecker() {
		return getStr("checker");
	}
	
	/**
	 * 抗拉强度
	 */
	public void setMechtensileStrength(java.math.BigDecimal mechtensileStrength) {
		set("mechtensileStrength", mechtensileStrength);
	}
	
	/**
	 * 抗拉强度
	 */
	public java.math.BigDecimal getMechtensileStrength() {
		return get("mechtensileStrength");
	}
	
	/**
	 * 屈服强度
	 */
	public void setMechyieldStrength(java.math.BigDecimal mechyieldStrength) {
		set("mechyieldStrength", mechyieldStrength);
	}
	
	/**
	 * 屈服强度
	 */
	public java.math.BigDecimal getMechyieldStrength() {
		return get("mechyieldStrength");
	}
	
	/**
	 * 断后伸长率
	 */
	public void setMechelongation(java.math.BigDecimal mechelongation) {
		set("mechelongation", mechelongation);
	}
	
	/**
	 * 断后伸长率
	 */
	public java.math.BigDecimal getMechelongation() {
		return get("mechelongation");
	}
	
	/**
	 * 弯曲性能
	 */
	public void setBending(java.lang.String bending) {
		set("bending", bending);
	}
	
	/**
	 * 弯曲性能
	 */
	public java.lang.String getBending() {
		return getStr("bending");
	}
	
	/**
	 * 冲击实验
	 */
	public void setImpactexp(java.lang.String impactexp) {
		set("impactexp", impactexp);
	}
	
	/**
	 * 冲击实验
	 */
	public java.lang.String getImpactexp() {
		return getStr("impactexp");
	}
	
	/**
	 * 尺寸(厚宽长mm)
	 */
	public void setSize(java.lang.String size) {
		set("size", size);
	}
	
	/**
	 * 尺寸(厚宽长mm)
	 */
	public java.lang.String getSize() {
		return getStr("size");
	}
	
	/**
	 * 重量
	 */
	public void setWeight(java.lang.String weight) {
		set("weight", weight);
	}
	
	/**
	 * 重量
	 */
	public java.lang.String getWeight() {
		return getStr("weight");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setCompInspQty(java.math.BigDecimal compInspQty) {
		set("compInspQty", compInspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getCompInspQty() {
		return get("compInspQty");
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public void setMeInspQty(java.math.BigDecimal meInspQty) {
		set("meInspQty", meInspQty);
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public java.math.BigDecimal getMeInspQty() {
		return get("meInspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public void setMechtensileStrengthRequired(java.math.BigDecimal mechtensileStrengthRequired) {
		set("mechtensileStrengthRequired", mechtensileStrengthRequired);
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public java.math.BigDecimal getMechtensileStrengthRequired() {
		return get("mechtensileStrengthRequired");
	}
	
	/**
	 * 屈服强度要求值
	 */
	public void setMechyieldStrengthRequired(java.math.BigDecimal mechyieldStrengthRequired) {
		set("mechyieldStrengthRequired", mechyieldStrengthRequired);
	}
	
	/**
	 * 屈服强度要求值
	 */
	public java.math.BigDecimal getMechyieldStrengthRequired() {
		return get("mechyieldStrengthRequired");
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public void setChemCRequired(java.math.BigDecimal chemCRequired) {
		set("chemCRequired", chemCRequired);
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public java.math.BigDecimal getChemCRequired() {
		return get("chemCRequired");
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public void setChemMnRequired(java.math.BigDecimal chemMnRequired) {
		set("chemMnRequired", chemMnRequired);
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public java.math.BigDecimal getChemMnRequired() {
		return get("chemMnRequired");
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public void setChemSiRequired(java.math.BigDecimal chemSiRequired) {
		set("chemSiRequired", chemSiRequired);
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public java.math.BigDecimal getChemSiRequired() {
		return get("chemSiRequired");
	}
	
	/**
	 * 化学成分要求值-P
	 */
	public void setChemPRequired(java.math.BigDecimal chemPRequired) {
		set("chemPRequired", chemPRequired);
	}
	
	/**
	 * 化学成分要求值-P
	 */
	public java.math.BigDecimal getChemPRequired() {
		return get("chemPRequired");
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public void setChemSRequired(java.math.BigDecimal chemSRequired) {
		set("chemSRequired", chemSRequired);
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public java.math.BigDecimal getChemSRequired() {
		return get("chemSRequired");
	}
	
	/**
	 * 化学成分要求值-Nb
	 */
	public void setChemNbRequired(java.math.BigDecimal chemNbRequired) {
		set("chemNbRequired", chemNbRequired);
	}
	
	/**
	 * 化学成分要求值-Nb
	 */
	public java.math.BigDecimal getChemNbRequired() {
		return get("chemNbRequired");
	}
	
	/**
	 * 化学成分要求值-V
	 */
	public void setChemVRequired(java.math.BigDecimal chemVRequired) {
		set("chemVRequired", chemVRequired);
	}
	
	/**
	 * 化学成分要求值-V
	 */
	public java.math.BigDecimal getChemVRequired() {
		return get("chemVRequired");
	}
	
	/**
	 * 化学成分要求值-Ti
	 */
	public void setChemTiRequired(java.math.BigDecimal chemTiRequired) {
		set("chemTiRequired", chemTiRequired);
	}
	
	/**
	 * 化学成分要求值-Ti
	 */
	public java.math.BigDecimal getChemTiRequired() {
		return get("chemTiRequired");
	}
	
	/**
	 * 化学成分要求值-Cu
	 */
	public void setChemCuRequired(java.math.BigDecimal chemCuRequired) {
		set("chemCuRequired", chemCuRequired);
	}
	
	/**
	 * 化学成分要求值-Cu
	 */
	public java.math.BigDecimal getChemCuRequired() {
		return get("chemCuRequired");
	}
	
	/**
	 * 化学成分要求值-Cr
	 */
	public void setChemCrRequired(java.math.BigDecimal chemCrRequired) {
		set("chemCrRequired", chemCrRequired);
	}
	
	/**
	 * 化学成分要求值-Cr
	 */
	public java.math.BigDecimal getChemCrRequired() {
		return get("chemCrRequired");
	}
	
	/**
	 * 化学成分要求值-Ni
	 */
	public void setChemNiRequired(java.math.BigDecimal chemNiRequired) {
		set("chemNiRequired", chemNiRequired);
	}
	
	/**
	 * 化学成分要求值-Ni
	 */
	public java.math.BigDecimal getChemNiRequired() {
		return get("chemNiRequired");
	}
	
	/**
	 * 化学成分要求值-Mo
	 */
	public void setChemMoRequired(java.math.BigDecimal chemMoRequired) {
		set("chemMoRequired", chemMoRequired);
	}
	
	/**
	 * 化学成分要求值-Mo
	 */
	public java.math.BigDecimal getChemMoRequired() {
		return get("chemMoRequired");
	}
	
	/**
	 * 断后伸长率要求值
	 */
	public void setMechelongationRequired(java.math.BigDecimal mechelongationRequired) {
		set("mechelongationRequired", mechelongationRequired);
	}
	
	/**
	 * 断后伸长率要求值
	 */
	public java.math.BigDecimal getMechelongationRequired() {
		return get("mechelongationRequired");
	}
	
}

