package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysuser<M extends BaseSysuser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 用户名
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * 用户名
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}
	
	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * 密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}
	
	/**
	 * 部门编号关联basdepartment表的id字段
	 */
	public void setDepartmentid(java.lang.Integer departmentid) {
		set("departmentid", departmentid);
	}
	
	/**
	 * 部门编号关联basdepartment表的id字段
	 */
	public java.lang.Integer getDepartmentid() {
		return getInt("departmentid");
	}
	
	/**
	 * 状态0表示正常，-1表示删除
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态0表示正常，-1表示删除
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 预留
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 预留
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 相关备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 相关备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setRule(java.lang.String rule) {
		set("rule", rule);
	}
	
	public java.lang.String getRule() {
		return getStr("rule");
	}
	
	/**
	 * 未知
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 未知
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 账户所对应人的姓名
	 */
	public void setDescr(java.lang.String descr) {
		set("descr", descr);
	}
	
	/**
	 * 账户所对应人的姓名
	 */
	public java.lang.String getDescr() {
		return getStr("descr");
	}
	
	/**
	 * 手机号
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}
	
	/**
	 * 应该是岗位名称
	 */
	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	/**
	 * 应该是岗位名称
	 */
	public java.lang.String getCategory() {
		return getStr("category");
	}
	
	/**
	 * 未知
	 */
	public void setFax(java.lang.String fax) {
		set("fax", fax);
	}
	
	/**
	 * 未知
	 */
	public java.lang.String getFax() {
		return getStr("fax");
	}
	
	public void setAvatar(java.lang.String avatar) {
		set("avatar", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("avatar");
	}
	
}

