package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasno<M extends BaseBasno<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 刘国奇，出厂试验数据
	 */
	public void setBasname(java.lang.String basname) {
		set("basname", basname);
	}
	
	/**
	 * 刘国奇，出厂试验数据
	 */
	public java.lang.String getBasname() {
		return getStr("basname");
	}
	
	public void setBasnum(java.lang.Integer basnum) {
		set("basnum", basnum);
	}
	
	public java.lang.Integer getBasnum() {
		return getInt("basnum");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setCurrentterm(java.lang.String currentterm) {
		set("currentterm", currentterm);
	}
	
	public java.lang.String getCurrentterm() {
		return getStr("currentterm");
	}
	
}

