package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePldingdanitem<M extends BasePldingdanitem<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 生产订单号，关联plshengchandingdan表
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 生产订单号，关联plshengchandingdan表
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 产品（物料）名称
	 */
	public void setItemname(java.lang.String itemname) {
		set("itemname", itemname);
	}
	
	/**
	 * 产品（物料）名称
	 */
	public java.lang.String getItemname() {
		return getStr("itemname");
	}
	
	/**
	 * 合同物料ID，关联Bascontractitem表
	 */
	public void setConitemId(java.lang.Long conitemId) {
		set("conitemId", conitemId);
	}
	
	/**
	 * 合同物料ID，关联Bascontractitem表
	 */
	public java.lang.Long getConitemId() {
		return getLong("conitemId");
	}
	
	/**
	 * 数量
	 */
	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}
	
	/**
	 * 数量
	 */
	public java.lang.String getAmount() {
		return getStr("amount");
	}
	
	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 规格型号
	 */
	public void setProductModel(java.lang.String productModel) {
		set("productModel", productModel);
	}
	
	/**
	 * 规格型号
	 */
	public java.lang.String getProductModel() {
		return getStr("productModel");
	}
	
	/**
	 * 对于该物料的生产计划备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 对于该物料的生产计划备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 生产车间
	 */
	public void setWorkshopName(java.lang.String workshopName) {
		set("workshopName", workshopName);
	}
	
	/**
	 * 生产车间
	 */
	public java.lang.String getWorkshopName() {
		return getStr("workshopName");
	}
	
}

