package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlMatInoutDoc<M extends BasePlMatInoutDoc<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID（通用）
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID（通用）
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 单据编号（通用）
	 */
	public void setDocNo(java.lang.String docNo) {
		set("docNo", docNo);
	}
	
	/**
	 * 单据编号（通用）
	 */
	public java.lang.String getDocNo() {
		return getStr("docNo");
	}
	
	/**
	 * 出入库类型（1=入库，2=出库）（通用）
	 */
	public void setInOutType(java.math.BigDecimal inOutType) {
		set("inOutType", inOutType);
	}
	
	/**
	 * 出入库类型（1=入库，2=出库）（通用）
	 */
	public java.math.BigDecimal getInOutType() {
		return get("inOutType");
	}
	
	/**
	 * 单据日期（通用）
	 */
	public void setTransactionDate(java.util.Date transactionDate) {
		set("transactionDate", transactionDate);
	}
	
	/**
	 * 单据日期（通用）
	 */
	public java.util.Date getTransactionDate() {
		return getDate("transactionDate");
	}
	
	/**
	 * 发货单位（入库用）
	 */
	public void setDeliveryOrg(java.lang.String deliveryOrg) {
		set("deliveryOrg", deliveryOrg);
	}
	
	/**
	 * 发货单位（入库用）
	 */
	public java.lang.String getDeliveryOrg() {
		return getStr("deliveryOrg");
	}
	
	/**
	 * 收货单位（出库用）
	 */
	public void setReceiveOrg(java.lang.String receiveOrg) {
		set("receiveOrg", receiveOrg);
	}
	
	/**
	 * 收货单位（出库用）
	 */
	public java.lang.String getReceiveOrg() {
		return getStr("receiveOrg");
	}
	
	/**
	 * 经手人（通用）
	 */
	public void setHandler(java.lang.String handler) {
		set("handler", handler);
	}
	
	/**
	 * 经手人（通用）
	 */
	public java.lang.String getHandler() {
		return getStr("handler");
	}
	
	/**
	 * 库管员（通用）
	 */
	public void setStorekeeper(java.lang.String storekeeper) {
		set("storekeeper", storekeeper);
	}
	
	/**
	 * 库管员（通用）
	 */
	public java.lang.String getStorekeeper() {
		return getStr("storekeeper");
	}
	
	/**
	 * 负责人（通用）
	 */
	public void setManager(java.lang.String manager) {
		set("manager", manager);
	}
	
	/**
	 * 负责人（通用）
	 */
	public java.lang.String getManager() {
		return getStr("manager");
	}
	
	/**
	 * 单据状态（通用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 单据状态（通用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 申请人（出库用）
	 */
	public void setRequester(java.lang.String requester) {
		set("requester", requester);
	}
	
	/**
	 * 申请人（出库用）
	 */
	public java.lang.String getRequester() {
		return getStr("requester");
	}
	
	/**
	 * 是否有发票（通用）
	 */
	public void setHasInvoice(java.lang.Integer hasInvoice) {
		set("hasInvoice", hasInvoice);
	}
	
	/**
	 * 是否有发票（通用）
	 */
	public java.lang.Integer getHasInvoice() {
		return getInt("hasInvoice");
	}
	
	/**
	 * 业务期间（通用）
	 */
	public void setTerm(java.math.BigDecimal term) {
		set("term", term);
	}
	
	/**
	 * 业务期间（通用）
	 */
	public java.math.BigDecimal getTerm() {
		return get("term");
	}
	
	/**
	 * 单据备注（通用）
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 单据备注（通用）
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 系统录入时间（通用）
	 */
	public void setOperateTime(java.util.Date operateTime) {
		set("operateTime", operateTime);
	}
	
	/**
	 * 系统录入时间（通用）
	 */
	public java.util.Date getOperateTime() {
		return getDate("operateTime");
	}
	
	/**
	 * 逻辑删除标识，（0=未删，1=已删）（通用）
	 */
	public void setIsDeleted(java.lang.Integer isDeleted) {
		set("isDeleted", isDeleted);
	}
	
	/**
	 * 逻辑删除标识，（0=未删，1=已删）（通用）
	 */
	public java.lang.Integer getIsDeleted() {
		return getInt("isDeleted");
	}
	
}

