package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlInspOrder<M extends BasePlInspOrder<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 检验单号，如 INS20251030001
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 检验单号，如 INS20251030001
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}
	
	/**
	 * 检验原材料ID--应该是从采购订单带过来，但也可以单独选择
	 */
	public void setItemId(java.lang.Long itemId) {
		set("itemId", itemId);
	}
	
	/**
	 * 检验原材料ID--应该是从采购订单带过来，但也可以单独选择
	 */
	public java.lang.Long getItemId() {
		return getLong("itemId");
	}
	
	/**
	 * 关联采购项ID
	 */
	public void setPurchaseId(java.lang.Long purchaseId) {
		set("purchaseId", purchaseId);
	}
	
	/**
	 * 关联采购项ID
	 */
	public java.lang.Long getPurchaseId() {
		return getLong("purchaseId");
	}
	
	/**
	 * 检验标准号
	 */
	public void setInspStandard(java.lang.String inspStandard) {
		set("inspStandard", inspStandard);
	}
	
	/**
	 * 检验标准号
	 */
	public java.lang.String getInspStandard() {
		return getStr("inspStandard");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNumber(java.lang.String batchNumber) {
		set("batchNumber", batchNumber);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNumber() {
		return getStr("batchNumber");
	}
	
	/**
	 * 检验数量
	 */
	public void setInspQuantity(java.math.BigDecimal inspQuantity) {
		set("inspQuantity", inspQuantity);
	}
	
	/**
	 * 检验数量
	 */
	public java.math.BigDecimal getInspQuantity() {
		return get("inspQuantity");
	}
	
	/**
	 * 实际到货数量
	 */
	public void setActualQuantity(java.math.BigDecimal actualQuantity) {
		set("actualQuantity", actualQuantity);
	}
	
	/**
	 * 实际到货数量
	 */
	public java.math.BigDecimal getActualQuantity() {
		return get("actualQuantity");
	}
	
	/**
	 * 实际到货重量
	 */
	public void setActualWeight(java.math.BigDecimal actualWeight) {
		set("actualWeight", actualWeight);
	}
	
	/**
	 * 实际到货重量
	 */
	public java.math.BigDecimal getActualWeight() {
		return get("actualWeight");
	}
	
	/**
	 * 实际到货材质
	 */
	public void setActualMaterial(java.lang.String actualMaterial) {
		set("actualMaterial", actualMaterial);
	}
	
	/**
	 * 实际到货材质
	 */
	public java.lang.String getActualMaterial() {
		return getStr("actualMaterial");
	}
	
	/**
	 * 实际到货型号
	 */
	public void setActualSpec(java.lang.String actualSpec) {
		set("actualSpec", actualSpec);
	}
	
	/**
	 * 实际到货型号
	 */
	public java.lang.String getActualSpec() {
		return getStr("actualSpec");
	}
	
	/**
	 * 检验时间前端输入
	 */
	public void setInspectTime(java.util.Date inspectTime) {
		set("inspectTime", inspectTime);
	}
	
	/**
	 * 检验时间前端输入
	 */
	public java.util.Date getInspectTime() {
		return getDate("inspectTime");
	}
	
	/**
	 * 报检人
	 */
	public void setReporter(java.lang.String reporter) {
		set("reporter", reporter);
	}
	
	/**
	 * 报检人
	 */
	public java.lang.String getReporter() {
		return getStr("reporter");
	}
	
	/**
	 * 报检审核人
	 */
	public void setReportReviewer(java.lang.String reportReviewer) {
		set("reportReviewer", reportReviewer);
	}
	
	/**
	 * 报检审核人
	 */
	public java.lang.String getReportReviewer() {
		return getStr("reportReviewer");
	}
	
	/**
	 * 检验人
	 */
	public void setInspector(java.lang.String inspector) {
		set("inspector", inspector);
	}
	
	/**
	 * 检验人
	 */
	public java.lang.String getInspector() {
		return getStr("inspector");
	}
	
	/**
	 * 检验审核人
	 */
	public void setInspectReviewer(java.lang.String inspectReviewer) {
		set("inspectReviewer", inspectReviewer);
	}
	
	/**
	 * 检验审核人
	 */
	public java.lang.String getInspectReviewer() {
		return getStr("inspectReviewer");
	}
	
	/**
	 * // 主检验单状态流转（status）
//0 报检单草稿->10 报检待审核 → 11 通过 → 20 检验中 → 21 检验完成 → 22 检验合格 → 30 入库中 → 31 已入库
// 拒绝：12 报检拒绝 | 23 检验不合格 | 32 入库拒绝（均可重提）
// 99 已作废
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * // 主检验单状态流转（status）
//0 报检单草稿->10 报检待审核 → 11 通过 → 20 检验中 → 21 检验完成 → 22 检验合格 → 30 入库中 → 31 已入库
// 拒绝：12 报检拒绝 | 23 检验不合格 | 32 入库拒绝（均可重提）
// 99 已作废
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 质量证明书url
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书url
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 整单通用备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 整单通用备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 检验阶段备注（如检验异常、数据说明等）
	 */
	public void setInspRemark(java.lang.String inspRemark) {
		set("inspRemark", inspRemark);
	}
	
	/**
	 * 检验阶段备注（如检验异常、数据说明等）
	 */
	public java.lang.String getInspRemark() {
		return getStr("inspRemark");
	}
	
	/**
	 * 库存（入库）阶段备注（如拒绝入库原因）
	 */
	public void setStockRemark(java.lang.String stockRemark) {
		set("stockRemark", stockRemark);
	}
	
	/**
	 * 库存（入库）阶段备注（如拒绝入库原因）
	 */
	public java.lang.String getStockRemark() {
		return getStr("stockRemark");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
	/**
	 * 入库时间，后端插入时生成
	 */
	public void setInStockTime(java.util.Date inStockTime) {
		set("inStockTime", inStockTime);
	}
	
	/**
	 * 入库时间，后端插入时生成
	 */
	public java.util.Date getInStockTime() {
		return getDate("inStockTime");
	}
	
	/**
	 * 检验审核完成时间
	 */
	public void setInspectFinishTime(java.util.Date inspectFinishTime) {
		set("inspectFinishTime", inspectFinishTime);
	}
	
	/**
	 * 检验审核完成时间
	 */
	public java.util.Date getInspectFinishTime() {
		return getDate("inspectFinishTime");
	}
	
	/**
	 * 入库审核人
	 */
	public void setStorageReviewer(java.lang.String storageReviewer) {
		set("storageReviewer", storageReviewer);
	}
	
	/**
	 * 入库审核人
	 */
	public java.lang.String getStorageReviewer() {
		return getStr("storageReviewer");
	}
	
	/**
	 * 到货时间
	 */
	public void setDeliveryTime(java.util.Date deliveryTime) {
		set("deliveryTime", deliveryTime);
	}
	
	/**
	 * 到货时间
	 */
	public java.util.Date getDeliveryTime() {
		return getDate("deliveryTime");
	}
	
	/**
	 * 单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 报检申请审核时间
	 */
	public void setReportReviewStartTime(java.util.Date reportReviewStartTime) {
		set("reportReviewStartTime", reportReviewStartTime);
	}
	
	/**
	 * 报检申请审核时间
	 */
	public java.util.Date getReportReviewStartTime() {
		return getDate("reportReviewStartTime");
	}
	
	/**
	 * 报检审核完成时间
	 */
	public void setReportReviewFinishTime(java.util.Date reportReviewFinishTime) {
		set("reportReviewFinishTime", reportReviewFinishTime);
	}
	
	/**
	 * 报检审核完成时间
	 */
	public java.util.Date getReportReviewFinishTime() {
		return getDate("reportReviewFinishTime");
	}
	
	/**
	 * 牌号
	 */
	public void setMatNo(java.lang.String matNo) {
		set("matNo", matNo);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatNo() {
		return getStr("matNo");
	}
	
}

