package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClTb<M extends BaseClTb<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 化学成分实测值-Cu+AI
	 */
	public void setChemCuAl(java.math.BigDecimal chemCuAl) {
		set("chemCuAl", chemCuAl);
	}
	
	/**
	 * 化学成分实测值-Cu+AI
	 */
	public java.math.BigDecimal getChemCuAl() {
		return get("chemCuAl");
	}
	
	/**
	 * 化学成分实测值-Sb
	 */
	public void setChemSb(java.math.BigDecimal chemSb) {
		set("chemSb", chemSb);
	}
	
	/**
	 * 化学成分实测值-Sb
	 */
	public java.math.BigDecimal getChemSb() {
		return get("chemSb");
	}
	
	/**
	 * 化学成分实测值-As
	 */
	public void setChemAs(java.math.BigDecimal chemAs) {
		set("chemAs", chemAs);
	}
	
	/**
	 * 化学成分实测值-As
	 */
	public java.math.BigDecimal getChemAs() {
		return get("chemAs");
	}
	
	/**
	 * 化学成分实测值-Fe
	 */
	public void setChemFe(java.math.BigDecimal chemFe) {
		set("chemFe", chemFe);
	}
	
	/**
	 * 化学成分实测值-Fe
	 */
	public java.math.BigDecimal getChemFe() {
		return get("chemFe");
	}
	
	/**
	 * 化学成分实测值-S
	 */
	public void setChemS(java.math.BigDecimal chemS) {
		set("chemS", chemS);
	}
	
	/**
	 * 化学成分实测值-S
	 */
	public java.math.BigDecimal getChemS() {
		return get("chemS");
	}
	
	/**
	 * 化学成分要求值-Cu+Al
	 */
	public void setChemCuAlRequired(java.lang.String chemCuAlRequired) {
		set("chemCuAlRequired", chemCuAlRequired);
	}
	
	/**
	 * 化学成分要求值-Cu+Al
	 */
	public java.lang.String getChemCuAlRequired() {
		return getStr("chemCuAlRequired");
	}
	
	/**
	 * 化学成分要求值-Sb
	 */
	public void setChemSbRequired(java.lang.String chemSbRequired) {
		set("chemSbRequired", chemSbRequired);
	}
	
	/**
	 * 化学成分要求值-Sb
	 */
	public java.lang.String getChemSbRequired() {
		return getStr("chemSbRequired");
	}
	
	/**
	 * 化学成分要求值-As
	 */
	public void setChemAsRequired(java.lang.String chemAsRequired) {
		set("chemAsRequired", chemAsRequired);
	}
	
	/**
	 * 化学成分要求值-As
	 */
	public java.lang.String getChemAsRequired() {
		return getStr("chemAsRequired");
	}
	
	/**
	 * 化学成分要求值-Fe
	 */
	public void setChemFeRequired(java.lang.String chemFeRequired) {
		set("chemFeRequired", chemFeRequired);
	}
	
	/**
	 * 化学成分要求值-Fe
	 */
	public java.lang.String getChemFeRequired() {
		return getStr("chemFeRequired");
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public void setChemSRequired(java.lang.String chemSRequired) {
		set("chemSRequired", chemSRequired);
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public java.lang.String getChemSRequired() {
		return getStr("chemSRequired");
	}
	
	/**
	 * 原材料出场检测日期
	 */
	public void setLeaveFactoryDate(java.util.Date leaveFactoryDate) {
		set("leaveFactoryDate", leaveFactoryDate);
	}
	
	/**
	 * 原材料出场检测日期
	 */
	public java.util.Date getLeaveFactoryDate() {
		return getDate("leaveFactoryDate");
	}
	
	/**
	 * 原材料入场检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入场检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 抗拉强度实测值
	 */
	public void setTenisileStrength(java.math.BigDecimal tenisileStrength) {
		set("tenisileStrength", tenisileStrength);
	}
	
	/**
	 * 抗拉强度实测值
	 */
	public java.math.BigDecimal getTenisileStrength() {
		return get("tenisileStrength");
	}
	
	/**
	 * 伸长率实测值
	 */
	public void setElongation(java.math.BigDecimal elongation) {
		set("elongation", elongation);
	}
	
	/**
	 * 伸长率实测值
	 */
	public java.math.BigDecimal getElongation() {
		return get("elongation");
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public void setTenisileStrengthRequired(java.lang.String tenisileStrengthRequired) {
		set("tenisileStrengthRequired", tenisileStrengthRequired);
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public java.lang.String getTenisileStrengthRequired() {
		return getStr("tenisileStrengthRequired");
	}
	
	/**
	 * 伸长率要求值
	 */
	public void setElongationReqiured(java.lang.String elongationReqiured) {
		set("elongationReqiured", elongationReqiured);
	}
	
	/**
	 * 伸长率要求值
	 */
	public java.lang.String getElongationReqiured() {
		return getStr("elongationReqiured");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录人，20检验单确认，待审核，30请检单验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录人，20检验单确认，待审核，30请检单验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号，录入请检单用
	 */
	public void setBasNo(java.lang.String basNo) {
		set("basNo", basNo);
	}
	
	/**
	 * 单据号，录入请检单用
	 */
	public java.lang.String getBasNo() {
		return getStr("basNo");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 总抽检数量
	 */
	public void setSampleQuantity(java.math.BigDecimal sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 总抽检数量
	 */
	public java.math.BigDecimal getSampleQuantity() {
		return get("sampleQuantity");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸是否合格
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸是否合格
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * :最终检验结论(合格/不台格/复检等)
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * :最终检验结论(合格/不台格/复检等)
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setComplnspQty(java.math.BigDecimal complnspQty) {
		set("complnspQty", complnspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getComplnspQty() {
		return get("complnspQty");
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public void setMechlnspQty(java.math.BigDecimal mechlnspQty) {
		set("mechlnspQty", mechlnspQty);
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public java.math.BigDecimal getMechlnspQty() {
		return get("mechlnspQty");
	}
	
	/**
	 * 批号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(byte[] requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public byte[] getRequestAuditor() {
		return get("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
}

