package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlInspResult<M extends BasePlInspResult<M>> extends Model<M> implements IBean {

	/**
	 * 主键，系统自动生成
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键，系统自动生成
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 所属检验单ID（逻辑外键，与pl_insp_order.id 关联）
	 */
	public void setInspOrderId(java.lang.Long inspOrderId) {
		set("inspOrderId", inspOrderId);
	}
	
	/**
	 * 所属检验单ID（逻辑外键，与pl_insp_order.id 关联）
	 */
	public java.lang.Long getInspOrderId() {
		return getLong("inspOrderId");
	}
	
	/**
	 * 检验项目ID（逻辑外键，与 pl_insp_item.id 关联）
	 */
	public void setInspItemId(java.lang.Long inspItemId) {
		set("inspItemId", inspItemId);
	}
	
	/**
	 * 检验项目ID（逻辑外键，与 pl_insp_item.id 关联）
	 */
	public java.lang.Long getInspItemId() {
		return getLong("inspItemId");
	}
	
	/**
	 * 实测值，字符串存储，支持数字、文本、枚举
	 */
	public void setActualValue(java.lang.String actualValue) {
		set("actualValue", actualValue);
	}
	
	/**
	 * 实测值，字符串存储，支持数字、文本、枚举
	 */
	public java.lang.String getActualValue() {
		return getStr("actualValue");
	}
	
	/**
	 * 第几次平行试验（1,2,3...），默认第1次
	 */
	public void setTestIndex(java.lang.Integer testIndex) {
		set("testIndex", testIndex);
	}
	
	/**
	 * 第几次平行试验（1,2,3...），默认第1次
	 */
	public java.lang.Integer getTestIndex() {
		return getInt("testIndex");
	}
	
	/**
	 * 是否合格：1=合格, 0=不合格, NULL=未判定
	 */
	public void setIsPass(java.lang.Short isPass) {
		set("isPass", isPass);
	}
	
	/**
	 * 是否合格：1=合格, 0=不合格, NULL=未判定
	 */
	public java.lang.Short getIsPass() {
		return getShort("isPass");
	}
	
	/**
	 * 单项备注，可记录异常、照片说明等
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 单项备注，可记录异常、照片说明等
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
}

