package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlMaterialRequestAllocation<M extends BasePlMaterialRequestAllocation<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 领料详情ID，关联 materialRequestDetail 表的 id
	 */
	public void setDetailId(java.lang.Long detailId) {
		set("detailId", detailId);
	}
	
	/**
	 * 领料详情ID，关联 materialRequestDetail 表的 id
	 */
	public java.lang.Long getDetailId() {
		return getLong("detailId");
	}
	
	/**
	 * 出库记录ID，关联出入库表（如 stockOutbound）中的出库类型记录
	 */
	public void setOutboundId(java.lang.Long outboundId) {
		set("outboundId", outboundId);
	}
	
	/**
	 * 出库记录ID，关联出入库表（如 stockOutbound）中的出库类型记录
	 */
	public java.lang.Long getOutboundId() {
		return getLong("outboundId");
	}
	
	/**
	 * 本次配货数量，记录该出库记录分配给该明细的具体数量
	 */
	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 本次配货数量，记录该出库记录分配给该明细的具体数量
	 */
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}
	
	/**
	 * 创建时间，记录配货操作发生的时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间，记录配货操作发生的时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
}

