package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasProcessRoute<M extends BaseBasProcessRoute<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 工序编码
	 */
	public void setProcessCode(java.lang.String processCode) {
		set("processCode", processCode);
	}
	
	/**
	 * 工序编码
	 */
	public java.lang.String getProcessCode() {
		return getStr("processCode");
	}
	
	/**
	 * 工序名称
	 */
	public void setProcessName(java.lang.String processName) {
		set("processName", processName);
	}
	
	/**
	 * 工序名称
	 */
	public java.lang.String getProcessName() {
		return getStr("processName");
	}
	
	/**
	 * 关联成品或者半成品id
	 */
	public void setItemId(java.lang.Long itemId) {
		set("itemId", itemId);
	}
	
	/**
	 * 关联成品或者半成品id
	 */
	public java.lang.Long getItemId() {
		return getLong("itemId");
	}
	
	/**
	 * 工序顺序
	 */
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	/**
	 * 工序顺序
	 */
	public java.lang.Integer getSort() {
		return getInt("sort");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 录入时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 标明是检验入库流程还是生产流程，1是生产，2是入库
	 */
	public void setProcessType(java.lang.Byte processType) {
		set("processType", processType);
	}
	
	/**
	 * 标明是检验入库流程还是生产流程，1是生产，2是入库
	 */
	public java.lang.Byte getProcessType() {
		return getByte("processType");
	}
	
}

