package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlshengchangongdan<M extends BasePlshengchangongdan<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商生产订单序号
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 供应商生产订单序号
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 生产工单编码
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 生产工单编码
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
	/**
	 * 品类编码
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 厂家物料编码
	 */
	public void setMaterialsCode(java.lang.String materialsCode) {
		set("materialsCode", materialsCode);
	}
	
	/**
	 * 厂家物料编码
	 */
	public java.lang.String getMaterialsCode() {
		return getStr("materialsCode");
	}
	
	/**
	 * 厂家物料描述
	 */
	public void setMaterialsDescription(java.lang.String materialsDescription) {
		set("materialsDescription", materialsDescription);
	}
	
	/**
	 * 厂家物料描述
	 */
	public java.lang.String getMaterialsDescription() {
		return getStr("materialsDescription");
	}
	
	/**
	 * 物料批次
	 */
	public void setMaterialsBatch(java.lang.String materialsBatch) {
		set("materialsBatch", materialsBatch);
	}
	
	/**
	 * 物料批次
	 */
	public java.lang.String getMaterialsBatch() {
		return getStr("materialsBatch");
	}
	
	/**
	 * 生产数量
	 */
	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}
	
	/**
	 * 生产数量
	 */
	public java.lang.String getAmount() {
		return getStr("amount");
	}
	
	/**
	 * 计量单位
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 计量单位
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 计划开始日期
	 */
	public void setPlanStartDate(java.util.Date planStartDate) {
		set("planStartDate", planStartDate);
	}
	
	/**
	 * 计划开始日期
	 */
	public java.util.Date getPlanStartDate() {
		return getDate("planStartDate");
	}
	
	/**
	 * 计划完成日期
	 */
	public void setPlanFinishDate(java.util.Date planFinishDate) {
		set("planFinishDate", planFinishDate);
	}
	
	/**
	 * 计划完成日期
	 */
	public java.util.Date getPlanFinishDate() {
		return getDate("planFinishDate");
	}
	
	/**
	 * 实际开始日期
	 */
	public void setActualStartDate(java.util.Date actualStartDate) {
		set("actualStartDate", actualStartDate);
	}
	
	/**
	 * 实际开始日期
	 */
	public java.util.Date getActualStartDate() {
		return getDate("actualStartDate");
	}
	
	/**
	 * 实际完成日期
	 */
	public void setActualFinishDate(java.util.Date actualFinishDate) {
		set("actualFinishDate", actualFinishDate);
	}
	
	/**
	 * 实际完成日期
	 */
	public java.util.Date getActualFinishDate() {
		return getDate("actualFinishDate");
	}
	
	/**
	 * 工单状态
	 */
	public void setWoStatus(java.lang.Integer woStatus) {
		set("woStatus", woStatus);
	}
	
	/**
	 * 工单状态
	 */
	public java.lang.Integer getWoStatus() {
		return getInt("woStatus");
	}
	
	/**
	 * 实物ID
	 */
	public void setEntityCode(java.lang.String entityCode) {
		set("entityCode", entityCode);
	}
	
	/**
	 * 实物ID
	 */
	public java.lang.String getEntityCode() {
		return getStr("entityCode");
	}
	
	/**
	 * 工艺路线编码
	 */
	public void setProcessRouteNo(java.lang.String processRouteNo) {
		set("processRouteNo", processRouteNo);
	}
	
	/**
	 * 工艺路线编码
	 */
	public java.lang.String getProcessRouteNo() {
		return getStr("processRouteNo");
	}
	
	/**
	 * 电压等级
	 */
	public void setVoltageLevel(java.lang.String voltageLevel) {
		set("voltageLevel", voltageLevel);
	}
	
	/**
	 * 电压等级
	 */
	public java.lang.String getVoltageLevel() {
		return getStr("voltageLevel");
	}
	
	/**
	 * 数据来源
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 数据拥有方
	 */
	public void setOwnerId(java.lang.String ownerId) {
		set("ownerId", ownerId);
	}
	
	/**
	 * 数据拥有方
	 */
	public java.lang.String getOwnerId() {
		return getStr("ownerId");
	}
	
	/**
	 * 数据可见方
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 数据可见方
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}
	
	/**
	 * 产品型号规格
	 */
	public void setModelSpec(java.lang.String modelSpec) {
		set("modelSpec", modelSpec);
	}
	
	/**
	 * 产品型号规格
	 */
	public java.lang.String getModelSpec() {
		return getStr("modelSpec");
	}
	
	/**
	 * 删除标记默认为0
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 删除标记默认为0
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 数据标识
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 数据标识
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 厂内合同号，关联bascontract的no
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 厂内合同号，关联bascontract的no
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间
	 */
	public void setWritetime(java.util.Date writetime) {
		set("writetime", writetime);
	}
	
	/**
	 * 录入时间
	 */
	public java.util.Date getWritetime() {
		return getDate("writetime");
	}
	
}

