package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlMatInoutItem<M extends BasePlMatInoutItem<M>> extends Model<M> implements IBean {

	/**
	 * 明细主键（通用）
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 明细主键（通用）
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 关联单据号（通用）
	 */
	public void setDocNo(java.lang.String docNo) {
		set("docNo", docNo);
	}
	
	/**
	 * 关联单据号（通用）
	 */
	public java.lang.String getDocNo() {
		return getStr("docNo");
	}
	
	/**
	 * 物料编号（通用）
	 */
	public void setMaterialCode(java.lang.String materialCode) {
		set("materialCode", materialCode);
	}
	
	/**
	 * 物料编号（通用）
	 */
	public java.lang.String getMaterialCode() {
		return getStr("materialCode");
	}
	
	/**
	 * 物料名称（通用）
	 */
	public void setMaterialName(java.lang.String materialName) {
		set("materialName", materialName);
	}
	
	/**
	 * 物料名称（通用）
	 */
	public java.lang.String getMaterialName() {
		return getStr("materialName");
	}
	
	/**
	 * 规格型号（通用）
	 */
	public void setMaterialSpec(java.lang.String materialSpec) {
		set("materialSpec", materialSpec);
	}
	
	/**
	 * 规格型号（通用）
	 */
	public java.lang.String getMaterialSpec() {
		return getStr("materialSpec");
	}
	
	/**
	 * 计量单位（通用）
	 */
	public void setMaterialUnit(java.lang.String materialUnit) {
		set("materialUnit", materialUnit);
	}
	
	/**
	 * 计量单位（通用）
	 */
	public java.lang.String getMaterialUnit() {
		return getStr("materialUnit");
	}
	
	/**
	 * 操作仓库（通用）
	 */
	public void setWarehouse(java.lang.String warehouse) {
		set("warehouse", warehouse);
	}
	
	/**
	 * 操作仓库（通用）
	 */
	public java.lang.String getWarehouse() {
		return getStr("warehouse");
	}
	
	/**
	 * 数量（入库正数，出库负数）（通用）
	 */
	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 数量（入库正数，出库负数）（通用）
	 */
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}
	
	/**
	 * 单重（通用）
	 */
	public void setUnitWeight(java.math.BigDecimal unitWeight) {
		set("unitWeight", unitWeight);
	}
	
	/**
	 * 单重（通用）
	 */
	public java.math.BigDecimal getUnitWeight() {
		return get("unitWeight");
	}
	
	/**
	 * 销售单价（出库用）
	 */
	public void setSalesPrice(java.math.BigDecimal salesPrice) {
		set("salesPrice", salesPrice);
	}
	
	/**
	 * 销售单价（出库用）
	 */
	public java.math.BigDecimal getSalesPrice() {
		return get("salesPrice");
	}
	
	/**
	 * 销售金额（出库用）
	 */
	public void setSalesTotalAmount(java.math.BigDecimal salesTotalAmount) {
		set("salesTotalAmount", salesTotalAmount);
	}
	
	/**
	 * 销售金额（出库用）
	 */
	public java.math.BigDecimal getSalesTotalAmount() {
		return get("salesTotalAmount");
	}
	
	/**
	 * 物料类别（通用）
	 */
	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	/**
	 * 物料类别（通用）
	 */
	public java.lang.String getCategory() {
		return getStr("category");
	}
	
	/**
	 * 关联合同编号（通用）
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 关联合同编号（通用）
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 关联合同名称（通用）
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 关联合同名称（通用）
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 检验部门（通用）
	 */
	public void setInspectorOrg(java.lang.String inspectorOrg) {
		set("inspectorOrg", inspectorOrg);
	}
	
	/**
	 * 检验部门（通用）
	 */
	public java.lang.String getInspectorOrg() {
		return getStr("inspectorOrg");
	}
	
	/**
	 * 采购部门（入库用）
	 */
	public void setBuyerOrg(java.lang.String buyerOrg) {
		set("buyerOrg", buyerOrg);
	}
	
	/**
	 * 采购部门（入库用）
	 */
	public java.lang.String getBuyerOrg() {
		return getStr("buyerOrg");
	}
	
	/**
	 * 盘点类型（通用）
	 */
	public void setInventoryCheckType(java.lang.Integer inventoryCheckType) {
		set("inventoryCheckType", inventoryCheckType);
	}
	
	/**
	 * 盘点类型（通用）
	 */
	public java.lang.Integer getInventoryCheckType() {
		return getInt("inventoryCheckType");
	}
	
	/**
	 * 申请数量（出库用）
	 */
	public void setRequestQuantity(java.math.BigDecimal requestQuantity) {
		set("requestQuantity", requestQuantity);
	}
	
	/**
	 * 申请数量（出库用）
	 */
	public java.math.BigDecimal getRequestQuantity() {
		return get("requestQuantity");
	}
	
	/**
	 * 批次号（通用）
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 批次号（通用）
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 明细备注（通用）
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 明细备注（通用）
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 明细状态（通用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 明细状态（通用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 系统录入时间（通用）
	 */
	public void setOperateTime(java.util.Date operateTime) {
		set("operateTime", operateTime);
	}
	
	/**
	 * 系统录入时间（通用）
	 */
	public java.util.Date getOperateTime() {
		return getDate("operateTime");
	}
	
	/**
	 * 总重（通用）
	 */
	public void setTotalWeight(java.math.BigDecimal totalWeight) {
		set("totalWeight", totalWeight);
	}
	
	/**
	 * 总重（通用）
	 */
	public java.math.BigDecimal getTotalWeight() {
		return get("totalWeight");
	}
	
}

