package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlInspWorkOrder<M extends BasePlInspWorkOrder<M>> extends Model<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 产成品检验单号
	 */
	public void setOrderNo(java.lang.String orderNo) {
		set("orderNo", orderNo);
	}
	
	/**
	 * 产成品检验单号
	 */
	public java.lang.String getOrderNo() {
		return getStr("orderNo");
	}
	
	/**
	 * 产成品ID--关联basitem表
	 */
	public void setItemId(java.lang.Long itemId) {
		set("itemId", itemId);
	}
	
	/**
	 * 产成品ID--关联basitem表
	 */
	public java.lang.Long getItemId() {
		return getLong("itemId");
	}
	
	/**
	 * 产成品检验数量
	 */
	public void setInspQuantity(java.math.BigDecimal inspQuantity) {
		set("inspQuantity", inspQuantity);
	}
	
	/**
	 * 产成品检验数量
	 */
	public java.math.BigDecimal getInspQuantity() {
		return get("inspQuantity");
	}
	
	/**
	 * 报检人（产成品报检发起人员）
	 */
	public void setReporter(java.lang.String reporter) {
		set("reporter", reporter);
	}
	
	/**
	 * 报检人（产成品报检发起人员）
	 */
	public java.lang.String getReporter() {
		return getStr("reporter");
	}
	
	/**
	 * 检验人（产成品实际检验数据录入人员）
	 */
	public void setInspector(java.lang.String inspector) {
		set("inspector", inspector);
	}
	
	/**
	 * 检验人（产成品实际检验数据录入人员）
	 */
	public java.lang.String getInspector() {
		return getStr("inspector");
	}
	
	/**
	 * 检验审核人（产成品检验结果审核人员）
	 */
	public void setInspectReviewer(java.lang.String inspectReviewer) {
		set("inspectReviewer", inspectReviewer);
	}
	
	/**
	 * 检验审核人（产成品检验结果审核人员）
	 */
	public java.lang.String getInspectReviewer() {
		return getStr("inspectReviewer");
	}
	
	/**
	 * 入库人（产成品入库操作人员）
	 */
	public void setStockInPerson(java.lang.String stockInPerson) {
		set("stockInPerson", stockInPerson);
	}
	
	/**
	 * 入库人（产成品入库操作人员）
	 */
	public java.lang.String getStockInPerson() {
		return getStr("stockInPerson");
	}
	
	/**
	 * 入库审核人（产成品入库审核人员）
	 */
	public void setStorageReviewer(java.lang.String storageReviewer) {
		set("storageReviewer", storageReviewer);
	}
	
	/**
	 * 入库审核人（产成品入库审核人员）
	 */
	public java.lang.String getStorageReviewer() {
		return getStr("storageReviewer");
	}
	
	/**
	 * 发起报检的时间（报检申请提交时间）
	 */
	public void setReportApplyTime(java.util.Date reportApplyTime) {
		set("reportApplyTime", reportApplyTime);
	}
	
	/**
	 * 发起报检的时间（报检申请提交时间）
	 */
	public java.util.Date getReportApplyTime() {
		return getDate("reportApplyTime");
	}
	
	/**
	 * 检验完成时间（产成品检验流程完成时间）
	 */
	public void setInspectFinishTime(java.util.Date inspectFinishTime) {
		set("inspectFinishTime", inspectFinishTime);
	}
	
	/**
	 * 检验完成时间（产成品检验流程完成时间）
	 */
	public java.util.Date getInspectFinishTime() {
		return getDate("inspectFinishTime");
	}
	
	/**
	 * 入库完成时间（产成品入库流程完成时间）
	 */
	public void setInStockFinishTime(java.util.Date inStockFinishTime) {
		set("inStockFinishTime", inStockFinishTime);
	}
	
	/**
	 * 入库完成时间（产成品入库流程完成时间）
	 */
	public java.util.Date getInStockFinishTime() {
		return getDate("inStockFinishTime");
	}
	
	/**
	 * // 产成品检验单状态流转（status）
//0 报检单草稿->10 报检待审核 → 11 报检通过 → 20 检验中 → 21 检验完成 → 22 检验合格 → 30 入库中 → 31 已入库
// 拒绝：12 报检拒绝 | 23 检验不合格 | 32 入库拒绝（均可重提）
// 99 已作废
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * // 产成品检验单状态流转（status）
//0 报检单草稿->10 报检待审核 → 11 报检通过 → 20 检验中 → 21 检验完成 → 22 检验合格 → 30 入库中 → 31 已入库
// 拒绝：12 报检拒绝 | 23 检验不合格 | 32 入库拒绝（均可重提）
// 99 已作废
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 整单通用备注（产成品检验单通用说明）
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 整单通用备注（产成品检验单通用说明）
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 检验阶段备注（如产成品检验异常、数据说明等）
	 */
	public void setInspRemark(java.lang.String inspRemark) {
		set("inspRemark", inspRemark);
	}
	
	/**
	 * 检验阶段备注（如产成品检验异常、数据说明等）
	 */
	public java.lang.String getInspRemark() {
		return getStr("inspRemark");
	}
	
	/**
	 * 入库阶段备注（如产成品拒绝入库原因、入库特殊说明等）
	 */
	public void setStockRemark(java.lang.String stockRemark) {
		set("stockRemark", stockRemark);
	}
	
	/**
	 * 入库阶段备注（如产成品拒绝入库原因、入库特殊说明等）
	 */
	public java.lang.String getStockRemark() {
		return getStr("stockRemark");
	}
	
	/**
	 * 创建时间（自动生成）
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间（自动生成）
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间（自动维护）
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
	/**
	 * 送检数量
	 */
	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}
	
	/**
	 * 送检数量
	 */
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}
	
	/**
	 * 生产工单编号
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 生产工单编号
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
	/**
	 * 生产订单编号
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 生产订单编号
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 检验标准
	 */
	public void setInspStandard(java.lang.String inspStandard) {
		set("inspStandard", inspStandard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getInspStandard() {
		return getStr("inspStandard");
	}
	
	/**
	 * 厂内合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 厂内合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货单位
	 */
	public void setDeliveryUnit(java.lang.String deliveryUnit) {
		set("deliveryUnit", deliveryUnit);
	}
	
	/**
	 * 送货单位
	 */
	public java.lang.String getDeliveryUnit() {
		return getStr("deliveryUnit");
	}
	
}

