package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasItemClass<M extends BaseBasItemClass<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 分类编码（如：B, B01, B0101）
	 */
	public void setClasscode(java.lang.String classcode) {
		set("classcode", classcode);
	}
	
	/**
	 * 分类编码（如：B, B01, B0101）
	 */
	public java.lang.String getClasscode() {
		return getStr("classcode");
	}
	
	/**
	 * 分类名称
	 */
	public void setClassname(java.lang.String classname) {
		set("classname", classname);
	}
	
	/**
	 * 分类名称
	 */
	public java.lang.String getClassname() {
		return getStr("classname");
	}
	
	/**
	 * 上级分类id
	 */
	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}
	
	/**
	 * 上级分类id
	 */
	public java.lang.Integer getParentId() {
		return getInt("parentId");
	}
	
	/**
	 * 使用状态（0正常，1停用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 使用状态（0正常，1停用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 分类级别（1-一级，2-二级，3-三级）
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 分类级别（1-一级，2-二级，3-三级）
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 系统预设
	 */
	public void setSystempreset(java.lang.String systempreset) {
		set("systempreset", systempreset);
	}
	
	/**
	 * 系统预设
	 */
	public java.lang.String getSystempreset() {
		return getStr("systempreset");
	}
	
	/**
	 * 控制策略
	 */
	public void setControlstrategy(java.lang.String controlstrategy) {
		set("controlstrategy", controlstrategy);
	}
	
	/**
	 * 控制策略
	 */
	public java.lang.String getControlstrategy() {
		return getStr("controlstrategy");
	}
	
	/**
	 * 创建组织
	 */
	public void setCreateorg(java.lang.String createorg) {
		set("createorg", createorg);
	}
	
	/**
	 * 创建组织
	 */
	public java.lang.String getCreateorg() {
		return getStr("createorg");
	}
	
	/**
	 * 描述
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 描述
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 标志
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreatetime(java.util.Date createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreatetime() {
		return getDate("createtime");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdatetime(java.util.Date updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdatetime() {
		return getDate("updatetime");
	}
	
}

