package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlentityid<M extends BasePlentityid<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 实物ID
	 */
	public void setEntityCode(java.lang.String entityCode) {
		set("entityCode", entityCode);
	}
	
	/**
	 * 实物ID
	 */
	public java.lang.String getEntityCode() {
		return getStr("entityCode");
	}
	
	/**
	 * 采购订单行项目ID
	 */
	public void setPoItemId(java.lang.Long poItemId) {
		set("poItemId", poItemId);
	}
	
	/**
	 * 采购订单行项目ID
	 */
	public java.lang.Long getPoItemId() {
		return getLong("poItemId");
	}
	
	/**
	 * 实物生产状态
	 */
	public void setEntityStatus(java.lang.String entityStatus) {
		set("entityStatus", entityStatus);
	}
	
	/**
	 * 实物生产状态
	 */
	public java.lang.String getEntityStatus() {
		return getStr("entityStatus");
	}
	
	/**
	 * 数据来源
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 数据拥有方
	 */
	public void setOwnerId(java.lang.String ownerId) {
		set("ownerId", ownerId);
	}
	
	/**
	 * 数据拥有方
	 */
	public java.lang.String getOwnerId() {
		return getStr("ownerId");
	}
	
	/**
	 * 数据可见方
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 数据可见方
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}
	
	/**
	 * 预留字段
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 预留字段
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 删除标记用于逻辑删除(0-未删除,1-已删除)初始值都为0
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 删除标记用于逻辑删除(0-未删除,1-已删除)初始值都为0
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
}

