package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBascontractitem<M extends BaseBascontractitem<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 合同的编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 合同的编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 产品或原料的顺序号，无包装
	 */
	public void setItemid(java.lang.Long itemid) {
		set("itemid", itemid);
	}
	
	/**
	 * 产品或原料的顺序号，无包装
	 */
	public java.lang.Long getItemid() {
		return getLong("itemid");
	}
	
	/**
	 * 产品或原料的数量，包装合计
	 */
	public void setItemnum(java.math.BigDecimal itemnum) {
		set("itemnum", itemnum);
	}
	
	/**
	 * 产品或原料的数量，包装合计
	 */
	public java.math.BigDecimal getItemnum() {
		return get("itemnum");
	}
	
	/**
	 * 产品或原料的单位
	 */
	public void setItemunit(java.lang.String itemunit) {
		set("itemunit", itemunit);
	}
	
	/**
	 * 产品或原料的单位
	 */
	public java.lang.String getItemunit() {
		return getStr("itemunit");
	}
	
	/**
	 * 产品或原料的单价，计费单价
	 */
	public void setItemprice(java.math.BigDecimal itemprice) {
		set("itemprice", itemprice);
	}
	
	/**
	 * 产品或原料的单价，计费单价
	 */
	public java.math.BigDecimal getItemprice() {
		return get("itemprice");
	}
	
	/**
	 * 一种产品或原料的总金额，运费合计
	 */
	public void setItemsum(java.math.BigDecimal itemsum) {
		set("itemsum", itemsum);
	}
	
	/**
	 * 一种产品或原料的总金额，运费合计
	 */
	public java.math.BigDecimal getItemsum() {
		return get("itemsum");
	}
	
	/**
	 * 合同的总金额------目前没有用，对每条记录进行加操作
	 */
	public void setContractsum(java.math.BigDecimal contractsum) {
		set("contractsum", contractsum);
	}
	
	/**
	 * 合同的总金额------目前没有用，对每条记录进行加操作
	 */
	public java.math.BigDecimal getContractsum() {
		return get("contractsum");
	}
	
	/**
	 * 产品或原料的单重，计费重量
	 */
	public void setItemweight(java.math.BigDecimal itemweight) {
		set("itemweight", itemweight);
	}
	
	/**
	 * 产品或原料的单重，计费重量
	 */
	public java.math.BigDecimal getItemweight() {
		return get("itemweight");
	}
	
	/**
	 * 一种产品或原料的总重，计费公里
	 */
	public void setItemgrossweight(java.math.BigDecimal itemgrossweight) {
		set("itemgrossweight", itemgrossweight);
	}
	
	/**
	 * 一种产品或原料的总重，计费公里
	 */
	public java.math.BigDecimal getItemgrossweight() {
		return get("itemgrossweight");
	}
	
	/**
	 * 产品或物料相关备注
	 */
	public void setItemmemo(java.lang.String itemmemo) {
		set("itemmemo", itemmemo);
	}
	
	/**
	 * 产品或物料相关备注
	 */
	public java.lang.String getItemmemo() {
		return getStr("itemmemo");
	}
	
	/**
	 * 发货时间及数量（itemsenddate），货物起运日期
	 */
	public void setItemsenddate(java.lang.String itemsenddate) {
		set("itemsenddate", itemsenddate);
	}
	
	/**
	 * 发货时间及数量（itemsenddate），货物起运日期
	 */
	public java.lang.String getItemsenddate() {
		return getStr("itemsenddate");
	}
	
	/**
	 * 0正常，-1删除
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 0正常，-1删除
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
}

