package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlReportWorkOrder<M extends BasePlReportWorkOrder<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID（自增）
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID（自增）
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码（必选）
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码（必选）
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商编码（必选）
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码（必选）
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 生产订单编号（必选）
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 生产订单编号（必选）
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 生产工单编号（必选）
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 生产工单编号（必选）
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
	/**
	 * 生产批次号（必选）
	 */
	public void setProductBatchNo(java.lang.String productBatchNo) {
		set("productBatchNo", productBatchNo);
	}
	
	/**
	 * 生产批次号（必选）
	 */
	public java.lang.String getProductBatchNo() {
		return getStr("productBatchNo");
	}
	
	/**
	 * 工序名称（必选）
	 */
	public void setProcessName(java.lang.String processName) {
		set("processName", processName);
	}
	
	/**
	 * 工序名称（必选）
	 */
	public java.lang.String getProcessName() {
		return getStr("processName");
	}
	
	/**
	 * 品类编码（必选）
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码（必选）
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码（必选）
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码（必选）
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 工序编码（必选）
	 */
	public void setProcessCode(java.lang.String processCode) {
		set("processCode", processCode);
	}
	
	/**
	 * 工序编码（必选）
	 */
	public java.lang.String getProcessCode() {
		return getStr("processCode");
	}
	
	/**
	 * 数据来源（必选）
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源（必选）
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间（必选）
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间（必选）
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 客户所属省份（必选）
	 */
	public void setBuyerProvince(java.lang.String buyerProvince) {
		set("buyerProvince", buyerProvince);
	}
	
	/**
	 * 客户所属省份（必选）
	 */
	public java.lang.String getBuyerProvince() {
		return getStr("buyerProvince");
	}
	
	/**
	 * 产品内部ID号（可选）
	 */
	public void setInsideNo(java.lang.String insideNo) {
		set("insideNo", insideNo);
	}
	
	/**
	 * 产品内部ID号（可选）
	 */
	public java.lang.String getInsideNo() {
		return getStr("insideNo");
	}
	
	/**
	 * 设备编号（可选）
	 */
	public void setDeviceNo(java.lang.String deviceNo) {
		set("deviceNo", deviceNo);
	}
	
	/**
	 * 设备编号（可选）
	 */
	public java.lang.String getDeviceNo() {
		return getStr("deviceNo");
	}
	
	/**
	 * 生产工艺路线编码（可选）
	 */
	public void setProcessNo(java.lang.String processNo) {
		set("processNo", processNo);
	}
	
	/**
	 * 生产工艺路线编码（可选）
	 */
	public java.lang.String getProcessNo() {
		return getStr("processNo");
	}
	
	/**
	 * 生产车间id（可选）
	 */
	public void setWorkshopId(java.lang.String workshopId) {
		set("workshopId", workshopId);
	}
	
	/**
	 * 生产车间id（可选）
	 */
	public java.lang.String getWorkshopId() {
		return getStr("workshopId");
	}
	
	/**
	 * 生产车间编码（可选）
	 */
	public void setWorkshopCode(java.lang.String workshopCode) {
		set("workshopCode", workshopCode);
	}
	
	/**
	 * 生产车间编码（可选）
	 */
	public java.lang.String getWorkshopCode() {
		return getStr("workshopCode");
	}
	
	/**
	 * 生产车间名称（可选）
	 */
	public void setWorkshopName(java.lang.String workshopName) {
		set("workshopName", workshopName);
	}
	
	/**
	 * 生产车间名称（可选）
	 */
	public java.lang.String getWorkshopName() {
		return getStr("workshopName");
	}
	
	/**
	 * 实物id，如国网实物id（可选）
	 */
	public void setEntityId(java.lang.String entityId) {
		set("entityId", entityId);
	}
	
	/**
	 * 实物id，如国网实物id（可选）
	 */
	public java.lang.String getEntityId() {
		return getStr("entityId");
	}
	
	/**
	 * 计划开始时间（可选）
	 */
	public void setPlanStartTime(java.util.Date planStartTime) {
		set("planStartTime", planStartTime);
	}
	
	/**
	 * 计划开始时间（可选）
	 */
	public java.util.Date getPlanStartTime() {
		return getDate("planStartTime");
	}
	
	/**
	 * 计划结束时间（可选）
	 */
	public void setPlanEndTime(java.util.Date planEndTime) {
		set("planEndTime", planEndTime);
	}
	
	/**
	 * 计划结束时间（可选）
	 */
	public java.util.Date getPlanEndTime() {
		return getDate("planEndTime");
	}
	
	/**
	 * 实际开始时间（可选）
	 */
	public void setActualStartDate(java.util.Date actualStartDate) {
		set("actualStartDate", actualStartDate);
	}
	
	/**
	 * 实际开始时间（可选）
	 */
	public java.util.Date getActualStartDate() {
		return getDate("actualStartDate");
	}
	
	/**
	 * 实际结束时间（可选）
	 */
	public void setActualFinishDate(java.util.Date actualFinishDate) {
		set("actualFinishDate", actualFinishDate);
	}
	
	/**
	 * 实际结束时间（可选）
	 */
	public java.util.Date getActualFinishDate() {
		return getDate("actualFinishDate");
	}
	
	/**
	 * 订单状态（可选）
	 */
	public void setOrderStatus(java.lang.String orderStatus) {
		set("orderStatus", orderStatus);
	}
	
	/**
	 * 订单状态（可选）
	 */
	public java.lang.String getOrderStatus() {
		return getStr("orderStatus");
	}
	
	/**
	 * 状态（10录入，20确认,30进行中，40已完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态（10录入，20确认,30进行中，40已完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 记录创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("createdTime", createdTime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("createdTime");
	}
	
	/**
	 * 记录更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updatedTime", updatedTime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updatedTime");
	}
	
	/**
	 * 报工单编号
	 */
	public void setReportNo(java.lang.String reportNo) {
		set("reportNo", reportNo);
	}
	
	/**
	 * 报工单编号
	 */
	public java.lang.String getReportNo() {
		return getStr("reportNo");
	}
	
}

