package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClDxls<M extends BaseClDxls<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号？来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号？来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库编号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库编号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分实测值-C1
	 */
	public void setChemC1(java.math.BigDecimal chemC1) {
		set("chemC1", chemC1);
	}
	
	/**
	 * 化学成分实测值-C1
	 */
	public java.math.BigDecimal getChemC1() {
		return get("chemC1");
	}
	
	/**
	 * 化学成分实测值-C2
	 */
	public void setChemC2(java.math.BigDecimal chemC2) {
		set("chemC2", chemC2);
	}
	
	/**
	 * 化学成分实测值-C2
	 */
	public java.math.BigDecimal getChemC2() {
		return get("chemC2");
	}
	
	/**
	 * 化学成分实测值-C3
	 */
	public void setChemC3(java.math.BigDecimal chemC3) {
		set("chemC3", chemC3);
	}
	
	/**
	 * 化学成分实测值-C3
	 */
	public java.math.BigDecimal getChemC3() {
		return get("chemC3");
	}
	
	/**
	 * 化学成分实测值-Si1
	 */
	public void setChemSi1(java.math.BigDecimal chemSi1) {
		set("chemSi1", chemSi1);
	}
	
	/**
	 * 化学成分实测值-Si1
	 */
	public java.math.BigDecimal getChemSi1() {
		return get("chemSi1");
	}
	
	/**
	 * 化学成分实测值-Si2
	 */
	public void setChemSi2(java.math.BigDecimal chemSi2) {
		set("chemSi2", chemSi2);
	}
	
	/**
	 * 化学成分实测值-Si2
	 */
	public java.math.BigDecimal getChemSi2() {
		return get("chemSi2");
	}
	
	/**
	 * 化学成分实测值-Si3
	 */
	public void setChemSi3(java.math.BigDecimal chemSi3) {
		set("chemSi3", chemSi3);
	}
	
	/**
	 * 化学成分实测值-Si3
	 */
	public java.math.BigDecimal getChemSi3() {
		return get("chemSi3");
	}
	
	/**
	 * 化学成分实测值-Mn1
	 */
	public void setChemMn1(java.math.BigDecimal chemMn1) {
		set("chemMn1", chemMn1);
	}
	
	/**
	 * 化学成分实测值-Mn1
	 */
	public java.math.BigDecimal getChemMn1() {
		return get("chemMn1");
	}
	
	/**
	 * 化学成分实测值-Mn2
	 */
	public void setChemMn2(java.math.BigDecimal chemMn2) {
		set("chemMn2", chemMn2);
	}
	
	/**
	 * 化学成分实测值-Mn2
	 */
	public java.math.BigDecimal getChemMn2() {
		return get("chemMn2");
	}
	
	/**
	 * 化学成分实测值-Mn3
	 */
	public void setChemMn3(java.math.BigDecimal chemMn3) {
		set("chemMn3", chemMn3);
	}
	
	/**
	 * 化学成分实测值-Mn3
	 */
	public java.math.BigDecimal getChemMn3() {
		return get("chemMn3");
	}
	
	/**
	 * 化学成分实测值-P1
	 */
	public void setChemP1(java.math.BigDecimal chemP1) {
		set("chemP1", chemP1);
	}
	
	/**
	 * 化学成分实测值-P1
	 */
	public java.math.BigDecimal getChemP1() {
		return get("chemP1");
	}
	
	/**
	 * 化学成分实测值-P2
	 */
	public void setChemP2(java.math.BigDecimal chemP2) {
		set("chemP2", chemP2);
	}
	
	/**
	 * 化学成分实测值-P2
	 */
	public java.math.BigDecimal getChemP2() {
		return get("chemP2");
	}
	
	/**
	 * 化学成分实测值-P3
	 */
	public void setChemP3(java.math.BigDecimal chemP3) {
		set("chemP3", chemP3);
	}
	
	/**
	 * 化学成分实测值-P3
	 */
	public java.math.BigDecimal getChemP3() {
		return get("chemP3");
	}
	
	/**
	 * 化学成分实测值-S1
	 */
	public void setChemS1(java.math.BigDecimal chemS1) {
		set("chemS1", chemS1);
	}
	
	/**
	 * 化学成分实测值-S1
	 */
	public java.math.BigDecimal getChemS1() {
		return get("chemS1");
	}
	
	/**
	 * 化学成分实测值-S2
	 */
	public void setChemS2(java.math.BigDecimal chemS2) {
		set("chemS2", chemS2);
	}
	
	/**
	 * 化学成分实测值-S2
	 */
	public java.math.BigDecimal getChemS2() {
		return get("chemS2");
	}
	
	/**
	 * 化学成分实测值-S3
	 */
	public void setChemS3(java.math.BigDecimal chemS3) {
		set("chemS3", chemS3);
	}
	
	/**
	 * 化学成分实测值-S3
	 */
	public java.math.BigDecimal getChemS3() {
		return get("chemS3");
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public void setChemCRequired(java.math.BigDecimal chemCRequired) {
		set("chemCRequired", chemCRequired);
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public java.math.BigDecimal getChemCRequired() {
		return get("chemCRequired");
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public void setChemSiRequired(java.math.BigDecimal chemSiRequired) {
		set("chemSiRequired", chemSiRequired);
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public java.math.BigDecimal getChemSiRequired() {
		return get("chemSiRequired");
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public void setChemMnRequired(java.math.BigDecimal chemMnRequired) {
		set("chemMnRequired", chemMnRequired);
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public java.math.BigDecimal getChemMnRequired() {
		return get("chemMnRequired");
	}
	
	/**
	 * 化学成分要求值-P
	 */
	public void setChemPRequired(java.math.BigDecimal chemPRequired) {
		set("chemPRequired", chemPRequired);
	}
	
	/**
	 * 化学成分要求值-P
	 */
	public java.math.BigDecimal getChemPRequired() {
		return get("chemPRequired");
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public void setChemSRequired(java.math.BigDecimal chemSRequired) {
		set("chemSRequired", chemSRequired);
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public java.math.BigDecimal getChemSRequired() {
		return get("chemSRequired");
	}
	
	/**
	 * 硬度实测值-hardness1
	 */
	public void setHardness1(java.math.BigDecimal hardness1) {
		set("hardness1", hardness1);
	}
	
	/**
	 * 硬度实测值-hardness1
	 */
	public java.math.BigDecimal getHardness1() {
		return get("hardness1");
	}
	
	/**
	 * 硬度实测值-hardness2
	 */
	public void setHardness2(java.math.BigDecimal hardness2) {
		set("hardness2", hardness2);
	}
	
	/**
	 * 硬度实测值-hardness2
	 */
	public java.math.BigDecimal getHardness2() {
		return get("hardness2");
	}
	
	/**
	 * 硬度实测值-hardness3
	 */
	public void setHardness3(java.math.BigDecimal hardness3) {
		set("hardness3", hardness3);
	}
	
	/**
	 * 硬度实测值-hardness3
	 */
	public java.math.BigDecimal getHardness3() {
		return get("hardness3");
	}
	
	/**
	 * 硬度实测值-hardness4
	 */
	public void setHardness4(java.math.BigDecimal hardness4) {
		set("hardness4", hardness4);
	}
	
	/**
	 * 硬度实测值-hardness4
	 */
	public java.math.BigDecimal getHardness4() {
		return get("hardness4");
	}
	
	/**
	 * 硬度实测值-hardness5
	 */
	public void setHardness5(java.math.BigDecimal hardness5) {
		set("hardness5", hardness5);
	}
	
	/**
	 * 硬度实测值-hardness5
	 */
	public java.math.BigDecimal getHardness5() {
		return get("hardness5");
	}
	
	/**
	 * 硬度要求值-hardnessRequired
	 */
	public void setHardnessRequired(java.math.BigDecimal hardnessRequired) {
		set("hardnessRequired", hardnessRequired);
	}
	
	/**
	 * 硬度要求值-hardnessRequired
	 */
	public java.math.BigDecimal getHardnessRequired() {
		return get("hardnessRequired");
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle1
	 */
	public void setZincLayerThicknessSingle1(java.math.BigDecimal zincLayerThicknessSingle1) {
		set("zincLayerThicknessSingle1", zincLayerThicknessSingle1);
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle1
	 */
	public java.math.BigDecimal getZincLayerThicknessSingle1() {
		return get("zincLayerThicknessSingle1");
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle2
	 */
	public void setZincLayerThicknessSingle2(java.math.BigDecimal zincLayerThicknessSingle2) {
		set("zincLayerThicknessSingle2", zincLayerThicknessSingle2);
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle2
	 */
	public java.math.BigDecimal getZincLayerThicknessSingle2() {
		return get("zincLayerThicknessSingle2");
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle3
	 */
	public void setZincLayerThicknessSingle3(java.math.BigDecimal zincLayerThicknessSingle3) {
		set("zincLayerThicknessSingle3", zincLayerThicknessSingle3);
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle3
	 */
	public java.math.BigDecimal getZincLayerThicknessSingle3() {
		return get("zincLayerThicknessSingle3");
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle4
	 */
	public void setZincLayerThicknessSingle4(java.math.BigDecimal zincLayerThicknessSingle4) {
		set("zincLayerThicknessSingle4", zincLayerThicknessSingle4);
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle4
	 */
	public java.math.BigDecimal getZincLayerThicknessSingle4() {
		return get("zincLayerThicknessSingle4");
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle5
	 */
	public void setZincLayerThicknessSingle5(java.math.BigDecimal zincLayerThicknessSingle5) {
		set("zincLayerThicknessSingle5", zincLayerThicknessSingle5);
	}
	
	/**
	 * 单体锌层厚度实测值-zincLayerThicknessSingle5
	 */
	public java.math.BigDecimal getZincLayerThicknessSingle5() {
		return get("zincLayerThicknessSingle5");
	}
	
	/**
	 * 单体锌层厚度要求值-zincLayerThicknessSingleRequired
	 */
	public void setZincLayerThicknessSingleRequired(java.math.BigDecimal zincLayerThicknessSingleRequired) {
		set("zincLayerThicknessSingleRequired", zincLayerThicknessSingleRequired);
	}
	
	/**
	 * 单体锌层厚度要求值-zincLayerThicknessSingleRequired
	 */
	public java.math.BigDecimal getZincLayerThicknessSingleRequired() {
		return get("zincLayerThicknessSingleRequired");
	}
	
	/**
	 * 总体锌层厚度实测值-zincLayerThicknessTotal
	 */
	public void setZincLayerThicknessTotal(java.math.BigDecimal zincLayerThicknessTotal) {
		set("zincLayerThicknessTotal", zincLayerThicknessTotal);
	}
	
	/**
	 * 总体锌层厚度实测值-zincLayerThicknessTotal
	 */
	public java.math.BigDecimal getZincLayerThicknessTotal() {
		return get("zincLayerThicknessTotal");
	}
	
	/**
	 * 总体锌层厚度要求值-zincLayerThicknessTotalRequired
	 */
	public void setZincLayerThicknessTotalRequired(java.math.BigDecimal zincLayerThicknessTotalRequired) {
		set("zincLayerThicknessTotalRequired", zincLayerThicknessTotalRequired);
	}
	
	/**
	 * 总体锌层厚度要求值-zincLayerThicknessTotalRequired
	 */
	public java.math.BigDecimal getZincLayerThicknessTotalRequired() {
		return get("zincLayerThicknessTotalRequired");
	}
	
	/**
	 * 机械性能实测值-mechanicalProperties1
	 */
	public void setMechanicalProperties1(java.math.BigDecimal mechanicalProperties1) {
		set("mechanicalProperties1", mechanicalProperties1);
	}
	
	/**
	 * 机械性能实测值-mechanicalProperties1
	 */
	public java.math.BigDecimal getMechanicalProperties1() {
		return get("mechanicalProperties1");
	}
	
	/**
	 * 机械性能实测值-mechanicalProperties2
	 */
	public void setMechanicalProperties2(java.math.BigDecimal mechanicalProperties2) {
		set("mechanicalProperties2", mechanicalProperties2);
	}
	
	/**
	 * 机械性能实测值-mechanicalProperties2
	 */
	public java.math.BigDecimal getMechanicalProperties2() {
		return get("mechanicalProperties2");
	}
	
	/**
	 * 机械性能实测值-mechanicalProperties3
	 */
	public void setMechanicalProperties3(java.math.BigDecimal mechanicalProperties3) {
		set("mechanicalProperties3", mechanicalProperties3);
	}
	
	/**
	 * 机械性能实测值-mechanicalProperties3
	 */
	public java.math.BigDecimal getMechanicalProperties3() {
		return get("mechanicalProperties3");
	}
	
	/**
	 * 机械性能要求值-mechanicalPropertiesRequired
	 */
	public void setMechanicalPropertiesRequired(java.math.BigDecimal mechanicalPropertiesRequired) {
		set("mechanicalPropertiesRequired", mechanicalPropertiesRequired);
	}
	
	/**
	 * 机械性能要求值-mechanicalPropertiesRequired
	 */
	public java.math.BigDecimal getMechanicalPropertiesRequired() {
		return get("mechanicalPropertiesRequired");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeaveFactoryDate(java.util.Date leaveFactoryDate) {
		set("leaveFactoryDate", leaveFactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeaveFactoryDate() {
		return getDate("leaveFactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过待入库，60确认入库，待审核，70审核入库通过入库成功
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过待入库，60确认入库，待审核，70审核入库通过入库成功
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasNo(java.lang.String basNo) {
		set("basNo", basNo);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasNo() {
		return getStr("basNo");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 抽检数量总
	 */
	public void setSampleQuantity(java.math.BigDecimal sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 抽检数量总
	 */
	public java.math.BigDecimal getSampleQuantity() {
		return get("sampleQuantity");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setCompInspQty(java.math.BigDecimal compInspQty) {
		set("compInspQty", compInspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getCompInspQty() {
		return get("compInspQty");
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public void setMechInspQty(java.math.BigDecimal mechInspQty) {
		set("mechInspQty", mechInspQty);
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public java.math.BigDecimal getMechInspQty() {
		return get("mechInspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 尺寸d1
	 */
	public void setSized1(java.math.BigDecimal sized1) {
		set("sized1", sized1);
	}
	
	/**
	 * 尺寸d1
	 */
	public java.math.BigDecimal getSized1() {
		return get("sized1");
	}
	
	/**
	 * 尺寸d2
	 */
	public void setSized2(java.math.BigDecimal sized2) {
		set("sized2", sized2);
	}
	
	/**
	 * 尺寸d2
	 */
	public java.math.BigDecimal getSized2() {
		return get("sized2");
	}
	
	/**
	 * 尺寸d3
	 */
	public void setSized3(java.math.BigDecimal sized3) {
		set("sized3", sized3);
	}
	
	/**
	 * 尺寸d3
	 */
	public java.math.BigDecimal getSized3() {
		return get("sized3");
	}
	
	/**
	 * 尺寸d4
	 */
	public void setSized4(java.math.BigDecimal sized4) {
		set("sized4", sized4);
	}
	
	/**
	 * 尺寸d4
	 */
	public java.math.BigDecimal getSized4() {
		return get("sized4");
	}
	
	/**
	 * 尺寸d5
	 */
	public void setSized5(java.math.BigDecimal sized5) {
		set("sized5", sized5);
	}
	
	/**
	 * 尺寸d5
	 */
	public java.math.BigDecimal getSized5() {
		return get("sized5");
	}
	
	/**
	 * 尺寸L1
	 */
	public void setSizeL1(java.math.BigDecimal sizeL1) {
		set("sizeL1", sizeL1);
	}
	
	/**
	 * 尺寸L1
	 */
	public java.math.BigDecimal getSizeL1() {
		return get("sizeL1");
	}
	
	/**
	 * 尺寸L2
	 */
	public void setSizeL2(java.math.BigDecimal sizeL2) {
		set("sizeL2", sizeL2);
	}
	
	/**
	 * 尺寸L2
	 */
	public java.math.BigDecimal getSizeL2() {
		return get("sizeL2");
	}
	
	/**
	 * 尺寸L3
	 */
	public void setSizeL3(java.math.BigDecimal sizeL3) {
		set("sizeL3", sizeL3);
	}
	
	/**
	 * 尺寸L3
	 */
	public java.math.BigDecimal getSizeL3() {
		return get("sizeL3");
	}
	
	/**
	 * 尺寸L4
	 */
	public void setSizeL4(java.math.BigDecimal sizeL4) {
		set("sizeL4", sizeL4);
	}
	
	/**
	 * 尺寸L4
	 */
	public java.math.BigDecimal getSizeL4() {
		return get("sizeL4");
	}
	
	/**
	 * 尺寸L5
	 */
	public void setSizeL5(java.math.BigDecimal sizeL5) {
		set("sizeL5", sizeL5);
	}
	
	/**
	 * 尺寸L5
	 */
	public java.math.BigDecimal getSizeL5() {
		return get("sizeL5");
	}
	
	/**
	 * 尺寸b1
	 */
	public void setSizeb1(java.math.BigDecimal sizeb1) {
		set("sizeb1", sizeb1);
	}
	
	/**
	 * 尺寸b1
	 */
	public java.math.BigDecimal getSizeb1() {
		return get("sizeb1");
	}
	
	/**
	 * 尺寸b2
	 */
	public void setSizeb2(java.math.BigDecimal sizeb2) {
		set("sizeb2", sizeb2);
	}
	
	/**
	 * 尺寸b2
	 */
	public java.math.BigDecimal getSizeb2() {
		return get("sizeb2");
	}
	
	/**
	 * 尺寸b3
	 */
	public void setSizeb3(java.math.BigDecimal sizeb3) {
		set("sizeb3", sizeb3);
	}
	
	/**
	 * 尺寸b3
	 */
	public java.math.BigDecimal getSizeb3() {
		return get("sizeb3");
	}
	
	/**
	 * 尺寸b4
	 */
	public void setSizeb4(java.math.BigDecimal sizeb4) {
		set("sizeb4", sizeb4);
	}
	
	/**
	 * 尺寸b4
	 */
	public java.math.BigDecimal getSizeb4() {
		return get("sizeb4");
	}
	
	/**
	 * 尺寸b5
	 */
	public void setSizeb5(java.math.BigDecimal sizeb5) {
		set("sizeb5", sizeb5);
	}
	
	/**
	 * 尺寸b5
	 */
	public java.math.BigDecimal getSizeb5() {
		return get("sizeb5");
	}
	
}

