package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClGb<M extends BaseClGb<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库单号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库单号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分分析-C
	 */
	public void setChemC(java.math.BigDecimal chemC) {
		set("chemC", chemC);
	}
	
	/**
	 * 化学成分分析-C
	 */
	public java.math.BigDecimal getChemC() {
		return get("chemC");
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分分析-P
	 */
	public void setChemP(java.math.BigDecimal chemP) {
		set("chemP", chemP);
	}
	
	/**
	 * 化学成分分析-P
	 */
	public java.math.BigDecimal getChemP() {
		return get("chemP");
	}
	
	/**
	 * 化学成分分析-S
	 */
	public void setChemS(java.math.BigDecimal chemS) {
		set("chemS", chemS);
	}
	
	/**
	 * 化学成分分析-S
	 */
	public java.math.BigDecimal getChemS() {
		return get("chemS");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeavefactoryDate(java.util.Date leavefactoryDate) {
		set("leavefactoryDate", leavefactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeavefactoryDate() {
		return getDate("leavefactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasno(java.lang.String basno) {
		set("basno", basno);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasno() {
		return getStr("basno");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	public void setQuantity(java.lang.String quantity) {
		set("quantity", quantity);
	}
	
	public java.lang.String getQuantity() {
		return getStr("quantity");
	}
	
	/**
	 * 总抽检数量
	 */
	public void setSampleQuantity(java.lang.String sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 总抽检数量
	 */
	public java.lang.String getSampleQuantity() {
		return getStr("sampleQuantity");
	}
	
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}
	
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 审核人
	 */
	public void setAuditor(java.lang.String auditor) {
		set("auditor", auditor);
	}
	
	/**
	 * 审核人
	 */
	public java.lang.String getAuditor() {
		return getStr("auditor");
	}
	
	/**
	 * 检验人
	 */
	public void setChecker(java.lang.String checker) {
		set("checker", checker);
	}
	
	/**
	 * 检验人
	 */
	public java.lang.String getChecker() {
		return getStr("checker");
	}
	
	/**
	 * 抗拉强度1#
	 */
	public void setMechtensileStrength1(java.math.BigDecimal mechtensileStrength1) {
		set("mechtensileStrength1", mechtensileStrength1);
	}
	
	/**
	 * 抗拉强度1#
	 */
	public java.math.BigDecimal getMechtensileStrength1() {
		return get("mechtensileStrength1");
	}
	
	/**
	 * 屈服强度1#
	 */
	public void setMechyieldStrength1(java.math.BigDecimal mechyieldStrength1) {
		set("mechyieldStrength1", mechyieldStrength1);
	}
	
	/**
	 * 屈服强度1#
	 */
	public java.math.BigDecimal getMechyieldStrength1() {
		return get("mechyieldStrength1");
	}
	
	/**
	 * 延长率1#
	 */
	public void setMechelongation1(java.math.BigDecimal mechelongation1) {
		set("mechelongation1", mechelongation1);
	}
	
	/**
	 * 延长率1#
	 */
	public java.math.BigDecimal getMechelongation1() {
		return get("mechelongation1");
	}
	
	/**
	 * 冲击实验1#
	 */
	public void setImpactexp1(java.lang.String impactexp1) {
		set("impactexp1", impactexp1);
	}
	
	/**
	 * 冲击实验1#
	 */
	public java.lang.String getImpactexp1() {
		return getStr("impactexp1");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setCompInspQty(java.math.BigDecimal compInspQty) {
		set("compInspQty", compInspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getCompInspQty() {
		return get("compInspQty");
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public void setMeInspQty(java.math.BigDecimal meInspQty) {
		set("meInspQty", meInspQty);
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public java.math.BigDecimal getMeInspQty() {
		return get("meInspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public void setMechtensileStrengthRequired(java.math.BigDecimal mechtensileStrengthRequired) {
		set("mechtensileStrengthRequired", mechtensileStrengthRequired);
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public java.math.BigDecimal getMechtensileStrengthRequired() {
		return get("mechtensileStrengthRequired");
	}
	
	/**
	 * 屈服强度要求值
	 */
	public void setMechyieldStrengthRequired(java.math.BigDecimal mechyieldStrengthRequired) {
		set("mechyieldStrengthRequired", mechyieldStrengthRequired);
	}
	
	/**
	 * 屈服强度要求值
	 */
	public java.math.BigDecimal getMechyieldStrengthRequired() {
		return get("mechyieldStrengthRequired");
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public void setChemCRequired(java.math.BigDecimal chemCRequired) {
		set("chemCRequired", chemCRequired);
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public java.math.BigDecimal getChemCRequired() {
		return get("chemCRequired");
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public void setChemMnRequired(java.math.BigDecimal chemMnRequired) {
		set("chemMnRequired", chemMnRequired);
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public java.math.BigDecimal getChemMnRequired() {
		return get("chemMnRequired");
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public void setChemSiRequired(java.math.BigDecimal chemSiRequired) {
		set("chemSiRequired", chemSiRequired);
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public java.math.BigDecimal getChemSiRequired() {
		return get("chemSiRequired");
	}
	
	/**
	 * 化学成分要求值-P
	 */
	public void setChemPRequired(java.math.BigDecimal chemPRequired) {
		set("chemPRequired", chemPRequired);
	}
	
	/**
	 * 化学成分要求值-P
	 */
	public java.math.BigDecimal getChemPRequired() {
		return get("chemPRequired");
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public void setChemSRequired(java.math.BigDecimal chemSRequired) {
		set("chemSRequired", chemSRequired);
	}
	
	/**
	 * 化学成分要求值-S
	 */
	public java.math.BigDecimal getChemSRequired() {
		return get("chemSRequired");
	}
	
	/**
	 * 延伸率要求值
	 */
	public void setMechelongationRequired(java.math.BigDecimal mechelongationRequired) {
		set("mechelongationRequired", mechelongationRequired);
	}
	
	/**
	 * 延伸率要求值
	 */
	public java.math.BigDecimal getMechelongationRequired() {
		return get("mechelongationRequired");
	}
	
	/**
	 * 抗拉强度2#
	 */
	public void setMechtensileStrength2(java.math.BigDecimal mechtensileStrength2) {
		set("mechtensileStrength2", mechtensileStrength2);
	}
	
	/**
	 * 抗拉强度2#
	 */
	public java.math.BigDecimal getMechtensileStrength2() {
		return get("mechtensileStrength2");
	}
	
	/**
	 * 抗拉强度3#
	 */
	public void setMechtensileStrength3(java.math.BigDecimal mechtensileStrength3) {
		set("mechtensileStrength3", mechtensileStrength3);
	}
	
	/**
	 * 抗拉强度3#
	 */
	public java.math.BigDecimal getMechtensileStrength3() {
		return get("mechtensileStrength3");
	}
	
	/**
	 * 屈服强度2#
	 */
	public void setMechyieldStrength2(java.math.BigDecimal mechyieldStrength2) {
		set("mechyieldStrength2", mechyieldStrength2);
	}
	
	/**
	 * 屈服强度2#
	 */
	public java.math.BigDecimal getMechyieldStrength2() {
		return get("mechyieldStrength2");
	}
	
	/**
	 * 屈服强度3#
	 */
	public void setMechyieldStrength3(java.math.BigDecimal mechyieldStrength3) {
		set("mechyieldStrength3", mechyieldStrength3);
	}
	
	/**
	 * 屈服强度3#
	 */
	public java.math.BigDecimal getMechyieldStrength3() {
		return get("mechyieldStrength3");
	}
	
	/**
	 * 延长率2#
	 */
	public void setMechelongation2(java.math.BigDecimal mechelongation2) {
		set("mechelongation2", mechelongation2);
	}
	
	/**
	 * 延长率2#
	 */
	public java.math.BigDecimal getMechelongation2() {
		return get("mechelongation2");
	}
	
	/**
	 * 延长率3#
	 */
	public void setMechelongation3(java.math.BigDecimal mechelongation3) {
		set("mechelongation3", mechelongation3);
	}
	
	/**
	 * 延长率3#
	 */
	public java.math.BigDecimal getMechelongation3() {
		return get("mechelongation3");
	}
	
	/**
	 * 冲击实验2#
	 */
	public void setImpactexp2(java.lang.String impactexp2) {
		set("impactexp2", impactexp2);
	}
	
	/**
	 * 冲击实验2#
	 */
	public java.lang.String getImpactexp2() {
		return getStr("impactexp2");
	}
	
	/**
	 * 冲击实验3#
	 */
	public void setImpactexp3(java.lang.String impactexp3) {
		set("impactexp3", impactexp3);
	}
	
	/**
	 * 冲击实验3#
	 */
	public java.lang.String getImpactexp3() {
		return getStr("impactexp3");
	}
	
}

