package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBascontractitem<M extends BaseBascontractitem<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 合同的编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 合同的编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 产品或原料的顺序号，无包装
	 */
	public void setItemid(java.lang.Long itemid) {
		set("itemid", itemid);
	}
	
	/**
	 * 产品或原料的顺序号，无包装
	 */
	public java.lang.Long getItemid() {
		return getLong("itemid");
	}
	
	/**
	 * 产品或原料的数量，包装合计
	 */
	public void setItemnum(java.math.BigDecimal itemnum) {
		set("itemnum", itemnum);
	}
	
	/**
	 * 产品或原料的数量，包装合计
	 */
	public java.math.BigDecimal getItemnum() {
		return get("itemnum");
	}
	
	/**
	 * 产品或原料的单位
	 */
	public void setItemunit(java.lang.String itemunit) {
		set("itemunit", itemunit);
	}
	
	/**
	 * 产品或原料的单位
	 */
	public java.lang.String getItemunit() {
		return getStr("itemunit");
	}
	
	/**
	 * 产品或原料的单价，计费单价
	 */
	public void setItemprice(java.math.BigDecimal itemprice) {
		set("itemprice", itemprice);
	}
	
	/**
	 * 产品或原料的单价，计费单价
	 */
	public java.math.BigDecimal getItemprice() {
		return get("itemprice");
	}
	
	/**
	 * 一种产品或原料的总金额，运费合计
	 */
	public void setItemsum(java.math.BigDecimal itemsum) {
		set("itemsum", itemsum);
	}
	
	/**
	 * 一种产品或原料的总金额，运费合计
	 */
	public java.math.BigDecimal getItemsum() {
		return get("itemsum");
	}
	
	/**
	 * 合同的总金额------目前没有用，对每条记录进行加操作
	 */
	public void setContractsum(java.math.BigDecimal contractsum) {
		set("contractsum", contractsum);
	}
	
	/**
	 * 合同的总金额------目前没有用，对每条记录进行加操作
	 */
	public java.math.BigDecimal getContractsum() {
		return get("contractsum");
	}
	
	/**
	 * 产品或原料的单重，计费重量
	 */
	public void setItemweight(java.math.BigDecimal itemweight) {
		set("itemweight", itemweight);
	}
	
	/**
	 * 产品或原料的单重，计费重量
	 */
	public java.math.BigDecimal getItemweight() {
		return get("itemweight");
	}
	
	/**
	 * 一种产品或原料的总重，计费公里
	 */
	public void setItemgrossweight(java.math.BigDecimal itemgrossweight) {
		set("itemgrossweight", itemgrossweight);
	}
	
	/**
	 * 一种产品或原料的总重，计费公里
	 */
	public java.math.BigDecimal getItemgrossweight() {
		return get("itemgrossweight");
	}
	
	/**
	 * 产品或物料相关备注
	 */
	public void setItemmemo(java.lang.String itemmemo) {
		set("itemmemo", itemmemo);
	}
	
	/**
	 * 产品或物料相关备注
	 */
	public java.lang.String getItemmemo() {
		return getStr("itemmemo");
	}
	
	/**
	 * 发货时间及数量（itemsenddate），货物起运日期
	 */
	public void setItemsenddate(java.lang.String itemsenddate) {
		set("itemsenddate", itemsenddate);
	}
	
	/**
	 * 发货时间及数量（itemsenddate），货物起运日期
	 */
	public java.lang.String getItemsenddate() {
		return getStr("itemsenddate");
	}
	
	/**
	 * 0正常，-1删除
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 0正常，-1删除
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 通知编号
	 */
	public void setNoticeid(java.lang.String noticeid) {
		set("noticeid", noticeid);
	}
	
	/**
	 * 通知编号
	 */
	public java.lang.String getNoticeid() {
		return getStr("noticeid");
	}
	
	/**
	 * 通知名称
	 */
	public void setNoticename(java.lang.String noticename) {
		set("noticename", noticename);
	}
	
	/**
	 * 通知名称
	 */
	public java.lang.String getNoticename() {
		return getStr("noticename");
	}
	
	/**
	 * 通知状态，10录入-20确认-30审核
	 */
	public void setNoticestatus(java.lang.String noticestatus) {
		set("noticestatus", noticestatus);
	}
	
	/**
	 * 通知状态，10录入-20确认-30审核
	 */
	public java.lang.String getNoticestatus() {
		return getStr("noticestatus");
	}
	
	/**
	 * 通知图纸编号
	 */
	public void setNoticedrawno(java.lang.String noticedrawno) {
		set("noticedrawno", noticedrawno);
	}
	
	/**
	 * 通知图纸编号
	 */
	public java.lang.String getNoticedrawno() {
		return getStr("noticedrawno");
	}
	
	/**
	 * 预留字段通知本条数据备注
	 */
	public void setNoticememo(java.lang.String noticememo) {
		set("noticememo", noticememo);
	}
	
	/**
	 * 预留字段通知本条数据备注
	 */
	public java.lang.String getNoticememo() {
		return getStr("noticememo");
	}
	
	/**
	 * 通知校验者
	 */
	public void setNoticedeliver(java.lang.String noticedeliver) {
		set("noticedeliver", noticedeliver);
	}
	
	/**
	 * 通知校验者
	 */
	public java.lang.String getNoticedeliver() {
		return getStr("noticedeliver");
	}
	
	/**
	 * 通知作者
	 */
	public void setNoticeauther(java.lang.String noticeauther) {
		set("noticeauther", noticeauther);
	}
	
	/**
	 * 通知作者
	 */
	public java.lang.String getNoticeauther() {
		return getStr("noticeauther");
	}
	
	/**
	 * 通知备注
	 */
	public void setNoticecomment(java.lang.String noticecomment) {
		set("noticecomment", noticecomment);
	}
	
	/**
	 * 通知备注
	 */
	public java.lang.String getNoticecomment() {
		return getStr("noticecomment");
	}
	
	/**
	 * 通知制定日期
	 */
	public void setNoticebuilddate(java.util.Date noticebuilddate) {
		set("noticebuilddate", noticebuilddate);
	}
	
	/**
	 * 通知制定日期
	 */
	public java.util.Date getNoticebuilddate() {
		return getDate("noticebuilddate");
	}
	
	/**
	 * 通知期间
	 */
	public void setNoticeterm(java.math.BigDecimal noticeterm) {
		set("noticeterm", noticeterm);
	}
	
	/**
	 * 通知期间
	 */
	public java.math.BigDecimal getNoticeterm() {
		return get("noticeterm");
	}
	
	/**
	 * 通知规则
	 */
	public void setNoticerule(java.lang.String noticerule) {
		set("noticerule", noticerule);
	}
	
	/**
	 * 通知规则
	 */
	public java.lang.String getNoticerule() {
		return getStr("noticerule");
	}
	
	/**
	 * 通知修改内容
	 */
	public void setNoticemodify(java.lang.String noticemodify) {
		set("noticemodify", noticemodify);
	}
	
	/**
	 * 通知修改内容
	 */
	public java.lang.String getNoticemodify() {
		return getStr("noticemodify");
	}
	
	/**
	 * 通知替代型号
	 */
	public void setNoticeinstead(java.lang.String noticeinstead) {
		set("noticeinstead", noticeinstead);
	}
	
	/**
	 * 通知替代型号
	 */
	public java.lang.String getNoticeinstead() {
		return getStr("noticeinstead");
	}
	
	public void setTuoyun(java.lang.String tuoyun) {
		set("tuoyun", tuoyun);
	}
	
	public java.lang.String getTuoyun() {
		return getStr("tuoyun");
	}
	
	/**
	 * 修改后的通知装填，现在没用上
	 */
	public void setUpdatenotice(java.math.BigDecimal updatenotice) {
		set("updatenotice", updatenotice);
	}
	
	/**
	 * 修改后的通知装填，现在没用上
	 */
	public java.math.BigDecimal getUpdatenotice() {
		return get("updatenotice");
	}
	
	/**
	 * 通知审核者
	 */
	public void setNoticeshenhe(java.lang.String noticeshenhe) {
		set("noticeshenhe", noticeshenhe);
	}
	
	/**
	 * 通知审核者
	 */
	public java.lang.String getNoticeshenhe() {
		return getStr("noticeshenhe");
	}
	
}

