package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBasContractMaterial<M extends BaseBasContractMaterial<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 物料ID，关联basitem表
	 */
	public void setItemId(java.lang.Integer itemId) {
		set("itemId", itemId);
	}
	
	/**
	 * 物料ID，关联basitem表
	 */
	public java.lang.Integer getItemId() {
		return getInt("itemId");
	}
	
	/**
	 * 计划数量--自动生成
	 */
	public void setPlanQuantity(java.math.BigDecimal planQuantity) {
		set("planQuantity", planQuantity);
	}
	
	/**
	 * 计划数量--自动生成
	 */
	public java.math.BigDecimal getPlanQuantity() {
		return get("planQuantity");
	}
	
	/**
	 * 评库数量-中心库做
	 */
	public void setStoreQuantity(java.math.BigDecimal storeQuantity) {
		set("storeQuantity", storeQuantity);
	}
	
	/**
	 * 评库数量-中心库做
	 */
	public java.math.BigDecimal getStoreQuantity() {
		return get("storeQuantity");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 备料单生成人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 备料单生成人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 实际采购数量--采购人填
	 */
	public void setActualQuantity(java.math.BigDecimal actualQuantity) {
		set("actualQuantity", actualQuantity);
	}
	
	/**
	 * 实际采购数量--采购人填
	 */
	public java.math.BigDecimal getActualQuantity() {
		return get("actualQuantity");
	}
	
	/**
	 * 关联采购单号--采购人制定采购单后选择了就关联上
	 */
	public void setPuchaseOrderNo(java.lang.String puchaseOrderNo) {
		set("puchaseOrderNo", puchaseOrderNo);
	}
	
	/**
	 * 关联采购单号--采购人制定采购单后选择了就关联上
	 */
	public java.lang.String getPuchaseOrderNo() {
		return getStr("puchaseOrderNo");
	}
	
	/**
	 * 执行标准--采购人制定
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 执行标准--采购人制定
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 材质--采购人制定
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质--采购人制定
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 关联合同产品名称--自动生成
	 */
	public void setContractItemNames(java.lang.String contractItemNames) {
		set("contractItemNames", contractItemNames);
	}
	
	/**
	 * 关联合同产品名称--自动生成
	 */
	public java.lang.String getContractItemNames() {
		return getStr("contractItemNames");
	}
	
	/**
	 * 关联合同产品Id，在basitem表里面的id--自动生成
	 */
	public void setContractItemIds(java.lang.String contractItemIds) {
		set("contractItemIds", contractItemIds);
	}
	
	/**
	 * 关联合同产品Id，在basitem表里面的id--自动生成
	 */
	public java.lang.String getContractItemIds() {
		return getStr("contractItemIds");
	}
	
}

