package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlSchedulePlan<M extends BasePlSchedulePlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 供应商名称
	 */
	public void setSupplierName(java.lang.String supplierName) {
		set("supplierName", supplierName);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getSupplierName() {
		return getStr("supplierName");
	}
	
	/**
	 * 采购订单行项目ID
	 */
	public void setPoItemId(java.lang.Long poItemId) {
		set("poItemId", poItemId);
	}
	
	/**
	 * 采购订单行项目ID
	 */
	public java.lang.Long getPoItemId() {
		return getLong("poItemId");
	}
	
	/**
	 * 排产计划编码
	 */
	public void setScheduleCode(java.lang.String scheduleCode) {
		set("scheduleCode", scheduleCode);
	}
	
	/**
	 * 排产计划编码
	 */
	public java.lang.String getScheduleCode() {
		return getStr("scheduleCode");
	}
	
	/**
	 * 省公司单位编码
	 */
	public void setProvCoCode(java.lang.String provCoCode) {
		set("provCoCode", provCoCode);
	}
	
	/**
	 * 省公司单位编码
	 */
	public java.lang.String getProvCoCode() {
		return getStr("provCoCode");
	}
	
	/**
	 * 省公司单位名称
	 */
	public void setProvCoName(java.lang.String provCoName) {
		set("provCoName", provCoName);
	}
	
	/**
	 * 省公司单位名称
	 */
	public java.lang.String getProvCoName() {
		return getStr("provCoName");
	}
	
	/**
	 * 计划工期（天数）
	 */
	public void setPlanPeriod(java.lang.String planPeriod) {
		set("planPeriod", planPeriod);
	}
	
	/**
	 * 计划工期（天数）
	 */
	public java.lang.String getPlanPeriod() {
		return getStr("planPeriod");
	}
	
	/**
	 * 实际工期
	 */
	public void setActualPeriod(java.lang.String actualPeriod) {
		set("actualPeriod", actualPeriod);
	}
	
	/**
	 * 实际工期
	 */
	public java.lang.String getActualPeriod() {
		return getStr("actualPeriod");
	}
	
	/**
	 * 进度
	 */
	public void setSchedule(java.lang.String schedule) {
		set("schedule", schedule);
	}
	
	/**
	 * 进度
	 */
	public java.lang.String getSchedule() {
		return getStr("schedule");
	}
	
	/**
	 * 交付日期（最后日期，底线）
	 */
	public void setDueDate(java.util.Date dueDate) {
		set("dueDate", dueDate);
	}
	
	/**
	 * 交付日期（最后日期，底线）
	 */
	public java.util.Date getDueDate() {
		return getDate("dueDate");
	}
	
	/**
	 * 计划开始日期
	 */
	public void setPlanStartDate(java.util.Date planStartDate) {
		set("planStartDate", planStartDate);
	}
	
	/**
	 * 计划开始日期
	 */
	public java.util.Date getPlanStartDate() {
		return getDate("planStartDate");
	}
	
	/**
	 * 计划完成日期
	 */
	public void setPlanFinishDate(java.util.Date planFinishDate) {
		set("planFinishDate", planFinishDate);
	}
	
	/**
	 * 计划完成日期
	 */
	public java.util.Date getPlanFinishDate() {
		return getDate("planFinishDate");
	}
	
	/**
	 * 实际开始日期
	 */
	public void setActualStartDate(java.util.Date actualStartDate) {
		set("actualStartDate", actualStartDate);
	}
	
	/**
	 * 实际开始日期
	 */
	public java.util.Date getActualStartDate() {
		return getDate("actualStartDate");
	}
	
	/**
	 * 实际完成日期
	 */
	public void setActualFinishDate(java.util.Date actualFinishDate) {
		set("actualFinishDate", actualFinishDate);
	}
	
	/**
	 * 实际完成日期
	 */
	public java.util.Date getActualFinishDate() {
		return getDate("actualFinishDate");
	}
	
	/**
	 * 品类编码
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 数据来源
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 数据拥有方
	 */
	public void setOwnerId(java.lang.String ownerId) {
		set("ownerId", ownerId);
	}
	
	/**
	 * 数据拥有方
	 */
	public java.lang.String getOwnerId() {
		return getStr("ownerId");
	}
	
	/**
	 * 数据可见方
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 数据可见方
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}
	
	/**
	 * 记录创建时间
	 */
	public void setCreatedTime(java.util.Date createdTime) {
		set("createdTime", createdTime);
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getCreatedTime() {
		return getDate("createdTime");
	}
	
	/**
	 * 记录更新时间
	 */
	public void setUpdatedTime(java.util.Date updatedTime) {
		set("updatedTime", updatedTime);
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getUpdatedTime() {
		return getDate("updatedTime");
	}
	
	/**
	 * 状态：10录入，20确认,30已完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态：10录入，20确认,30已完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 作者
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 作者
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 产品名称
	 */
	public void setItemName(java.lang.String itemName) {
		set("itemName", itemName);
	}
	
	/**
	 * 产品名称
	 */
	public java.lang.String getItemName() {
		return getStr("itemName");
	}
	
}

