package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlbeiliaojihua<M extends BasePlbeiliaojihua<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractno(java.lang.String contractno) {
		set("contractno", contractno);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractno() {
		return getStr("contractno");
	}
	
	/**
	 * 工程名称
	 */
	public void setContractname(java.lang.String contractname) {
		set("contractname", contractname);
	}
	
	/**
	 * 工程名称
	 */
	public java.lang.String getContractname() {
		return getStr("contractname");
	}
	
	/**
	 * 通知编号
	 */
	public void setNoticeid(java.lang.String noticeid) {
		set("noticeid", noticeid);
	}
	
	/**
	 * 通知编号
	 */
	public java.lang.String getNoticeid() {
		return getStr("noticeid");
	}
	
	/**
	 * 物料编码
	 */
	public void setItemno(java.lang.String itemno) {
		set("itemno", itemno);
	}
	
	/**
	 * 物料编码
	 */
	public java.lang.String getItemno() {
		return getStr("itemno");
	}
	
	/**
	 * 图纸编号
	 */
	public void setNoticedrawno(java.lang.String noticedrawno) {
		set("noticedrawno", noticedrawno);
	}
	
	/**
	 * 图纸编号
	 */
	public java.lang.String getNoticedrawno() {
		return getStr("noticedrawno");
	}
	
	/**
	 * 代用型号
	 */
	public void setDaiyongxinghao(java.lang.String daiyongxinghao) {
		set("daiyongxinghao", daiyongxinghao);
	}
	
	/**
	 * 代用型号
	 */
	public java.lang.String getDaiyongxinghao() {
		return getStr("daiyongxinghao");
	}
	
	/**
	 * 制定部门
	 */
	public void setZhidingbumen(java.lang.String zhidingbumen) {
		set("zhidingbumen", zhidingbumen);
	}
	
	/**
	 * 制定部门
	 */
	public java.lang.String getZhidingbumen() {
		return getStr("zhidingbumen");
	}
	
	/**
	 * 制定日期
	 */
	public void setZhidingriqi(java.lang.String zhidingriqi) {
		set("zhidingriqi", zhidingriqi);
	}
	
	/**
	 * 制定日期
	 */
	public java.lang.String getZhidingriqi() {
		return getStr("zhidingriqi");
	}
	
	/**
	 * 订货套数
	 */
	public void setDinghuotaoshu(java.lang.String dinghuotaoshu) {
		set("dinghuotaoshu", dinghuotaoshu);
	}
	
	/**
	 * 订货套数
	 */
	public java.lang.String getDinghuotaoshu() {
		return getStr("dinghuotaoshu");
	}
	
	/**
	 * 所需材料编码
	 */
	public void setSxclitemno(java.lang.String sxclitemno) {
		set("sxclitemno", sxclitemno);
	}
	
	/**
	 * 所需材料编码
	 */
	public java.lang.String getSxclitemno() {
		return getStr("sxclitemno");
	}
	
	/**
	 * 所需材料名称
	 */
	public void setSxclitemname(java.lang.String sxclitemname) {
		set("sxclitemname", sxclitemname);
	}
	
	/**
	 * 所需材料名称
	 */
	public java.lang.String getSxclitemname() {
		return getStr("sxclitemname");
	}
	
	/**
	 * 所需材料数量
	 */
	public void setSxclshuliang(java.lang.String sxclshuliang) {
		set("sxclshuliang", sxclshuliang);
	}
	
	/**
	 * 所需材料数量
	 */
	public java.lang.String getSxclshuliang() {
		return getStr("sxclshuliang");
	}
	
	/**
	 * 所需材料单位
	 */
	public void setSxcldanwei(java.lang.String sxcldanwei) {
		set("sxcldanwei", sxcldanwei);
	}
	
	/**
	 * 所需材料单位
	 */
	public java.lang.String getSxcldanwei() {
		return getStr("sxcldanwei");
	}
	
	/**
	 * 所需材料数量
	 */
	public void setSxcltihuoshuliang(java.lang.String sxcltihuoshuliang) {
		set("sxcltihuoshuliang", sxcltihuoshuliang);
	}
	
	/**
	 * 所需材料数量
	 */
	public java.lang.String getSxcltihuoshuliang() {
		return getStr("sxcltihuoshuliang");
	}
	
	/**
	 * 所需材料材质
	 */
	public void setSxclcaizhi(java.lang.String sxclcaizhi) {
		set("sxclcaizhi", sxclcaizhi);
	}
	
	/**
	 * 所需材料材质
	 */
	public java.lang.String getSxclcaizhi() {
		return getStr("sxclcaizhi");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 编制人
	 */
	public void setBianzhiren(java.lang.String bianzhiren) {
		set("bianzhiren", bianzhiren);
	}
	
	/**
	 * 编制人
	 */
	public java.lang.String getBianzhiren() {
		return getStr("bianzhiren");
	}
	
	/**
	 * 提料时间
	 */
	public void setTiliaoshijian(java.lang.String tiliaoshijian) {
		set("tiliaoshijian", tiliaoshijian);
	}
	
	/**
	 * 提料时间
	 */
	public java.lang.String getTiliaoshijian() {
		return getStr("tiliaoshijian");
	}
	
	/**
	 * 交货时间
	 */
	public void setJiaohuoshijian(java.lang.String jiaohuoshijian) {
		set("jiaohuoshijian", jiaohuoshijian);
	}
	
	/**
	 * 交货时间
	 */
	public java.lang.String getJiaohuoshijian() {
		return getStr("jiaohuoshijian");
	}
	
	/**
	 * 所需材料实际数量
	 */
	public void setSxclshijishuliang(java.lang.String sxclshijishuliang) {
		set("sxclshijishuliang", sxclshijishuliang);
	}
	
	/**
	 * 所需材料实际数量
	 */
	public java.lang.String getSxclshijishuliang() {
		return getStr("sxclshijishuliang");
	}
	
	/**
	 * 销售产品itemid
	 */
	public void setXiaoshouitemid(java.lang.Integer xiaoshouitemid) {
		set("xiaoshouitemid", xiaoshouitemid);
	}
	
	/**
	 * 销售产品itemid
	 */
	public java.lang.Integer getXiaoshouitemid() {
		return getInt("xiaoshouitemid");
	}
	
	/**
	 * 所需备件itemid
	 */
	public void setSxclitemid(java.lang.Integer sxclitemid) {
		set("sxclitemid", sxclitemid);
	}
	
	/**
	 * 所需备件itemid
	 */
	public java.lang.Integer getSxclitemid() {
		return getInt("sxclitemid");
	}
	
	/**
	 * 校验人
	 */
	public void setJiaoyanren(java.lang.String jiaoyanren) {
		set("jiaoyanren", jiaoyanren);
	}
	
	/**
	 * 校验人
	 */
	public java.lang.String getJiaoyanren() {
		return getStr("jiaoyanren");
	}
	
	/**
	 * 审核人
	 */
	public void setShenheren(java.lang.String shenheren) {
		set("shenheren", shenheren);
	}
	
	/**
	 * 审核人
	 */
	public java.lang.String getShenheren() {
		return getStr("shenheren");
	}
	
	/**
	 * 预留字段
	 */
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	/**
	 * 预留字段
	 */
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	/**
	 * 预留字段
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
}

