package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClXj<M extends BaseClXj<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 自增主键
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 检验单号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 检验单号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 供应商编码
	 */
	public void setMafactoryno(java.lang.String mafactoryno) {
		set("mafactoryno", mafactoryno);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getMafactoryno() {
		return getStr("mafactoryno");
	}
	
	/**
	 * 供应商名称
	 */
	public void setMafactoryname(java.lang.String mafactoryname) {
		set("mafactoryname", mafactoryname);
	}
	
	/**
	 * 供应商名称
	 */
	public java.lang.String getMafactoryname() {
		return getStr("mafactoryname");
	}
	
	/**
	 * 检验日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 检验日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 材料名称
	 */
	public void setMatname(java.lang.String matname) {
		set("matname", matname);
	}
	
	/**
	 * 材料名称
	 */
	public java.lang.String getMatname() {
		return getStr("matname");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 规格
	 */
	public void setMattype(java.lang.String mattype) {
		set("mattype", mattype);
	}
	
	/**
	 * 规格
	 */
	public java.lang.String getMattype() {
		return getStr("mattype");
	}
	
	/**
	 * 试验编号
	 */
	public void setTestno(java.lang.String testno) {
		set("testno", testno);
	}
	
	/**
	 * 试验编号
	 */
	public java.lang.String getTestno() {
		return getStr("testno");
	}
	
	/**
	 * 来料数量
	 */
	public void setQuantity(java.math.BigDecimal quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 来料数量
	 */
	public java.math.BigDecimal getQuantity() {
		return get("quantity");
	}
	
	/**
	 * 抽检数量
	 */
	public void setSampleQuantity(java.lang.String sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 抽检数量
	 */
	public java.lang.String getSampleQuantity() {
		return getStr("sampleQuantity");
	}
	
	/**
	 * 使用单位
	 */
	public void setMatdepartment(java.lang.String matdepartment) {
		set("matdepartment", matdepartment);
	}
	
	/**
	 * 使用单位
	 */
	public java.lang.String getMatdepartment() {
		return getStr("matdepartment");
	}
	
	/**
	 * 来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 执行标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 执行标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeavefactoryDate(java.util.Date leavefactoryDate) {
		set("leavefactoryDate", leavefactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeavefactoryDate() {
		return getDate("leavefactoryDate");
	}
	
	/**
	 * 外形检测说明
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外形检测说明
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 外形检测结果
	 */
	public void setAppearanceResult(java.lang.String appearanceResult) {
		set("appearanceResult", appearanceResult);
	}
	
	/**
	 * 外形检测结果
	 */
	public java.lang.String getAppearanceResult() {
		return getStr("appearanceResult");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 长测量值 1
	 */
	public void setMatlongsize1(java.math.BigDecimal matlongsize1) {
		set("matlongsize1", matlongsize1);
	}
	
	/**
	 * 长测量值 1
	 */
	public java.math.BigDecimal getMatlongsize1() {
		return get("matlongsize1");
	}
	
	/**
	 * 长测量值 2
	 */
	public void setMatlongsize2(java.math.BigDecimal matlongsize2) {
		set("matlongsize2", matlongsize2);
	}
	
	/**
	 * 长测量值 2
	 */
	public java.math.BigDecimal getMatlongsize2() {
		return get("matlongsize2");
	}
	
	/**
	 * 长测量值 3
	 */
	public void setMatlongsize3(java.math.BigDecimal matlongsize3) {
		set("matlongsize3", matlongsize3);
	}
	
	/**
	 * 长测量值 3
	 */
	public java.math.BigDecimal getMatlongsize3() {
		return get("matlongsize3");
	}
	
	/**
	 * 长测量值 4
	 */
	public void setMatlongsize4(java.math.BigDecimal matlongsize4) {
		set("matlongsize4", matlongsize4);
	}
	
	/**
	 * 长测量值 4
	 */
	public java.math.BigDecimal getMatlongsize4() {
		return get("matlongsize4");
	}
	
	/**
	 * 长测量值 5
	 */
	public void setMatlongsize5(java.math.BigDecimal matlongsize5) {
		set("matlongsize5", matlongsize5);
	}
	
	/**
	 * 长测量值 5
	 */
	public java.math.BigDecimal getMatlongsize5() {
		return get("matlongsize5");
	}
	
	/**
	 * 长度检测结果
	 */
	public void setMatlongresult(java.lang.String matlongresult) {
		set("matlongresult", matlongresult);
	}
	
	/**
	 * 长度检测结果
	 */
	public java.lang.String getMatlongresult() {
		return getStr("matlongresult");
	}
	
	/**
	 * 宽测量值 1
	 */
	public void setMatlenghsize1(java.math.BigDecimal matlenghsize1) {
		set("matlenghsize1", matlenghsize1);
	}
	
	/**
	 * 宽测量值 1
	 */
	public java.math.BigDecimal getMatlenghsize1() {
		return get("matlenghsize1");
	}
	
	/**
	 * 宽测量值 2
	 */
	public void setMatlenghsize2(java.math.BigDecimal matlenghsize2) {
		set("matlenghsize2", matlenghsize2);
	}
	
	/**
	 * 宽测量值 2
	 */
	public java.math.BigDecimal getMatlenghsize2() {
		return get("matlenghsize2");
	}
	
	/**
	 * 宽测量值 3
	 */
	public void setMatlenghsize3(java.math.BigDecimal matlenghsize3) {
		set("matlenghsize3", matlenghsize3);
	}
	
	/**
	 * 宽测量值 3
	 */
	public java.math.BigDecimal getMatlenghsize3() {
		return get("matlenghsize3");
	}
	
	/**
	 * 宽测量值 4
	 */
	public void setMatlenghsize4(java.math.BigDecimal matlenghsize4) {
		set("matlenghsize4", matlenghsize4);
	}
	
	/**
	 * 宽测量值 4
	 */
	public java.math.BigDecimal getMatlenghsize4() {
		return get("matlenghsize4");
	}
	
	/**
	 * 宽测量值 5
	 */
	public void setMatlenghsize5(java.math.BigDecimal matlenghsize5) {
		set("matlenghsize5", matlenghsize5);
	}
	
	/**
	 * 宽测量值 5
	 */
	public java.math.BigDecimal getMatlenghsize5() {
		return get("matlenghsize5");
	}
	
	/**
	 * 宽检测结果
	 */
	public void setMatlenghresult(java.lang.String matlenghresult) {
		set("matlenghresult", matlenghresult);
	}
	
	/**
	 * 宽检测结果
	 */
	public java.lang.String getMatlenghresult() {
		return getStr("matlenghresult");
	}
	
	/**
	 * 线径测量值 1
	 */
	public void setMatxianjing1(java.math.BigDecimal matxianjing1) {
		set("matxianjing1", matxianjing1);
	}
	
	/**
	 * 线径测量值 1
	 */
	public java.math.BigDecimal getMatxianjing1() {
		return get("matxianjing1");
	}
	
	/**
	 * 线径测量值 2
	 */
	public void setMatxianjing2(java.math.BigDecimal matxianjing2) {
		set("matxianjing2", matxianjing2);
	}
	
	/**
	 * 线径测量值 2
	 */
	public java.math.BigDecimal getMatxianjing2() {
		return get("matxianjing2");
	}
	
	/**
	 * 线径测量值 3
	 */
	public void setMatxianjing3(java.math.BigDecimal matxianjing3) {
		set("matxianjing3", matxianjing3);
	}
	
	/**
	 * 线径测量值 3
	 */
	public java.math.BigDecimal getMatxianjing3() {
		return get("matxianjing3");
	}
	
	/**
	 * 线径测量值 4
	 */
	public void setMatxianjing4(java.math.BigDecimal matxianjing4) {
		set("matxianjing4", matxianjing4);
	}
	
	/**
	 * 线径测量值 4
	 */
	public java.math.BigDecimal getMatxianjing4() {
		return get("matxianjing4");
	}
	
	/**
	 * 线径测量值 5
	 */
	public void setMatxianjing5(java.math.BigDecimal matxianjing5) {
		set("matxianjing5", matxianjing5);
	}
	
	/**
	 * 线径测量值 5
	 */
	public java.math.BigDecimal getMatxianjing5() {
		return get("matxianjing5");
	}
	
	/**
	 * 线径检测结果
	 */
	public void setMatxianjingresult(java.lang.String matxianjingresult) {
		set("matxianjingresult", matxianjingresult);
	}
	
	/**
	 * 线径检测结果
	 */
	public java.lang.String getMatxianjingresult() {
		return getStr("matxianjingresult");
	}
	
	/**
	 * 厚度测量值 1
	 */
	public void setMatheightsize1(java.math.BigDecimal matheightsize1) {
		set("matheightsize1", matheightsize1);
	}
	
	/**
	 * 厚度测量值 1
	 */
	public java.math.BigDecimal getMatheightsize1() {
		return get("matheightsize1");
	}
	
	/**
	 * 厚度测量值 2
	 */
	public void setMatheightsize2(java.math.BigDecimal matheightsize2) {
		set("matheightsize2", matheightsize2);
	}
	
	/**
	 * 厚度测量值 2
	 */
	public java.math.BigDecimal getMatheightsize2() {
		return get("matheightsize2");
	}
	
	/**
	 * 厚度测量值 3
	 */
	public void setMatheightsize3(java.math.BigDecimal matheightsize3) {
		set("matheightsize3", matheightsize3);
	}
	
	/**
	 * 厚度测量值 3
	 */
	public java.math.BigDecimal getMatheightsize3() {
		return get("matheightsize3");
	}
	
	/**
	 * 厚度测量值 4
	 */
	public void setMatheightsize4(java.math.BigDecimal matheightsize4) {
		set("matheightsize4", matheightsize4);
	}
	
	/**
	 * 厚度测量值 4
	 */
	public java.math.BigDecimal getMatheightsize4() {
		return get("matheightsize4");
	}
	
	/**
	 * 厚度测量值 5
	 */
	public void setMatheightsize5(java.math.BigDecimal matheightsize5) {
		set("matheightsize5", matheightsize5);
	}
	
	/**
	 * 厚度测量值 5
	 */
	public java.math.BigDecimal getMatheightsize5() {
		return get("matheightsize5");
	}
	
	/**
	 * 厚度检测结果
	 */
	public void setMatheightsizeresult(java.lang.String matheightsizeresult) {
		set("matheightsizeresult", matheightsizeresult);
	}
	
	/**
	 * 厚度检测结果
	 */
	public java.lang.String getMatheightsizeresult() {
		return getStr("matheightsizeresult");
	}
	
	/**
	 * 柱经测量值 1
	 */
	public void setMatzhujingsize1(java.math.BigDecimal matzhujingsize1) {
		set("matzhujingsize1", matzhujingsize1);
	}
	
	/**
	 * 柱经测量值 1
	 */
	public java.math.BigDecimal getMatzhujingsize1() {
		return get("matzhujingsize1");
	}
	
	/**
	 * 柱经测量值 2
	 */
	public void setMatzhujingsize2(java.math.BigDecimal matzhujingsize2) {
		set("matzhujingsize2", matzhujingsize2);
	}
	
	/**
	 * 柱经测量值 2
	 */
	public java.math.BigDecimal getMatzhujingsize2() {
		return get("matzhujingsize2");
	}
	
	/**
	 * 柱经测量值 3
	 */
	public void setMatzhujingsize3(java.math.BigDecimal matzhujingsize3) {
		set("matzhujingsize3", matzhujingsize3);
	}
	
	/**
	 * 柱经测量值 3
	 */
	public java.math.BigDecimal getMatzhujingsize3() {
		return get("matzhujingsize3");
	}
	
	/**
	 * 柱经测量值 4
	 */
	public void setMatzhujingsize4(java.math.BigDecimal matzhujingsize4) {
		set("matzhujingsize4", matzhujingsize4);
	}
	
	/**
	 * 柱经测量值 4
	 */
	public java.math.BigDecimal getMatzhujingsize4() {
		return get("matzhujingsize4");
	}
	
	/**
	 * 柱经测量值 5
	 */
	public void setMatzhujingsize5(java.math.BigDecimal matzhujingsize5) {
		set("matzhujingsize5", matzhujingsize5);
	}
	
	/**
	 * 柱经测量值 5
	 */
	public java.math.BigDecimal getMatzhujingsize5() {
		return get("matzhujingsize5");
	}
	
	/**
	 * 柱高检测结果
	 */
	public void setMatzhujingsizeresult(java.lang.String matzhujingsizeresult) {
		set("matzhujingsizeresult", matzhujingsizeresult);
	}
	
	/**
	 * 柱高检测结果
	 */
	public java.lang.String getMatzhujingsizeresult() {
		return getStr("matzhujingsizeresult");
	}
	
	/**
	 * 柱高测量值 1
	 */
	public void setMatzhugaosize1(java.math.BigDecimal matzhugaosize1) {
		set("matzhugaosize1", matzhugaosize1);
	}
	
	/**
	 * 柱高测量值 1
	 */
	public java.math.BigDecimal getMatzhugaosize1() {
		return get("matzhugaosize1");
	}
	
	/**
	 * 柱高测量值 2
	 */
	public void setMatzhugaosize2(java.math.BigDecimal matzhugaosize2) {
		set("matzhugaosize2", matzhugaosize2);
	}
	
	/**
	 * 柱高测量值 2
	 */
	public java.math.BigDecimal getMatzhugaosize2() {
		return get("matzhugaosize2");
	}
	
	/**
	 * 柱高测量值 3
	 */
	public void setMatzhugaosize3(java.math.BigDecimal matzhugaosize3) {
		set("matzhugaosize3", matzhugaosize3);
	}
	
	/**
	 * 柱高测量值 3
	 */
	public java.math.BigDecimal getMatzhugaosize3() {
		return get("matzhugaosize3");
	}
	
	/**
	 * 柱高测量值 4
	 */
	public void setMatzhugaosize4(java.math.BigDecimal matzhugaosize4) {
		set("matzhugaosize4", matzhugaosize4);
	}
	
	/**
	 * 柱高测量值 4
	 */
	public java.math.BigDecimal getMatzhugaosize4() {
		return get("matzhugaosize4");
	}
	
	/**
	 * 柱高测量值 5
	 */
	public void setMatzhugaosize5(java.math.BigDecimal matzhugaosize5) {
		set("matzhugaosize5", matzhugaosize5);
	}
	
	/**
	 * 柱高测量值 5
	 */
	public java.math.BigDecimal getMatzhugaosize5() {
		return get("matzhugaosize5");
	}
	
	/**
	 * 柱高检测结果
	 */
	public void setMatzhugaosizeresult(java.lang.String matzhugaosizeresult) {
		set("matzhugaosizeresult", matzhugaosizeresult);
	}
	
	/**
	 * 柱高检测结果
	 */
	public java.lang.String getMatzhugaosizeresult() {
		return getStr("matzhugaosizeresult");
	}
	
	/**
	 * 硬度（邵儿）67-73
	 */
	public void setMatjixiexingnengvalue(java.math.BigDecimal matjixiexingnengvalue) {
		set("matjixiexingnengvalue", matjixiexingnengvalue);
	}
	
	/**
	 * 硬度（邵儿）67-73
	 */
	public java.math.BigDecimal getMatjixiexingnengvalue() {
		return get("matjixiexingnengvalue");
	}
	
	/**
	 * 硬度检测结果
	 */
	public void setMatjixiexingnengresult(java.lang.String matjixiexingnengresult) {
		set("matjixiexingnengresult", matjixiexingnengresult);
	}
	
	/**
	 * 硬度检测结果
	 */
	public java.lang.String getMatjixiexingnengresult() {
		return getStr("matjixiexingnengresult");
	}
	
	/**
	 * 录入时间，自动生成
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 录入时间，自动生成
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasno(java.lang.String basno) {
		set("basno", basno);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasno() {
		return getStr("basno");
	}
	
	/**
	 * 录入人-登录用户
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人-登录用户
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 审核人
	 */
	public void setAuditor(java.lang.String auditor) {
		set("auditor", auditor);
	}
	
	/**
	 * 审核人
	 */
	public java.lang.String getAuditor() {
		return getStr("auditor");
	}
	
	/**
	 * 检验人
	 */
	public void setChecker(java.lang.String checker) {
		set("checker", checker);
	}
	
	/**
	 * 检验人
	 */
	public java.lang.String getChecker() {
		return getStr("checker");
	}
	
	/**
	 * 长度标准值
	 */
	public void setMatlongsizebiaozhun(java.math.BigDecimal matlongsizebiaozhun) {
		set("matlongsizebiaozhun", matlongsizebiaozhun);
	}
	
	/**
	 * 长度标准值
	 */
	public java.math.BigDecimal getMatlongsizebiaozhun() {
		return get("matlongsizebiaozhun");
	}
	
	/**
	 * 宽度标准值
	 */
	public void setMatlenghsizebiaozhun(java.math.BigDecimal matlenghsizebiaozhun) {
		set("matlenghsizebiaozhun", matlenghsizebiaozhun);
	}
	
	/**
	 * 宽度标准值
	 */
	public java.math.BigDecimal getMatlenghsizebiaozhun() {
		return get("matlenghsizebiaozhun");
	}
	
	/**
	 * 线径标准值
	 */
	public void setMatxianjingbiaozhun(java.math.BigDecimal matxianjingbiaozhun) {
		set("matxianjingbiaozhun", matxianjingbiaozhun);
	}
	
	/**
	 * 线径标准值
	 */
	public java.math.BigDecimal getMatxianjingbiaozhun() {
		return get("matxianjingbiaozhun");
	}
	
	/**
	 * 厚度标准值
	 */
	public void setMatheightsizebiaozhun(java.math.BigDecimal matheightsizebiaozhun) {
		set("matheightsizebiaozhun", matheightsizebiaozhun);
	}
	
	/**
	 * 厚度标准值
	 */
	public java.math.BigDecimal getMatheightsizebiaozhun() {
		return get("matheightsizebiaozhun");
	}
	
	/**
	 * 柱径标准值
	 */
	public void setMatzhujingsizebiaozhun(java.math.BigDecimal matzhujingsizebiaozhun) {
		set("matzhujingsizebiaozhun", matzhujingsizebiaozhun);
	}
	
	/**
	 * 柱径标准值
	 */
	public java.math.BigDecimal getMatzhujingsizebiaozhun() {
		return get("matzhujingsizebiaozhun");
	}
	
	/**
	 * 柱高标准值
	 */
	public void setMatzhugaosizebiaozhun(java.math.BigDecimal matzhugaosizebiaozhun) {
		set("matzhugaosizebiaozhun", matzhugaosizebiaozhun);
	}
	
	/**
	 * 柱高标准值
	 */
	public java.math.BigDecimal getMatzhugaosizebiaozhun() {
		return get("matzhugaosizebiaozhun");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractno(java.lang.String contractno) {
		set("contractno", contractno);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractno() {
		return getStr("contractno");
	}
	
	/**
	 * 实际单价
	 */
	public void setShijidanjia(java.math.BigDecimal shijidanjia) {
		set("shijidanjia", shijidanjia);
	}
	
	/**
	 * 实际单价
	 */
	public java.math.BigDecimal getShijidanjia() {
		return get("shijidanjia");
	}
	
	/**
	 * 实际总价
	 */
	public void setShijiamount(java.math.BigDecimal shijiamount) {
		set("shijiamount", shijiamount);
	}
	
	/**
	 * 实际总价
	 */
	public java.math.BigDecimal getShijiamount() {
		return get("shijiamount");
	}
	
	/**
	 * 单重
	 */
	public void setDanzhong(java.math.BigDecimal danzhong) {
		set("danzhong", danzhong);
	}
	
	/**
	 * 单重
	 */
	public java.math.BigDecimal getDanzhong() {
		return get("danzhong");
	}
	
	/**
	 * 总重
	 */
	public void setZongzhong(java.math.BigDecimal zongzhong) {
		set("zongzhong", zongzhong);
	}
	
	/**
	 * 总重
	 */
	public java.math.BigDecimal getZongzhong() {
		return get("zongzhong");
	}
	
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
}

