package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlFinishInoutList<M extends BasePlFinishInoutList<M>> extends Model<M> implements IBean {

	/**
	 * 明细主键（通用）
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 明细主键（通用）
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 关联检验单据号（通用）
	 */
	public void setInspOrderNo(java.lang.String inspOrderNo) {
		set("inspOrderNo", inspOrderNo);
	}
	
	/**
	 * 关联检验单据号（通用）
	 */
	public java.lang.String getInspOrderNo() {
		return getStr("inspOrderNo");
	}
	
	/**
	 * 操作仓库（通用）
	 */
	public void setWarehouse(java.lang.String warehouse) {
		set("warehouse", warehouse);
	}
	
	/**
	 * 操作仓库（通用）
	 */
	public java.lang.String getWarehouse() {
		return getStr("warehouse");
	}
	
	/**
	 * 关联合同编号（通用）
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 关联合同编号（通用）
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 关联合同名称（通用）
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 关联合同名称（通用）
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货单位 （入库用）
	 */
	public void setDeliveryUnit(java.lang.String deliveryUnit) {
		set("deliveryUnit", deliveryUnit);
	}
	
	/**
	 * 送货单位 （入库用）
	 */
	public java.lang.String getDeliveryUnit() {
		return getStr("deliveryUnit");
	}
	
	/**
	 * 物料编号（通用）
	 */
	public void setItemCode(java.lang.String itemCode) {
		set("itemCode", itemCode);
	}
	
	/**
	 * 物料编号（通用）
	 */
	public java.lang.String getItemCode() {
		return getStr("itemCode");
	}
	
	/**
	 * 物料名称（通用）
	 */
	public void setItemName(java.lang.String itemName) {
		set("itemName", itemName);
	}
	
	/**
	 * 物料名称（通用）
	 */
	public java.lang.String getItemName() {
		return getStr("itemName");
	}
	
	/**
	 * 规格型号（通用）
	 */
	public void setItemSpec(java.lang.String itemSpec) {
		set("itemSpec", itemSpec);
	}
	
	/**
	 * 规格型号（通用）
	 */
	public java.lang.String getItemSpec() {
		return getStr("itemSpec");
	}
	
	/**
	 * 计量单位（通用）
	 */
	public void setItemUnit(java.lang.String itemUnit) {
		set("itemUnit", itemUnit);
	}
	
	/**
	 * 计量单位（通用）
	 */
	public java.lang.String getItemUnit() {
		return getStr("itemUnit");
	}
	
	/**
	 * 数量（入库正数，出库负数
	 */
	public void setActualQuantity(java.math.BigDecimal actualQuantity) {
		set("actualQuantity", actualQuantity);
	}
	
	/**
	 * 数量（入库正数，出库负数
	 */
	public java.math.BigDecimal getActualQuantity() {
		return get("actualQuantity");
	}
	
	/**
	 * 实际重量（入库正数，出库负数）
	 */
	public void setActualWeight(java.math.BigDecimal actualWeight) {
		set("actualWeight", actualWeight);
	}
	
	/**
	 * 实际重量（入库正数，出库负数）
	 */
	public java.math.BigDecimal getActualWeight() {
		return get("actualWeight");
	}
	
	/**
	 * 物料类别（通用）
	 */
	public void setInclass(java.lang.String inclass) {
		set("inclass", inclass);
	}
	
	/**
	 * 物料类别（通用）
	 */
	public java.lang.String getInclass() {
		return getStr("inclass");
	}
	
	/**
	 * 单价
	 */
	public void setPrice(java.math.BigDecimal price) {
		set("price", price);
	}
	
	/**
	 * 单价
	 */
	public java.math.BigDecimal getPrice() {
		return get("price");
	}
	
	/**
	 * 金额
	 */
	public void setTotalPrice(java.math.BigDecimal totalPrice) {
		set("totalPrice", totalPrice);
	}
	
	/**
	 * 金额
	 */
	public java.math.BigDecimal getTotalPrice() {
		return get("totalPrice");
	}
	
	/**
	 * 明细备注（通用）
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 明细备注（通用）
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 入库时间（通用）
	 */
	public void setOperateTime(java.util.Date operateTime) {
		set("operateTime", operateTime);
	}
	
	/**
	 * 入库时间（通用）
	 */
	public java.util.Date getOperateTime() {
		return getDate("operateTime");
	}
	
	/**
	 * 明细状态（通用）
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 明细状态（通用）
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 盘点类型（通用）
	 */
	public void setInventoryCheckType(java.lang.Integer inventoryCheckType) {
		set("inventoryCheckType", inventoryCheckType);
	}
	
	/**
	 * 盘点类型（通用）
	 */
	public java.lang.Integer getInventoryCheckType() {
		return getInt("inventoryCheckType");
	}
	
	/**
	 * 出入库类型1入库，2出库
	 */
	public void setType(java.lang.Byte type) {
		set("type", type);
	}
	
	/**
	 * 出入库类型1入库，2出库
	 */
	public java.lang.Byte getType() {
		return getByte("type");
	}
	
	/**
	 * 录入人
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 期间
	 */
	public void setTerm(java.lang.String term) {
		set("term", term);
	}
	
	/**
	 * 期间
	 */
	public java.lang.String getTerm() {
		return getStr("term");
	}
	
	/**
	 * 重量单位
	 */
	public void setWeightUnit(java.lang.String weightUnit) {
		set("weightUnit", weightUnit);
	}
	
	/**
	 * 重量单位
	 */
	public java.lang.String getWeightUnit() {
		return getStr("weightUnit");
	}
	
	/**
	 * 生产工单号
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 生产工单号
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
}

