package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlMaterialRequestDetail<M extends BasePlMaterialRequestDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 领料单ID（关联主表）
	 */
	public void setRequestId(java.lang.Long requestId) {
		set("requestId", requestId);
	}
	
	/**
	 * 领料单ID（关联主表）
	 */
	public java.lang.Long getRequestId() {
		return getLong("requestId");
	}
	
	/**
	 * 物料ID
	 */
	public void setMaterialId(java.lang.Long materialId) {
		set("materialId", materialId);
	}
	
	/**
	 * 物料ID
	 */
	public java.lang.Long getMaterialId() {
		return getLong("materialId");
	}
	
	/**
	 * 申请数量
	 */
	public void setRequestQty(java.math.BigDecimal requestQty) {
		set("requestQty", requestQty);
	}
	
	/**
	 * 申请数量
	 */
	public java.math.BigDecimal getRequestQty() {
		return get("requestQty");
	}
	
	/**
	 * 批准数量（库管员审核后填写，暂时没用）
	 */
	public void setApprovedQty(java.math.BigDecimal approvedQty) {
		set("approvedQty", approvedQty);
	}
	
	/**
	 * 批准数量（库管员审核后填写，暂时没用）
	 */
	public java.math.BigDecimal getApprovedQty() {
		return get("approvedQty");
	}
	
	/**
	 * 实际领取数量
	 */
	public void setActualQty(java.math.BigDecimal actualQty) {
		set("actualQty", actualQty);
	}
	
	/**
	 * 实际领取数量
	 */
	public java.math.BigDecimal getActualQty() {
		return get("actualQty");
	}
	
	/**
	 * 明细状态（0-待审核，1-已审核，2-已全部领取，3-部分领取，4-已拒绝）
	 */
	public void setDetailStatus(java.lang.Integer detailStatus) {
		set("detailStatus", detailStatus);
	}
	
	/**
	 * 明细状态（0-待审核，1-已审核，2-已全部领取，3-部分领取，4-已拒绝）
	 */
	public java.lang.Integer getDetailStatus() {
		return getInt("detailStatus");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
	/**
	 * 已使用的数量
	 */
	public void setUsedQty(java.math.BigDecimal usedQty) {
		set("usedQty", usedQty);
	}
	
	/**
	 * 已使用的数量
	 */
	public java.math.BigDecimal getUsedQty() {
		return get("usedQty");
	}
	
}

