package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClWfg<M extends BaseClWfg<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库单号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库单号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分分析-C
	 */
	public void setChemC(java.math.BigDecimal chemC) {
		set("chemC", chemC);
	}
	
	/**
	 * 化学成分分析-C
	 */
	public java.math.BigDecimal getChemC() {
		return get("chemC");
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分分析-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分分析-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分分析-P
	 */
	public void setChemP(java.math.BigDecimal chemP) {
		set("chemP", chemP);
	}
	
	/**
	 * 化学成分分析-P
	 */
	public java.math.BigDecimal getChemP() {
		return get("chemP");
	}
	
	/**
	 * 化学成分分析-S
	 */
	public void setChemS(java.math.BigDecimal chemS) {
		set("chemS", chemS);
	}
	
	/**
	 * 化学成分分析-S
	 */
	public java.math.BigDecimal getChemS() {
		return get("chemS");
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public void setChemCr(java.math.BigDecimal chemCr) {
		set("chemCr", chemCr);
	}
	
	/**
	 * 化学成分分析-Cr
	 */
	public java.math.BigDecimal getChemCr() {
		return get("chemCr");
	}
	
	/**
	 * 化学成分分析-Ni
	 */
	public void setChemNi(java.math.BigDecimal chemNi) {
		set("chemNi", chemNi);
	}
	
	/**
	 * 化学成分分析-Ni
	 */
	public java.math.BigDecimal getChemNi() {
		return get("chemNi");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeavefactoryDate(java.util.Date leavefactoryDate) {
		set("leavefactoryDate", leavefactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeavefactoryDate() {
		return getDate("leavefactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 录入人-登录用户
	 */
	public void setWriter(java.lang.String writer) {
		set("writer", writer);
	}
	
	/**
	 * 录入人-登录用户
	 */
	public java.lang.String getWriter() {
		return getStr("writer");
	}
	
	/**
	 * 录入时间，自动生成
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 录入时间，自动生成
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasno(java.lang.String basno) {
		set("basno", basno);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasno() {
		return getStr("basno");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 数量
	 */
	public void setQuantity(java.lang.String quantity) {
		set("quantity", quantity);
	}
	
	/**
	 * 数量
	 */
	public java.lang.String getQuantity() {
		return getStr("quantity");
	}
	
	/**
	 * 抽检数量
	 */
	public void setSampleQuantity(java.lang.String sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 抽检数量
	 */
	public java.lang.String getSampleQuantity() {
		return getStr("sampleQuantity");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 审核人
	 */
	public void setAuditor(java.lang.String auditor) {
		set("auditor", auditor);
	}
	
	/**
	 * 审核人
	 */
	public java.lang.String getAuditor() {
		return getStr("auditor");
	}
	
	/**
	 * 检验人
	 */
	public void setChecker(java.lang.String checker) {
		set("checker", checker);
	}
	
	/**
	 * 检验人
	 */
	public java.lang.String getChecker() {
		return getStr("checker");
	}
	
	/**
	 * 抗拉强度
	 */
	public void setTensileStrength(java.lang.String tensileStrength) {
		set("tensileStrength", tensileStrength);
	}
	
	/**
	 * 抗拉强度
	 */
	public java.lang.String getTensileStrength() {
		return getStr("tensileStrength");
	}
	
	/**
	 * 屈服强度
	 */
	public void setYieldStrength(java.lang.String yieldStrength) {
		set("yieldStrength", yieldStrength);
	}
	
	/**
	 * 屈服强度
	 */
	public java.lang.String getYieldStrength() {
		return getStr("yieldStrength");
	}
	
	/**
	 * 延伸率
	 */
	public void setElongation(java.lang.String elongation) {
		set("elongation", elongation);
	}
	
	/**
	 * 延伸率
	 */
	public java.lang.String getElongation() {
		return getStr("elongation");
	}
	
	/**
	 * 冲击测试1#
	 */
	public void setImpact1(java.lang.String impact1) {
		set("impact1", impact1);
	}
	
	/**
	 * 冲击测试1#
	 */
	public java.lang.String getImpact1() {
		return getStr("impact1");
	}
	
	/**
	 * 冲击测试2#
	 */
	public void setImpact2(java.lang.String impact2) {
		set("impact2", impact2);
	}
	
	/**
	 * 冲击测试2#
	 */
	public java.lang.String getImpact2() {
		return getStr("impact2");
	}
	
	/**
	 * 冲击测试3#
	 */
	public void setImpact3(java.lang.String impact3) {
		set("impact3", impact3);
	}
	
	/**
	 * 冲击测试3#
	 */
	public java.lang.String getImpact3() {
		return getStr("impact3");
	}
	
}

