package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlSupplyOrder<M extends BasePlSupplyOrder<M>> extends Model<M> implements IBean {

	/**
	 * 自增主键，唯一标识一条供货单请求记录
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 自增主键，唯一标识一条供货单请求记录
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码，长度12位，必填项
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码，长度12位，必填项
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 采购方公司编码，内部或外部系统编码，长度48位，可选项
	 */
	public void setPurchaseCode(java.lang.String purchaseCode) {
		set("purchaseCode", purchaseCode);
	}
	
	/**
	 * 采购方公司编码，内部或外部系统编码，长度48位，可选项
	 */
	public java.lang.String getPurchaseCode() {
		return getStr("purchaseCode");
	}
	
	/**
	 * 供应商编码，长度48位，必填项
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码，长度48位，必填项
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 合同类型，整数类型，必填项
	 */
	public void setConType(java.lang.Integer conType) {
		set("conType", conType);
	}
	
	/**
	 * 合同类型，整数类型，必填项
	 */
	public java.lang.Integer getConType() {
		return getInt("conType");
	}
	
	/**
	 * 采购供货单序号，唯一标识本次供货单，长度48位，必填项
	 */
	public void setSupplyNo(java.lang.String supplyNo) {
		set("supplyNo", supplyNo);
	}
	
	/**
	 * 采购供货单序号，唯一标识本次供货单，长度48位，必填项
	 */
	public java.lang.String getSupplyNo() {
		return getStr("supplyNo");
	}
	
	/**
	 * 合同序号，关联对应采购合同，长度48位，必填项
	 */
	public void setConCode(java.lang.String conCode) {
		set("conCode", conCode);
	}
	
	/**
	 * 合同序号，关联对应采购合同，长度48位，必填项
	 */
	public java.lang.String getConCode() {
		return getStr("conCode");
	}
	
	/**
	 * 工程项目名称，描述供货所归属的项目，最大长度100字符，可选项
	 */
	public void setPrjName(java.lang.String prjName) {
		set("prjName", prjName);
	}
	
	/**
	 * 工程项目名称，描述供货所归属的项目，最大长度100字符，可选项
	 */
	public java.lang.String getPrjName() {
		return getStr("prjName");
	}
	
	/**
	 * 合同名称，便于业务识别，最大长度200字符，可选项
	 */
	public void setConName(java.lang.String conName) {
		set("conName", conName);
	}
	
	/**
	 * 合同名称，便于业务识别，最大长度200字符，可选项
	 */
	public java.lang.String getConName() {
		return getStr("conName");
	}
	
	/**
	 * 合同签订日期，格式如YYYY-MM-DD HH:MM:SS，长度30位，可选项
	 */
	public void setSellerSignTime(java.lang.String sellerSignTime) {
		set("sellerSignTime", sellerSignTime);
	}
	
	/**
	 * 合同签订日期，格式如YYYY-MM-DD HH:MM:SS，长度30位，可选项
	 */
	public java.lang.String getSellerSignTime() {
		return getStr("sellerSignTime");
	}
	
	/**
	 * 货物名称，表示本次供货的具体货物名称，最大长度100字符，必填项
	 */
	public void setCargoName(java.lang.String cargoName) {
		set("cargoName", cargoName);
	}
	
	/**
	 * 货物名称，表示本次供货的具体货物名称，最大长度100字符，必填项
	 */
	public java.lang.String getCargoName() {
		return getStr("cargoName");
	}
	
	/**
	 * 品类编码，标准化分类编码，长度10位，必填项
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码，标准化分类编码，长度10位，必填项
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码，更细粒度的分类编码，长度100位，必填项
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码，更细粒度的分类编码，长度100位，必填项
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 采购方公司名称，完整名称，最大长度1000字符，必填项
	 */
	public void setPurchaseName(java.lang.String purchaseName) {
		set("purchaseName", purchaseName);
	}
	
	/**
	 * 采购方公司名称，完整名称，最大长度1000字符，必填项
	 */
	public java.lang.String getPurchaseName() {
		return getStr("purchaseName");
	}
	
	/**
	 * 供货单项目号，对应采购订单行项目编号，长度48位，必填项
	 */
	public void setPoItemNo(java.lang.String poItemNo) {
		set("poItemNo", poItemNo);
	}
	
	/**
	 * 供货单项目号，对应采购订单行项目编号，长度48位，必填项
	 */
	public java.lang.String getPoItemNo() {
		return getStr("poItemNo");
	}
	
	/**
	 * 收货方公司名称，实际接收货物的公司全称，最大长度255字符，必填项
	 */
	public void setReceivedName(java.lang.String receivedName) {
		set("receivedName", receivedName);
	}
	
	/**
	 * 收货方公司名称，实际接收货物的公司全称，最大长度255字符，必填项
	 */
	public java.lang.String getReceivedName() {
		return getStr("receivedName");
	}
	
	/**
	 * 供应商侧物料编码，供应商内部使用的物料编号，长度48位，必填项
	 */
	public void setMaterialCode(java.lang.String materialCode) {
		set("materialCode", materialCode);
	}
	
	/**
	 * 供应商侧物料编码，供应商内部使用的物料编号，长度48位，必填项
	 */
	public java.lang.String getMaterialCode() {
		return getStr("materialCode");
	}
	
	/**
	 * 供应商侧物料描述，详细说明物料规格、型号等信息，最大长度1000字符，必填项
	 */
	public void setMaterialDesc(java.lang.String materialDesc) {
		set("materialDesc", materialDesc);
	}
	
	/**
	 * 供应商侧物料描述，详细说明物料规格、型号等信息，最大长度1000字符，必填项
	 */
	public java.lang.String getMaterialDesc() {
		return getStr("materialDesc");
	}
	
	/**
	 * 采购数量，以字符串形式存储，支持大数值或高精度，最大长度1000字符，必填项
	 */
	public void setAmount(java.lang.String amount) {
		set("amount", amount);
	}
	
	/**
	 * 采购数量，以字符串形式存储，支持大数值或高精度，最大长度1000字符，必填项
	 */
	public java.lang.String getAmount() {
		return getStr("amount");
	}
	
	/**
	 * 计量单位，如"个"、"kg"、"米"等，长度48位，必填项
	 */
	public void setMeasUnit(java.lang.String measUnit) {
		set("measUnit", measUnit);
	}
	
	/**
	 * 计量单位，如"个"、"kg"、"米"等，长度48位，必填项
	 */
	public java.lang.String getMeasUnit() {
		return getStr("measUnit");
	}
	
	/**
	 * 数据来源系统标识，用于追踪数据源头，长度48位，必填项
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源系统标识，用于追踪数据源头，长度48位，必填项
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源系统创建该数据的时间戳，格式如YYYY-MM-DD HH:MM:SS，长度30位，必填项
	 */
	public void setDataSourceCreateTime(java.lang.String dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源系统创建该数据的时间戳，格式如YYYY-MM-DD HH:MM:SS，长度30位，必填项
	 */
	public java.lang.String getDataSourceCreateTime() {
		return getStr("dataSourceCreateTime");
	}
	
	/**
	 * 备注信息，可填写额外说明或异常标注，最大长度1000字符，可选项
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注信息，可填写额外说明或异常标注，最大长度1000字符，可选项
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 卖方合同序号，由供应商提供的合同编号，长度48位，可选项
	 */
	public void setSellerConCode(java.lang.String sellerConCode) {
		set("sellerConCode", sellerConCode);
	}
	
	/**
	 * 卖方合同序号，由供应商提供的合同编号，长度48位，可选项
	 */
	public java.lang.String getSellerConCode() {
		return getStr("sellerConCode");
	}
	
	/**
	 * 物资大类序号，用于分类管理，长度48位，可选项
	 */
	public void setMatMaxCode(java.lang.String matMaxCode) {
		set("matMaxCode", matMaxCode);
	}
	
	/**
	 * 物资大类序号，用于分类管理，长度48位，可选项
	 */
	public java.lang.String getMatMaxCode() {
		return getStr("matMaxCode");
	}
	
	/**
	 * 物资中类序号，用于分类管理，长度48位，可选项
	 */
	public void setMatMedCode(java.lang.String matMedCode) {
		set("matMedCode", matMedCode);
	}
	
	/**
	 * 物资中类序号，用于分类管理，长度48位，可选项
	 */
	public java.lang.String getMatMedCode() {
		return getStr("matMedCode");
	}
	
	/**
	 * 物资小类序号，用于分类管理，长度48位，可选项
	 */
	public void setMatMinCode(java.lang.String matMinCode) {
		set("matMinCode", matMinCode);
	}
	
	/**
	 * 物资小类序号，用于分类管理，长度48位，可选项
	 */
	public java.lang.String getMatMinCode() {
		return getStr("matMinCode");
	}
	
	/**
	 * 物资大类名称，便于展示和查询，最大长度128字符，可选项
	 */
	public void setMatMaxName(java.lang.String matMaxName) {
		set("matMaxName", matMaxName);
	}
	
	/**
	 * 物资大类名称，便于展示和查询，最大长度128字符，可选项
	 */
	public java.lang.String getMatMaxName() {
		return getStr("matMaxName");
	}
	
	/**
	 * 物资中类名称，便于展示和查询，最大长度128字符，可选项
	 */
	public void setMatMedName(java.lang.String matMedName) {
		set("matMedName", matMedName);
	}
	
	/**
	 * 物资中类名称，便于展示和查询，最大长度128字符，可选项
	 */
	public java.lang.String getMatMedName() {
		return getStr("matMedName");
	}
	
	/**
	 * 物资小类名称，便于展示和查询，最大长度128字符，可选项
	 */
	public void setMatMinName(java.lang.String matMinName) {
		set("matMinName", matMinName);
	}
	
	/**
	 * 物资小类名称，便于展示和查询，最大长度128字符，可选项
	 */
	public java.lang.String getMatMinName() {
		return getStr("matMinName");
	}
	
}

