package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysmenu<M extends BaseSysmenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	public java.lang.String getPath() {
		return getStr("path");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}
	
	public java.lang.String getIcon() {
		return getStr("icon");
	}
	
	public void setParentid(java.lang.Integer parentid) {
		set("parentid", parentid);
	}
	
	public java.lang.Integer getParentid() {
		return getInt("parentid");
	}
	
	public void setComponent(java.lang.String component) {
		set("component", component);
	}
	
	public java.lang.String getComponent() {
		return getStr("component");
	}
	
	public void setLayout(java.lang.String layout) {
		set("layout", layout);
	}
	
	public java.lang.String getLayout() {
		return getStr("layout");
	}
	
}

