package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClDxgjx<M extends BaseClDxgjx<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号，来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号，来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库编号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库编号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeaveFactoryDate(java.util.Date leaveFactoryDate) {
		set("leaveFactoryDate", leaveFactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeaveFactoryDate() {
		return getDate("leaveFactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.lang.String detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.lang.String getDetectionTime() {
		return getStr("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasNo(java.lang.String basNo) {
		set("basNo", basNo);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasNo() {
		return getStr("basNo");
	}
	
	/**
	 * 抽检数量总
	 */
	public void setSampleQuantity(java.math.BigDecimal sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 抽检数量总
	 */
	public java.math.BigDecimal getSampleQuantity() {
		return get("sampleQuantity");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸结论（合格/不合格）
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸结论（合格/不合格）
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 力学性能检验抽检数量
	 */
	public void setMechlnspQty(java.math.BigDecimal mechlnspQty) {
		set("mechlnspQty", mechlnspQty);
	}
	
	/**
	 * 力学性能检验抽检数量
	 */
	public java.math.BigDecimal getMechlnspQty() {
		return get("mechlnspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 单丝强度实测值第一组
	 */
	public void setMonoStrengthA(java.math.BigDecimal monoStrengthA) {
		set("monoStrengthA", monoStrengthA);
	}
	
	/**
	 * 单丝强度实测值第一组
	 */
	public java.math.BigDecimal getMonoStrengthA() {
		return get("monoStrengthA");
	}
	
	/**
	 * 单丝强度要求值
	 */
	public void setMonoStrengthRequired(java.math.BigDecimal monoStrengthRequired) {
		set("monoStrengthRequired", monoStrengthRequired);
	}
	
	/**
	 * 单丝强度要求值
	 */
	public java.math.BigDecimal getMonoStrengthRequired() {
		return get("monoStrengthRequired");
	}
	
	/**
	 * 破断拉力总和实测值第一组
	 */
	public void setBreakingForceA(java.math.BigDecimal breakingForceA) {
		set("breakingForceA", breakingForceA);
	}
	
	/**
	 * 破断拉力总和实测值第一组
	 */
	public java.math.BigDecimal getBreakingForceA() {
		return get("breakingForceA");
	}
	
	/**
	 * 破断拉力总和要求值
	 */
	public void setBreakingForceRequired(java.math.BigDecimal breakingForceRequired) {
		set("breakingForceRequired", breakingForceRequired);
	}
	
	/**
	 * 破断拉力总和要求值
	 */
	public java.math.BigDecimal getBreakingForceRequired() {
		return get("breakingForceRequired");
	}
	
	/**
	 * 单丝强度实测值第二组
	 */
	public void setMonoStrengthB(java.math.BigDecimal monoStrengthB) {
		set("monoStrengthB", monoStrengthB);
	}
	
	/**
	 * 单丝强度实测值第二组
	 */
	public java.math.BigDecimal getMonoStrengthB() {
		return get("monoStrengthB");
	}
	
	/**
	 * 单丝强度实测值第三组
	 */
	public void setMonoStrengthC(java.math.BigDecimal monoStrengthC) {
		set("monoStrengthC", monoStrengthC);
	}
	
	/**
	 * 单丝强度实测值第三组
	 */
	public java.math.BigDecimal getMonoStrengthC() {
		return get("monoStrengthC");
	}
	
	/**
	 * 破断拉力总和实测值第二组
	 */
	public void setBreakingForceB(java.math.BigDecimal breakingForceB) {
		set("breakingForceB", breakingForceB);
	}
	
	/**
	 * 破断拉力总和实测值第二组
	 */
	public java.math.BigDecimal getBreakingForceB() {
		return get("breakingForceB");
	}
	
	/**
	 * 破断拉力总和实测值第三组
	 */
	public void setBreakingForceC(java.math.BigDecimal breakingForceC) {
		set("breakingForceC", breakingForceC);
	}
	
	/**
	 * 破断拉力总和实测值第三组
	 */
	public java.math.BigDecimal getBreakingForceC() {
		return get("breakingForceC");
	}
	
}

