package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHruser<M extends BaseHruser<M>> extends Model<M> implements IBean {

	/**
	 * 人员顺序号
	 */
	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	/**
	 * 人员顺序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 人员编号
	 */
	public void setNo(java.lang.String no) {
		set("no", no);
	}
	
	/**
	 * 人员编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}
	
	/**
	 * 人员姓名
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	/**
	 * 人员姓名
	 */
	public java.lang.String getName() {
		return getStr("name");
	}
	
	/**
	 * 部门ID
	 */
	public void setDepartmentid(java.lang.Integer departmentid) {
		set("departmentid", departmentid);
	}
	
	/**
	 * 部门ID
	 */
	public java.lang.Integer getDepartmentid() {
		return getInt("departmentid");
	}
	
	/**
	 * 籍贯
	 */
	public void setNativeplace(java.lang.String nativeplace) {
		set("nativeplace", nativeplace);
	}
	
	/**
	 * 籍贯
	 */
	public java.lang.String getNativeplace() {
		return getStr("nativeplace");
	}
	
	/**
	 * 性别
	 */
	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}
	
	/**
	 * 性别
	 */
	public java.lang.String getSex() {
		return getStr("sex");
	}
	
	/**
	 * 年龄
	 */
	public void setAge(java.lang.Integer age) {
		set("age", age);
	}
	
	/**
	 * 年龄
	 */
	public java.lang.Integer getAge() {
		return getInt("age");
	}
	
	/**
	 * 学历
	 */
	public void setSchoolage(java.lang.String schoolage) {
		set("schoolage", schoolage);
	}
	
	/**
	 * 学历
	 */
	public java.lang.String getSchoolage() {
		return getStr("schoolage");
	}
	
	/**
	 * 专业
	 */
	public void setMajor(java.lang.String major) {
		set("major", major);
	}
	
	/**
	 * 专业
	 */
	public java.lang.String getMajor() {
		return getStr("major");
	}
	
	/**
	 * 毕业院校
	 */
	public void setGraduateschool(java.lang.String graduateschool) {
		set("graduateschool", graduateschool);
	}
	
	/**
	 * 毕业院校
	 */
	public java.lang.String getGraduateschool() {
		return getStr("graduateschool");
	}
	
	/**
	 * 家庭住址
	 */
	public void setFamilyaddress(java.lang.String familyaddress) {
		set("familyaddress", familyaddress);
	}
	
	/**
	 * 家庭住址
	 */
	public java.lang.String getFamilyaddress() {
		return getStr("familyaddress");
	}
	
	/**
	 * 民族
	 */
	public void setNation(java.lang.String nation) {
		set("nation", nation);
	}
	
	/**
	 * 民族
	 */
	public java.lang.String getNation() {
		return getStr("nation");
	}
	
	/**
	 * 出生日期
	 */
	public void setBirthdate(java.util.Date birthdate) {
		set("birthdate", birthdate);
	}
	
	/**
	 * 出生日期
	 */
	public java.util.Date getBirthdate() {
		return getDate("birthdate");
	}
	
	/**
	 * 工作状态 10表示在职 20表,退休,30表买断
	 */
	public void setWorkstatus(java.lang.Integer workstatus) {
		set("workstatus", workstatus);
	}
	
	/**
	 * 工作状态 10表示在职 20表,退休,30表买断
	 */
	public java.lang.Integer getWorkstatus() {
		return getInt("workstatus");
	}
	
	/**
	 * 政治面貌
	 */
	public void setPolity(java.lang.String polity) {
		set("polity", polity);
	}
	
	/**
	 * 政治面貌
	 */
	public java.lang.String getPolity() {
		return getStr("polity");
	}
	
	/**
	 * 开始工作时间
	 */
	public void setBeginworkdate(java.util.Date beginworkdate) {
		set("beginworkdate", beginworkdate);
	}
	
	/**
	 * 开始工作时间
	 */
	public java.util.Date getBeginworkdate() {
		return getDate("beginworkdate");
	}
	
	/**
	 * 电话
	 */
	public void setPhone1(java.lang.String phone1) {
		set("phone1", phone1);
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getPhone1() {
		return getStr("phone1");
	}
	
	/**
	 * 电话
	 */
	public void setPhone2(java.lang.String phone2) {
		set("phone2", phone2);
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getPhone2() {
		return getStr("phone2");
	}
	
	/**
	 * 电话
	 */
	public void setPhone3(java.lang.String phone3) {
		set("phone3", phone3);
	}
	
	/**
	 * 电话
	 */
	public java.lang.String getPhone3() {
		return getStr("phone3");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}
	
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 退休日期
	 */
	public void setEndworkdate(java.util.Date endworkdate) {
		set("endworkdate", endworkdate);
	}
	
	/**
	 * 退休日期
	 */
	public java.util.Date getEndworkdate() {
		return getDate("endworkdate");
	}
	
	/**
	 * 职务
	 */
	public void setDuty(java.lang.String duty) {
		set("duty", duty);
	}
	
	/**
	 * 职务
	 */
	public java.lang.String getDuty() {
		return getStr("duty");
	}
	
	/**
	 * 身份证号
	 */
	public void setIdcardno(java.lang.String idcardno) {
		set("idcardno", idcardno);
	}
	
	/**
	 * 身份证号
	 */
	public java.lang.String getIdcardno() {
		return getStr("idcardno");
	}
	
	public void setFlag(java.lang.Integer flag) {
		set("flag", flag);
	}
	
	public java.lang.Integer getFlag() {
		return getInt("flag");
	}
	
	public void setDescription(java.lang.String description) {
		set("description", description);
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}
	
	/**
	 * 曾用名
	 */
	public void setCyname(java.lang.String cyname) {
		set("cyname", cyname);
	}
	
	/**
	 * 曾用名
	 */
	public java.lang.String getCyname() {
		return getStr("cyname");
	}
	
	/**
	 * 部门名称
	 */
	public void setDepartment(java.lang.String department) {
		set("department", department);
	}
	
	/**
	 * 部门名称
	 */
	public java.lang.String getDepartment() {
		return getStr("department");
	}
	
	/**
	 * 部门类别
	 */
	public void setDepartmentlb(java.lang.String departmentlb) {
		set("departmentlb", departmentlb);
	}
	
	/**
	 * 部门类别
	 */
	public java.lang.String getDepartmentlb() {
		return getStr("departmentlb");
	}
	
	/**
	 * 班组名称
	 */
	public void setBzmc(java.lang.String bzmc) {
		set("bzmc", bzmc);
	}
	
	/**
	 * 班组名称
	 */
	public java.lang.String getBzmc() {
		return getStr("bzmc");
	}
	
	/**
	 * 专业类别
	 */
	public void setMajorlb(java.lang.String majorlb) {
		set("majorlb", majorlb);
	}
	
	/**
	 * 专业类别
	 */
	public java.lang.String getMajorlb() {
		return getStr("majorlb");
	}
	
	/**
	 * 入学时间
	 */
	public void setRxsj(java.util.Date rxsj) {
		set("rxsj", rxsj);
	}
	
	/**
	 * 入学时间
	 */
	public java.util.Date getRxsj() {
		return getDate("rxsj");
	}
	
	/**
	 * 毕业时间
	 */
	public void setBysj(java.util.Date bysj) {
		set("bysj", bysj);
	}
	
	/**
	 * 毕业时间
	 */
	public java.util.Date getBysj() {
		return getDate("bysj");
	}
	
	/**
	 * 是否第一学历
	 */
	public void setSffxl(java.lang.String sffxl) {
		set("sffxl", sffxl);
	}
	
	/**
	 * 是否第一学历
	 */
	public java.lang.String getSffxl() {
		return getStr("sffxl");
	}
	
	/**
	 * 学位
	 */
	public void setDegree(java.lang.String degree) {
		set("degree", degree);
	}
	
	/**
	 * 学位
	 */
	public java.lang.String getDegree() {
		return getStr("degree");
	}
	
	/**
	 * 受教育年限
	 */
	public void setEducateyear(java.lang.String educateyear) {
		set("educateyear", educateyear);
	}
	
	/**
	 * 受教育年限
	 */
	public java.lang.String getEducateyear() {
		return getStr("educateyear");
	}
	
	/**
	 * 学习形式
	 */
	public void setLearningformat(java.lang.String learningformat) {
		set("learningformat", learningformat);
	}
	
	/**
	 * 学习形式
	 */
	public java.lang.String getLearningformat() {
		return getStr("learningformat");
	}
	
	/**
	 * 户口所在地
	 */
	public void setAccountaddress(java.lang.String accountaddress) {
		set("accountaddress", accountaddress);
	}
	
	/**
	 * 户口所在地
	 */
	public java.lang.String getAccountaddress() {
		return getStr("accountaddress");
	}
	
	/**
	 * 出生地
	 */
	public void setBirthaddress(java.lang.String birthaddress) {
		set("birthaddress", birthaddress);
	}
	
	/**
	 * 出生地
	 */
	public java.lang.String getBirthaddress() {
		return getStr("birthaddress");
	}
	
	/**
	 * 社区名称
	 */
	public void setCommunityname(java.lang.String communityname) {
		set("communityname", communityname);
	}
	
	/**
	 * 社区名称
	 */
	public java.lang.String getCommunityname() {
		return getStr("communityname");
	}
	
	/**
	 * 用工性质
	 */
	public void setYgxz(java.lang.String ygxz) {
		set("ygxz", ygxz);
	}
	
	/**
	 * 用工性质
	 */
	public java.lang.String getYgxz() {
		return getStr("ygxz");
	}
	
	/**
	 * 用工分类
	 */
	public void setYgfl(java.lang.String ygfl) {
		set("ygfl", ygfl);
	}
	
	/**
	 * 用工分类
	 */
	public java.lang.String getYgfl() {
		return getStr("ygfl");
	}
	
	/**
	 * 入党时间
	 */
	public void setRddate(java.util.Date rddate) {
		set("rddate", rddate);
	}
	
	/**
	 * 入党时间
	 */
	public java.util.Date getRddate() {
		return getDate("rddate");
	}
	
	/**
	 * 人员类别
	 */
	public void setRylb(java.lang.String rylb) {
		set("rylb", rylb);
	}
	
	/**
	 * 人员类别
	 */
	public java.lang.String getRylb() {
		return getStr("rylb");
	}
	
	/**
	 * 岗位名称
	 */
	public void setGwname(java.lang.String gwname) {
		set("gwname", gwname);
	}
	
	/**
	 * 岗位名称
	 */
	public java.lang.String getGwname() {
		return getStr("gwname");
	}
	
	/**
	 * 岗位分类
	 */
	public void setGwfl(java.lang.String gwfl) {
		set("gwfl", gwfl);
	}
	
	/**
	 * 岗位分类
	 */
	public java.lang.String getGwfl() {
		return getStr("gwfl");
	}
	
	/**
	 * 岗位工资等级
	 */
	public void setGwgzdj(java.lang.String gwgzdj) {
		set("gwgzdj", gwgzdj);
	}
	
	/**
	 * 岗位工资等级
	 */
	public java.lang.String getGwgzdj() {
		return getStr("gwgzdj");
	}
	
	/**
	 * 岗位工资
	 */
	public void setGwgz(java.math.BigDecimal gwgz) {
		set("gwgz", gwgz);
	}
	
	/**
	 * 岗位工资
	 */
	public java.math.BigDecimal getGwgz() {
		return get("gwgz");
	}
	
	/**
	 * 岗位工资调整时间
	 */
	public void setGwgztzsj(java.util.Date gwgztzsj) {
		set("gwgztzsj", gwgztzsj);
	}
	
	/**
	 * 岗位工资调整时间
	 */
	public java.util.Date getGwgztzsj() {
		return getDate("gwgztzsj");
	}
	
	/**
	 * 职务级别
	 */
	public void setZwjb(java.lang.String zwjb) {
		set("zwjb", zwjb);
	}
	
	/**
	 * 职务级别
	 */
	public java.lang.String getZwjb() {
		return getStr("zwjb");
	}
	
	/**
	 * 职务聘任时间
	 */
	public void setZwprsj(java.util.Date zwprsj) {
		set("zwprsj", zwprsj);
	}
	
	/**
	 * 职务聘任时间
	 */
	public java.util.Date getZwprsj() {
		return getDate("zwprsj");
	}
	
	/**
	 * 职务聘任终止时间
	 */
	public void setZwprzzsj(java.util.Date zwprzzsj) {
		set("zwprzzsj", zwprzzsj);
	}
	
	/**
	 * 职务聘任终止时间
	 */
	public java.util.Date getZwprzzsj() {
		return getDate("zwprzzsj");
	}
	
	/**
	 * 专业技术职务
	 */
	public void setZyjszw(java.lang.String zyjszw) {
		set("zyjszw", zyjszw);
	}
	
	/**
	 * 专业技术职务
	 */
	public java.lang.String getZyjszw() {
		return getStr("zyjszw");
	}
	
	/**
	 * 专业技术职务等级
	 */
	public void setZyjszwj(java.lang.String zyjszwj) {
		set("zyjszwj", zyjszwj);
	}
	
	/**
	 * 专业技术职务等级
	 */
	public java.lang.String getZyjszwj() {
		return getStr("zyjszwj");
	}
	
	/**
	 * 专业技术职务系列
	 */
	public void setZjjszwxl(java.lang.String zjjszwxl) {
		set("zjjszwxl", zjjszwxl);
	}
	
	/**
	 * 专业技术职务系列
	 */
	public java.lang.String getZjjszwxl() {
		return getStr("zjjszwxl");
	}
	
	/**
	 * 聘任标志
	 */
	public void setPrbz(java.lang.String prbz) {
		set("prbz", prbz);
	}
	
	/**
	 * 聘任标志
	 */
	public java.lang.String getPrbz() {
		return getStr("prbz");
	}
	
	/**
	 * 聘任时间
	 */
	public void setPrsj(java.util.Date prsj) {
		set("prsj", prsj);
	}
	
	/**
	 * 聘任时间
	 */
	public java.util.Date getPrsj() {
		return getDate("prsj");
	}
	
	/**
	 * 聘任终止时间
	 */
	public void setPrzjsj(java.util.Date przjsj) {
		set("przjsj", przjsj);
	}
	
	/**
	 * 聘任终止时间
	 */
	public java.util.Date getPrzjsj() {
		return getDate("przjsj");
	}
	
	/**
	 * 技能工资等级
	 */
	public void setJngzdj(java.lang.String jngzdj) {
		set("jngzdj", jngzdj);
	}
	
	/**
	 * 技能工资等级
	 */
	public java.lang.String getJngzdj() {
		return getStr("jngzdj");
	}
	
	/**
	 * 技能工资
	 */
	public void setJngz(java.math.BigDecimal jngz) {
		set("jngz", jngz);
	}
	
	/**
	 * 技能工资
	 */
	public java.math.BigDecimal getJngz() {
		return get("jngz");
	}
	
	/**
	 * 技能工资调整时间
	 */
	public void setJngztzsj(java.util.Date jngztzsj) {
		set("jngztzsj", jngztzsj);
	}
	
	/**
	 * 技能工资调整时间
	 */
	public java.util.Date getJngztzsj() {
		return getDate("jngztzsj");
	}
	
	/**
	 * 入本单位时间
	 */
	public void setRbdwsj(java.util.Date rbdwsj) {
		set("rbdwsj", rbdwsj);
	}
	
	/**
	 * 入本单位时间
	 */
	public java.util.Date getRbdwsj() {
		return getDate("rbdwsj");
	}
	
	/**
	 * 个人身份
	 */
	public void setGrsf(java.lang.String grsf) {
		set("grsf", grsf);
	}
	
	/**
	 * 个人身份
	 */
	public java.lang.String getGrsf() {
		return getStr("grsf");
	}
	
	/**
	 * 用工形式
	 */
	public void setYgxs(java.lang.String ygxs) {
		set("ygxs", ygxs);
	}
	
	/**
	 * 用工形式
	 */
	public java.lang.String getYgxs() {
		return getStr("ygxs");
	}
	
	/**
	 * 复原转业军人标识
	 */
	public void setFyzyjrbs(java.lang.String fyzyjrbs) {
		set("fyzyjrbs", fyzyjrbs);
	}
	
	/**
	 * 复原转业军人标识
	 */
	public java.lang.String getFyzyjrbs() {
		return getStr("fyzyjrbs");
	}
	
	/**
	 * 参军时间
	 */
	public void setCjsj(java.util.Date cjsj) {
		set("cjsj", cjsj);
	}
	
	/**
	 * 参军时间
	 */
	public java.util.Date getCjsj() {
		return getDate("cjsj");
	}
	
	/**
	 * 复原转业时间
	 */
	public void setFyzysj(java.util.Date fyzysj) {
		set("fyzysj", fyzysj);
	}
	
	/**
	 * 复原转业时间
	 */
	public java.util.Date getFyzysj() {
		return getDate("fyzysj");
	}
	
	/**
	 * 军队职务级别
	 */
	public void setJdzwjb(java.lang.String jdzwjb) {
		set("jdzwjb", jdzwjb);
	}
	
	/**
	 * 军队职务级别
	 */
	public java.lang.String getJdzwjb() {
		return getStr("jdzwjb");
	}
	
	/**
	 * 下乡时间
	 */
	public void setXxsj(java.util.Date xxsj) {
		set("xxsj", xxsj);
	}
	
	/**
	 * 下乡时间
	 */
	public java.util.Date getXxsj() {
		return getDate("xxsj");
	}
	
	/**
	 * 劳动合同编号
	 */
	public void setLdhtbh(java.lang.String ldhtbh) {
		set("ldhtbh", ldhtbh);
	}
	
	/**
	 * 劳动合同编号
	 */
	public java.lang.String getLdhtbh() {
		return getStr("ldhtbh");
	}
	
	/**
	 * 劳动合同期限类型
	 */
	public void setLdhtqxlx(java.lang.String ldhtqxlx) {
		set("ldhtqxlx", ldhtqxlx);
	}
	
	/**
	 * 劳动合同期限类型
	 */
	public java.lang.String getLdhtqxlx() {
		return getStr("ldhtqxlx");
	}
	
	/**
	 * 劳动合同起始时间
	 */
	public void setLdhtqssj(java.util.Date ldhtqssj) {
		set("ldhtqssj", ldhtqssj);
	}
	
	/**
	 * 劳动合同起始时间
	 */
	public java.util.Date getLdhtqssj() {
		return getDate("ldhtqssj");
	}
	
	/**
	 * 劳动合同终止时间
	 */
	public void setLdhtzzsj(java.util.Date ldhtzzsj) {
		set("ldhtzzsj", ldhtzzsj);
	}
	
	/**
	 * 劳动合同终止时间
	 */
	public java.util.Date getLdhtzzsj() {
		return getDate("ldhtzzsj");
	}
	
	/**
	 * 最初学历
	 */
	public void setZcxl(java.lang.String zcxl) {
		set("zcxl", zcxl);
	}
	
	/**
	 * 最初学历
	 */
	public java.lang.String getZcxl() {
		return getStr("zcxl");
	}
	
	/**
	 * 判断是否删除0正常，-1删除
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 判断是否删除0正常，-1删除
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
}

