package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClBxgls<M extends BaseClBxgls<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号？来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号？来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库编号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库编号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分实测值-C
	 */
	public void setChemC(java.math.BigDecimal chemC) {
		set("chemC", chemC);
	}
	
	/**
	 * 化学成分实测值-C
	 */
	public java.math.BigDecimal getChemC() {
		return get("chemC");
	}
	
	/**
	 * 化学成分实测值-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分实测值-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分实测值-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分实测值-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分实测值-Cr
	 */
	public void setChemCr(java.math.BigDecimal chemCr) {
		set("chemCr", chemCr);
	}
	
	/**
	 * 化学成分实测值-Cr
	 */
	public java.math.BigDecimal getChemCr() {
		return get("chemCr");
	}
	
	/**
	 * 化学成分实测值-Ni
	 */
	public void setChemNi(java.math.BigDecimal chemNi) {
		set("chemNi", chemNi);
	}
	
	/**
	 * 化学成分实测值-Ni
	 */
	public java.math.BigDecimal getChemNi() {
		return get("chemNi");
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public void setChemCRequired(java.math.BigDecimal chemCRequired) {
		set("chemCRequired", chemCRequired);
	}
	
	/**
	 * 化学成分要求值-C
	 */
	public java.math.BigDecimal getChemCRequired() {
		return get("chemCRequired");
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public void setChemSiRequired(java.math.BigDecimal chemSiRequired) {
		set("chemSiRequired", chemSiRequired);
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public java.math.BigDecimal getChemSiRequired() {
		return get("chemSiRequired");
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public void setChemMnRequired(java.math.BigDecimal chemMnRequired) {
		set("chemMnRequired", chemMnRequired);
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public java.math.BigDecimal getChemMnRequired() {
		return get("chemMnRequired");
	}
	
	/**
	 * 化学成分要求值-Cr
	 */
	public void setChemCrRequired(java.math.BigDecimal chemCrRequired) {
		set("chemCrRequired", chemCrRequired);
	}
	
	/**
	 * 化学成分要求值-Cr
	 */
	public java.math.BigDecimal getChemCrRequired() {
		return get("chemCrRequired");
	}
	
	/**
	 * 化学成分要求值-Ni
	 */
	public void setChemNiRequired(java.math.BigDecimal chemNiRequired) {
		set("chemNiRequired", chemNiRequired);
	}
	
	/**
	 * 化学成分要求值-Ni
	 */
	public java.math.BigDecimal getChemNiRequired() {
		return get("chemNiRequired");
	}
	
	/**
	 * 化学成分-规格
	 */
	public void setChemStandard(java.math.BigDecimal chemStandard) {
		set("chemStandard", chemStandard);
	}
	
	/**
	 * 化学成分-规格
	 */
	public java.math.BigDecimal getChemStandard() {
		return get("chemStandard");
	}
	
	/**
	 * 化学成分-炉号
	 */
	public void setChemBatchNo(java.math.BigDecimal chemBatchNo) {
		set("chemBatchNo", chemBatchNo);
	}
	
	/**
	 * 化学成分-炉号
	 */
	public java.math.BigDecimal getChemBatchNo() {
		return get("chemBatchNo");
	}
	
	/**
	 * 化学成分-批号
	 */
	public void setChemBatchNum(java.math.BigDecimal chemBatchNum) {
		set("chemBatchNum", chemBatchNum);
	}
	
	/**
	 * 化学成分-批号
	 */
	public java.math.BigDecimal getChemBatchNum() {
		return get("chemBatchNum");
	}
	
	/**
	 * 化学成分-判断结果
	 */
	public void setChemDeterminationResult(java.math.BigDecimal chemDeterminationResult) {
		set("chemDeterminationResult", chemDeterminationResult);
	}
	
	/**
	 * 化学成分-判断结果
	 */
	public java.math.BigDecimal getChemDeterminationResult() {
		return get("chemDeterminationResult");
	}
	
	/**
	 * 外形-规格
	 */
	public void setShapeStandard(java.math.BigDecimal shapeStandard) {
		set("shapeStandard", shapeStandard);
	}
	
	/**
	 * 外形-规格
	 */
	public java.math.BigDecimal getShapeStandard() {
		return get("shapeStandard");
	}
	
	/**
	 * 外形-不圆度
	 */
	public void setShapeOutOfRoundness(java.math.BigDecimal shapeOutOfRoundness) {
		set("shapeOutOfRoundness", shapeOutOfRoundness);
	}
	
	/**
	 * 外形-不圆度
	 */
	public java.math.BigDecimal getShapeOutOfRoundness() {
		return get("shapeOutOfRoundness");
	}
	
	/**
	 * 外形-判断结果
	 */
	public void setShapeDeterminationResult(java.math.BigDecimal shapeDeterminationResult) {
		set("shapeDeterminationResult", shapeDeterminationResult);
	}
	
	/**
	 * 外形-判断结果
	 */
	public java.math.BigDecimal getShapeDeterminationResult() {
		return get("shapeDeterminationResult");
	}
	
	/**
	 * 尺寸-规格
	 */
	public void setSizeStandard(java.math.BigDecimal sizeStandard) {
		set("sizeStandard", sizeStandard);
	}
	
	/**
	 * 尺寸-规格
	 */
	public java.math.BigDecimal getSizeStandard() {
		return get("sizeStandard");
	}
	
	/**
	 * 尺寸-实际测量1
	 */
	public void setSizeRequired1(java.math.BigDecimal sizeRequired1) {
		set("sizeRequired1", sizeRequired1);
	}
	
	/**
	 * 尺寸-实际测量1
	 */
	public java.math.BigDecimal getSizeRequired1() {
		return get("sizeRequired1");
	}
	
	/**
	 * 尺寸-实际测量2
	 */
	public void setSizeRequired2(java.math.BigDecimal sizeRequired2) {
		set("sizeRequired2", sizeRequired2);
	}
	
	/**
	 * 尺寸-实际测量2
	 */
	public java.math.BigDecimal getSizeRequired2() {
		return get("sizeRequired2");
	}
	
	/**
	 * 尺寸-实际测量3
	 */
	public void setSizeRequired3(java.math.BigDecimal sizeRequired3) {
		set("sizeRequired3", sizeRequired3);
	}
	
	/**
	 * 尺寸-实际测量3
	 */
	public java.math.BigDecimal getSizeRequired3() {
		return get("sizeRequired3");
	}
	
	/**
	 * 尺寸-平均值
	 */
	public void setSizeMean(java.math.BigDecimal sizeMean) {
		set("sizeMean", sizeMean);
	}
	
	/**
	 * 尺寸-平均值
	 */
	public java.math.BigDecimal getSizeMean() {
		return get("sizeMean");
	}
	
	/**
	 * 尺寸-判断结果
	 */
	public void setSizeDeterminationResult(java.math.BigDecimal sizeDeterminationResult) {
		set("sizeDeterminationResult", sizeDeterminationResult);
	}
	
	/**
	 * 尺寸-判断结果
	 */
	public java.math.BigDecimal getSizeDeterminationResult() {
		return get("sizeDeterminationResult");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeaveFactoryDate(java.util.Date leaveFactoryDate) {
		set("leaveFactoryDate", leaveFactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeaveFactoryDate() {
		return getDate("leaveFactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过待入库，60确认入库，待审核，70审核入库通过入库成功
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过待入库，60确认入库，待审核，70审核入库通过入库成功
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 抽检数量总
	 */
	public void setSampleQuantity(java.math.BigDecimal sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 抽检数量总
	 */
	public java.math.BigDecimal getSampleQuantity() {
		return get("sampleQuantity");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入人
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入人
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 最终检验结论（合格/不合格/复检等）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setCompInspQty(java.math.BigDecimal compInspQty) {
		set("compInspQty", compInspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getCompInspQty() {
		return get("compInspQty");
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public void setMechInspQty(java.math.BigDecimal mechInspQty) {
		set("mechInspQty", mechInspQty);
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public java.math.BigDecimal getMechInspQty() {
		return get("mechInspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasNo(java.lang.String basNo) {
		set("basNo", basNo);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasNo() {
		return getStr("basNo");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
}

