package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClLg<M extends BaseClLg<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 复检单号？来料检验批次号
	 */
	public void setMatRecheckNo(java.lang.String matRecheckNo) {
		set("matRecheckNo", matRecheckNo);
	}
	
	/**
	 * 复检单号？来料检验批次号
	 */
	public java.lang.String getMatRecheckNo() {
		return getStr("matRecheckNo");
	}
	
	/**
	 * 原材料制造商
	 */
	public void setMafactory(java.lang.String mafactory) {
		set("mafactory", mafactory);
	}
	
	/**
	 * 原材料制造商
	 */
	public java.lang.String getMafactory() {
		return getStr("mafactory");
	}
	
	/**
	 * 牌号
	 */
	public void setMatMaterial(java.lang.String matMaterial) {
		set("matMaterial", matMaterial);
	}
	
	/**
	 * 牌号
	 */
	public java.lang.String getMatMaterial() {
		return getStr("matMaterial");
	}
	
	/**
	 * 入库编号
	 */
	public void setInNo(java.lang.String inNo) {
		set("inNo", inNo);
	}
	
	/**
	 * 入库编号
	 */
	public java.lang.String getInNo() {
		return getStr("inNo");
	}
	
	/**
	 * 化学成分实测值-Si
	 */
	public void setChemSi(java.math.BigDecimal chemSi) {
		set("chemSi", chemSi);
	}
	
	/**
	 * 化学成分实测值-Si
	 */
	public java.math.BigDecimal getChemSi() {
		return get("chemSi");
	}
	
	/**
	 * 化学成分实测值-Fe
	 */
	public void setChemFe(java.math.BigDecimal chemFe) {
		set("chemFe", chemFe);
	}
	
	/**
	 * 化学成分实测值-Fe
	 */
	public java.math.BigDecimal getChemFe() {
		return get("chemFe");
	}
	
	/**
	 * 化学成分实测值-Cu
	 */
	public void setChemCu(java.math.BigDecimal chemCu) {
		set("chemCu", chemCu);
	}
	
	/**
	 * 化学成分实测值-Cu
	 */
	public java.math.BigDecimal getChemCu() {
		return get("chemCu");
	}
	
	/**
	 * 化学成分实测值-Mn
	 */
	public void setChemMn(java.math.BigDecimal chemMn) {
		set("chemMn", chemMn);
	}
	
	/**
	 * 化学成分实测值-Mn
	 */
	public java.math.BigDecimal getChemMn() {
		return get("chemMn");
	}
	
	/**
	 * 化学成分实测值-Mg
	 */
	public void setChemMg(java.math.BigDecimal chemMg) {
		set("chemMg", chemMg);
	}
	
	/**
	 * 化学成分实测值-Mg
	 */
	public java.math.BigDecimal getChemMg() {
		return get("chemMg");
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public void setChemSiRequired(java.lang.String chemSiRequired) {
		set("chemSiRequired", chemSiRequired);
	}
	
	/**
	 * 化学成分要求值-Si
	 */
	public java.lang.String getChemSiRequired() {
		return getStr("chemSiRequired");
	}
	
	/**
	 * 化学成分要求值-Fe
	 */
	public void setChemFeRequired(java.lang.String chemFeRequired) {
		set("chemFeRequired", chemFeRequired);
	}
	
	/**
	 * 化学成分要求值-Fe
	 */
	public java.lang.String getChemFeRequired() {
		return getStr("chemFeRequired");
	}
	
	/**
	 * 化学成分要求值-Cu
	 */
	public void setChemCuRequired(java.lang.String chemCuRequired) {
		set("chemCuRequired", chemCuRequired);
	}
	
	/**
	 * 化学成分要求值-Cu
	 */
	public java.lang.String getChemCuRequired() {
		return getStr("chemCuRequired");
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public void setChemMnRequired(java.lang.String chemMnRequired) {
		set("chemMnRequired", chemMnRequired);
	}
	
	/**
	 * 化学成分要求值-Mn
	 */
	public java.lang.String getChemMnRequired() {
		return getStr("chemMnRequired");
	}
	
	/**
	 * 化学成分要求值-Mg
	 */
	public void setChemMgRequired(java.lang.String chemMgRequired) {
		set("chemMgRequired", chemMgRequired);
	}
	
	/**
	 * 化学成分要求值-Mg
	 */
	public java.lang.String getChemMgRequired() {
		return getStr("chemMgRequired");
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public void setLeaveFactoryDate(java.util.Date leaveFactoryDate) {
		set("leaveFactoryDate", leaveFactoryDate);
	}
	
	/**
	 * 原材料出厂检测日期
	 */
	public java.util.Date getLeaveFactoryDate() {
		return getDate("leaveFactoryDate");
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public void setDetectionTime(java.util.Date detectionTime) {
		set("detectionTime", detectionTime);
	}
	
	/**
	 * 原材料入厂检测日期
	 */
	public java.util.Date getDetectionTime() {
		return getDate("detectionTime");
	}
	
	/**
	 * 质量证明书
	 */
	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	/**
	 * 质量证明书
	 */
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}
	
	/**
	 * 请检单录入人
	 */
	public void setRequestWriter(java.lang.String requestWriter) {
		set("requestWriter", requestWriter);
	}
	
	/**
	 * 请检单录入人
	 */
	public java.lang.String getRequestWriter() {
		return getStr("requestWriter");
	}
	
	/**
	 * 请检单录入时间
	 */
	public void setWriteTime(java.util.Date writeTime) {
		set("writeTime", writeTime);
	}
	
	/**
	 * 请检单录入时间
	 */
	public java.util.Date getWriteTime() {
		return getDate("writeTime");
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	/**
	 * 状态，10检验单录入，20检验单确认，待审核，30请检单审核通过，待录入检验数据，40录入数据确认，待审核，50审核通过检验完成
	 */
	public java.lang.String getStatus() {
		return getStr("status");
	}
	
	/**
	 * 请检单备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 请检单备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 单据号
	 */
	public void setBasNo(java.lang.String basNo) {
		set("basNo", basNo);
	}
	
	/**
	 * 单据号
	 */
	public java.lang.String getBasNo() {
		return getStr("basNo");
	}
	
	/**
	 * 炉批号
	 */
	public void setBatchNo(java.lang.String batchNo) {
		set("batchNo", batchNo);
	}
	
	/**
	 * 炉批号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batchNo");
	}
	
	/**
	 * 抽检数量总
	 */
	public void setSampleQuantity(java.math.BigDecimal sampleQuantity) {
		set("sampleQuantity", sampleQuantity);
	}
	
	/**
	 * 抽检数量总
	 */
	public java.math.BigDecimal getSampleQuantity() {
		return get("sampleQuantity");
	}
	
	/**
	 * 材质
	 */
	public void setMaterial(java.lang.String material) {
		set("material", material);
	}
	
	/**
	 * 材质
	 */
	public java.lang.String getMaterial() {
		return getStr("material");
	}
	
	/**
	 * 型号
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 型号
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 检验标准
	 */
	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	/**
	 * 检验标准
	 */
	public java.lang.String getStandard() {
		return getStr("standard");
	}
	
	/**
	 * 外观尺寸
	 */
	public void setAppearanceSize(java.lang.String appearanceSize) {
		set("appearanceSize", appearanceSize);
	}
	
	/**
	 * 外观尺寸
	 */
	public java.lang.String getAppearanceSize() {
		return getStr("appearanceSize");
	}
	
	/**
	 * 检验完成审核人
	 */
	public void setCheckAuditor(java.lang.String checkAuditor) {
		set("checkAuditor", checkAuditor);
	}
	
	/**
	 * 检验完成审核人
	 */
	public java.lang.String getCheckAuditor() {
		return getStr("checkAuditor");
	}
	
	/**
	 * 检验数据录入
	 */
	public void setCheckWriter(java.lang.String checkWriter) {
		set("checkWriter", checkWriter);
	}
	
	/**
	 * 检验数据录入
	 */
	public java.lang.String getCheckWriter() {
		return getStr("checkWriter");
	}
	
	/**
	 * 检验完成时间
	 */
	public void setCheckFinishTime(java.util.Date checkFinishTime) {
		set("checkFinishTime", checkFinishTime);
	}
	
	/**
	 * 检验完成时间
	 */
	public java.util.Date getCheckFinishTime() {
		return getDate("checkFinishTime");
	}
	
	/**
	 * 合同编号
	 */
	public void setContractNo(java.lang.String contractNo) {
		set("contractNo", contractNo);
	}
	
	/**
	 * 合同编号
	 */
	public java.lang.String getContractNo() {
		return getStr("contractNo");
	}
	
	/**
	 * 合同名称
	 */
	public void setContractName(java.lang.String contractName) {
		set("contractName", contractName);
	}
	
	/**
	 * 合同名称
	 */
	public java.lang.String getContractName() {
		return getStr("contractName");
	}
	
	/**
	 * 送货数量
	 */
	public void setDeliveryQuantity(java.math.BigDecimal deliveryQuantity) {
		set("deliveryQuantity", deliveryQuantity);
	}
	
	/**
	 * 送货数量
	 */
	public java.math.BigDecimal getDeliveryQuantity() {
		return get("deliveryQuantity");
	}
	
	/**
	 * 验收数量
	 */
	public void setAcceptQuantity(java.math.BigDecimal acceptQuantity) {
		set("acceptQuantity", acceptQuantity);
	}
	
	/**
	 * 验收数量
	 */
	public java.math.BigDecimal getAcceptQuantity() {
		return get("acceptQuantity");
	}
	
	/**
	 * 外观尺寸结论（合格/不合格）
	 */
	public void setFinalConclusion(java.lang.String finalConclusion) {
		set("finalConclusion", finalConclusion);
	}
	
	/**
	 * 外观尺寸结论（合格/不合格）
	 */
	public java.lang.String getFinalConclusion() {
		return getStr("finalConclusion");
	}
	
	/**
	 * 入库时间
	 */
	public void setStorageTime(java.util.Date storageTime) {
		set("storageTime", storageTime);
	}
	
	/**
	 * 入库时间
	 */
	public java.util.Date getStorageTime() {
		return getDate("storageTime");
	}
	
	/**
	 * 检验数据备注
	 */
	public void setCheckMemo(java.lang.String checkMemo) {
		set("checkMemo", checkMemo);
	}
	
	/**
	 * 检验数据备注
	 */
	public java.lang.String getCheckMemo() {
		return getStr("checkMemo");
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public void setCompInspQty(java.math.BigDecimal compInspQty) {
		set("compInspQty", compInspQty);
	}
	
	/**
	 * 成分检验抽检数量，默认为一件
	 */
	public java.math.BigDecimal getCompInspQty() {
		return get("compInspQty");
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public void setMechInspQty(java.math.BigDecimal mechInspQty) {
		set("mechInspQty", mechInspQty);
	}
	
	/**
	 * 力学性能检验抽检数量，默认为三件
	 */
	public java.math.BigDecimal getMechInspQty() {
		return get("mechInspQty");
	}
	
	/**
	 * 批次号
	 */
	public void setBatchNum(java.lang.String batchNum) {
		set("batchNum", batchNum);
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNum() {
		return getStr("batchNum");
	}
	
	/**
	 * 请检单审核人
	 */
	public void setRequestAuditor(java.lang.String requestAuditor) {
		set("requestAuditor", requestAuditor);
	}
	
	/**
	 * 请检单审核人
	 */
	public java.lang.String getRequestAuditor() {
		return getStr("requestAuditor");
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 单位，请检单用默认为kg
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 抗拉强度实测值第一组
	 */
	public void setMechTSA(java.math.BigDecimal mechTSA) {
		set("mechTSA", mechTSA);
	}
	
	/**
	 * 抗拉强度实测值第一组
	 */
	public java.math.BigDecimal getMechTSA() {
		return get("mechTSA");
	}
	
	/**
	 * 伸长率实测值第一组
	 */
	public void setMechELA(java.math.BigDecimal mechELA) {
		set("mechELA", mechELA);
	}
	
	/**
	 * 伸长率实测值第一组
	 */
	public java.math.BigDecimal getMechELA() {
		return get("mechELA");
	}
	
	/**
	 * 布氏硬度实测值第一组
	 */
	public void setMechHBA(java.math.BigDecimal mechHBA) {
		set("mechHBA", mechHBA);
	}
	
	/**
	 * 布氏硬度实测值第一组
	 */
	public java.math.BigDecimal getMechHBA() {
		return get("mechHBA");
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public void setMechTSRequired(java.lang.String mechTSRequired) {
		set("mechTSRequired", mechTSRequired);
	}
	
	/**
	 * 抗拉强度要求值
	 */
	public java.lang.String getMechTSRequired() {
		return getStr("mechTSRequired");
	}
	
	/**
	 * 伸长率要求值
	 */
	public void setMechELRequired(java.lang.String mechELRequired) {
		set("mechELRequired", mechELRequired);
	}
	
	/**
	 * 伸长率要求值
	 */
	public java.lang.String getMechELRequired() {
		return getStr("mechELRequired");
	}
	
	/**
	 * 布氏硬度要求值
	 */
	public void setMechHBRequired(java.lang.String mechHBRequired) {
		set("mechHBRequired", mechHBRequired);
	}
	
	/**
	 * 布氏硬度要求值
	 */
	public java.lang.String getMechHBRequired() {
		return getStr("mechHBRequired");
	}
	
	/**
	 * 抗拉强度实测值第二组
	 */
	public void setMechTSB(java.math.BigDecimal mechTSB) {
		set("mechTSB", mechTSB);
	}
	
	/**
	 * 抗拉强度实测值第二组
	 */
	public java.math.BigDecimal getMechTSB() {
		return get("mechTSB");
	}
	
	/**
	 * 抗拉强度实测值第三组
	 */
	public void setMechTSC(java.math.BigDecimal mechTSC) {
		set("mechTSC", mechTSC);
	}
	
	/**
	 * 抗拉强度实测值第三组
	 */
	public java.math.BigDecimal getMechTSC() {
		return get("mechTSC");
	}
	
	/**
	 * 伸长率实测值第二组
	 */
	public void setMechELB(java.math.BigDecimal mechELB) {
		set("mechELB", mechELB);
	}
	
	/**
	 * 伸长率实测值第二组
	 */
	public java.math.BigDecimal getMechELB() {
		return get("mechELB");
	}
	
	/**
	 * 伸长率实测值第三组
	 */
	public void setMechELC(java.math.BigDecimal mechELC) {
		set("mechELC", mechELC);
	}
	
	/**
	 * 伸长率实测值第三组
	 */
	public java.math.BigDecimal getMechELC() {
		return get("mechELC");
	}
	
	/**
	 * 布氏硬度实测值第二组
	 */
	public void setMechHBB(java.math.BigDecimal mechHBB) {
		set("mechHBB", mechHBB);
	}
	
	/**
	 * 布氏硬度实测值第二组
	 */
	public java.math.BigDecimal getMechHBB() {
		return get("mechHBB");
	}
	
	/**
	 * 布氏硬度实测值第三组
	 */
	public void setMechHBC(java.math.BigDecimal mechHBC) {
		set("mechHBC", mechHBC);
	}
	
	/**
	 * 布氏硬度实测值第三组
	 */
	public java.math.BigDecimal getMechHBC() {
		return get("mechHBC");
	}
	
}

