package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlInspItem<M extends BasePlInspItem<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 项目编码（唯一标识），如"TENSILE"
	 */
	public void setInspItemCode(java.lang.String inspItemCode) {
		set("inspItemCode", inspItemCode);
	}
	
	/**
	 * 项目编码（唯一标识），如"TENSILE"
	 */
	public java.lang.String getInspItemCode() {
		return getStr("inspItemCode");
	}
	
	/**
	 * 项目名称，如"抗拉强度"
	 */
	public void setInspItemName(java.lang.String inspItemName) {
		set("inspItemName", inspItemName);
	}
	
	/**
	 * 项目名称，如"抗拉强度"
	 */
	public java.lang.String getInspItemName() {
		return getStr("inspItemName");
	}
	
	/**
	 * 输入控件类型：number-数字，text-文本，bool-布尔，select-下拉选择，date-日期
	 */
	public void setDataType(java.lang.String dataType) {
		set("dataType", dataType);
	}
	
	/**
	 * 输入控件类型：number-数字，text-文本，bool-布尔，select-下拉选择，date-日期
	 */
	public java.lang.String getDataType() {
		return getStr("dataType");
	}
	
	/**
	 * 计量单位，如"MPa"、"%"（无单位时可为空）
	 */
	public void setUnit(java.lang.String unit) {
		set("unit", unit);
	}
	
	/**
	 * 计量单位，如"MPa"、"%"（无单位时可为空）
	 */
	public java.lang.String getUnit() {
		return getStr("unit");
	}
	
	/**
	 * 所属检验类别如"力学性能"、"化学成分"
	 */
	public void setCategory(java.lang.String category) {
		set("category", category);
	}
	
	/**
	 * 所属检验类别如"力学性能"、"化学成分"
	 */
	public java.lang.String getCategory() {
		return getStr("category");
	}
	
	/**
	 * 状态（预留字段）
	 */
	public void setStatus(java.lang.Byte status) {
		set("status", status);
	}
	
	/**
	 * 状态（预留字段）
	 */
	public java.lang.Byte getStatus() {
		return getByte("status");
	}
	
	/**
	 * 备注说明（如检验标准、特殊要求等）
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注说明（如检验标准、特殊要求等）
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
}

