package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlMaterialRequestMain<M extends BasePlMaterialRequestMain<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 领料单号（格式：LLYYYYMMDDHHMMSS）
	 */
	public void setRequestNo(java.lang.String requestNo) {
		set("requestNo", requestNo);
	}
	
	/**
	 * 领料单号（格式：LLYYYYMMDDHHMMSS）
	 */
	public java.lang.String getRequestNo() {
		return getStr("requestNo");
	}
	
	/**
	 * 申请人ID
	 */
	public void setApplicantId(java.lang.Long applicantId) {
		set("applicantId", applicantId);
	}
	
	/**
	 * 申请人ID
	 */
	public java.lang.Long getApplicantId() {
		return getLong("applicantId");
	}
	
	/**
	 * 申请人姓名
	 */
	public void setApplicantName(java.lang.String applicantName) {
		set("applicantName", applicantName);
	}
	
	/**
	 * 申请人姓名
	 */
	public java.lang.String getApplicantName() {
		return getStr("applicantName");
	}
	
	/**
	 * 申请部门名称
	 */
	public void setDepartmentName(java.lang.String departmentName) {
		set("departmentName", departmentName);
	}
	
	/**
	 * 申请部门名称
	 */
	public java.lang.String getDepartmentName() {
		return getStr("departmentName");
	}
	
	/**
	 * 合同ID
	 */
	public void setProjectId(java.lang.Long projectId) {
		set("projectId", projectId);
	}
	
	/**
	 * 合同ID
	 */
	public java.lang.Long getProjectId() {
		return getLong("projectId");
	}
	
	/**
	 * 项目名称
	 */
	public void setProjectName(java.lang.String projectName) {
		set("projectName", projectName);
	}
	
	/**
	 * 项目名称
	 */
	public java.lang.String getProjectName() {
		return getStr("projectName");
	}
	
	/**
	 * 领料用途说明
	 */
	public void setRequestReason(java.lang.String requestReason) {
		set("requestReason", requestReason);
	}
	
	/**
	 * 领料用途说明
	 */
	public java.lang.String getRequestReason() {
		return getStr("requestReason");
	}
	
	/**
	 * 库管员ID
	 */
	public void setKeeperId(java.lang.Long keeperId) {
		set("keeperId", keeperId);
	}
	
	/**
	 * 库管员ID
	 */
	public java.lang.Long getKeeperId() {
		return getLong("keeperId");
	}
	
	/**
	 * 库管员姓名
	 */
	public void setKeeperName(java.lang.String keeperName) {
		set("keeperName", keeperName);
	}
	
	/**
	 * 库管员姓名
	 */
	public java.lang.String getKeeperName() {
		return getStr("keeperName");
	}
	
	/**
	 * 审核时间
	 */
	public void setApproveTime(java.util.Date approveTime) {
		set("approveTime", approveTime);
	}
	
	/**
	 * 审核时间
	 */
	public java.util.Date getApproveTime() {
		return getDate("approveTime");
	}
	
	/**
	 * 状态（0-草稿，1-待审核，11-审核成功待领取，12-审核拒绝，20-已全部领取，21-已部分领取）
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态（0-草稿，1-待审核，11-审核成功待领取，12-审核拒绝，20-已全部领取，21-已部分领取）
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 备注
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getRemark() {
		return getStr("remark");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}
	
	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}
	
	/**
	 * 更新时间
	 */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}
	
	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("createBy", createBy);
	}
	
	/**
	 * 创建人
	 */
	public java.lang.String getCreateBy() {
		return getStr("createBy");
	}
	
}

