package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePlbaogongdan<M extends BasePlbaogongdan<M>> extends Model<M> implements IBean {

	/**
	 * 主键ID
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	/**
	 * 主键ID
	 */
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 采购方总部编码
	 */
	public void setPurchaserHqCode(java.lang.String purchaserHqCode) {
		set("purchaserHqCode", purchaserHqCode);
	}
	
	/**
	 * 采购方总部编码
	 */
	public java.lang.String getPurchaserHqCode() {
		return getStr("purchaserHqCode");
	}
	
	/**
	 * 供应商编码
	 */
	public void setSupplierCode(java.lang.String supplierCode) {
		set("supplierCode", supplierCode);
	}
	
	/**
	 * 供应商编码
	 */
	public java.lang.String getSupplierCode() {
		return getStr("supplierCode");
	}
	
	/**
	 * 生产订单序号
	 */
	public void setIpoNo(java.lang.String ipoNo) {
		set("ipoNo", ipoNo);
	}
	
	/**
	 * 生产订单序号
	 */
	public java.lang.String getIpoNo() {
		return getStr("ipoNo");
	}
	
	/**
	 * 产品内部ID号
	 */
	public void setInsideNo(java.lang.String insideNo) {
		set("insideNo", insideNo);
	}
	
	/**
	 * 产品内部ID号
	 */
	public java.lang.String getInsideNo() {
		return getStr("insideNo");
	}
	
	/**
	 * 设备序号
	 */
	public void setDeviceNo(java.lang.String deviceNo) {
		set("deviceNo", deviceNo);
	}
	
	/**
	 * 设备序号
	 */
	public java.lang.String getDeviceNo() {
		return getStr("deviceNo");
	}
	
	/**
	 * 生产批次号
	 */
	public void setProductBatchNo(java.lang.String productBatchNo) {
		set("productBatchNo", productBatchNo);
	}
	
	/**
	 * 生产批次号
	 */
	public java.lang.String getProductBatchNo() {
		return getStr("productBatchNo");
	}
	
	/**
	 * 工序名称
	 */
	public void setProcessName(java.lang.String processName) {
		set("processName", processName);
	}
	
	/**
	 * 工序名称
	 */
	public java.lang.String getProcessName() {
		return getStr("processName");
	}
	
	/**
	 * 品类编码
	 */
	public void setCategoryCode(java.lang.String categoryCode) {
		set("categoryCode", categoryCode);
	}
	
	/**
	 * 品类编码
	 */
	public java.lang.String getCategoryCode() {
		return getStr("categoryCode");
	}
	
	/**
	 * 种类编码
	 */
	public void setSubclassCode(java.lang.String subclassCode) {
		set("subclassCode", subclassCode);
	}
	
	/**
	 * 种类编码
	 */
	public java.lang.String getSubclassCode() {
		return getStr("subclassCode");
	}
	
	/**
	 * 工序编码
	 */
	public void setProcessCode(java.lang.String processCode) {
		set("processCode", processCode);
	}
	
	/**
	 * 工序编码
	 */
	public java.lang.String getProcessCode() {
		return getStr("processCode");
	}
	
	/**
	 * 生产工艺路线编码
	 */
	public void setProcessNo(java.lang.String processNo) {
		set("processNo", processNo);
	}
	
	/**
	 * 生产工艺路线编码
	 */
	public java.lang.String getProcessNo() {
		return getStr("processNo");
	}
	
	/**
	 * 生产车间ID
	 */
	public void setWorkshopId(java.lang.String workshopId) {
		set("workshopId", workshopId);
	}
	
	/**
	 * 生产车间ID
	 */
	public java.lang.String getWorkshopId() {
		return getStr("workshopId");
	}
	
	/**
	 * 生产车间编码
	 */
	public void setWorkshopCode(java.lang.String workshopCode) {
		set("workshopCode", workshopCode);
	}
	
	/**
	 * 生产车间编码
	 */
	public java.lang.String getWorkshopCode() {
		return getStr("workshopCode");
	}
	
	/**
	 * 生产车间名称
	 */
	public void setWorkshopName(java.lang.String workshopName) {
		set("workshopName", workshopName);
	}
	
	/**
	 * 生产车间名称
	 */
	public java.lang.String getWorkshopName() {
		return getStr("workshopName");
	}
	
	/**
	 * 生产工单序号
	 */
	public void setWoNo(java.lang.String woNo) {
		set("woNo", woNo);
	}
	
	/**
	 * 生产工单序号
	 */
	public java.lang.String getWoNo() {
		return getStr("woNo");
	}
	
	/**
	 * 实物ID，如用户侧实物ID
	 */
	public void setProductId(java.lang.String productId) {
		set("productId", productId);
	}
	
	/**
	 * 实物ID，如用户侧实物ID
	 */
	public java.lang.String getProductId() {
		return getStr("productId");
	}
	
	/**
	 * 数据来源
	 */
	public void setDataSource(java.lang.String dataSource) {
		set("dataSource", dataSource);
	}
	
	/**
	 * 数据来源
	 */
	public java.lang.String getDataSource() {
		return getStr("dataSource");
	}
	
	/**
	 * 来源数据创建时间
	 */
	public void setDataSourceCreateTime(java.util.Date dataSourceCreateTime) {
		set("dataSourceCreateTime", dataSourceCreateTime);
	}
	
	/**
	 * 来源数据创建时间
	 */
	public java.util.Date getDataSourceCreateTime() {
		return getDate("dataSourceCreateTime");
	}
	
	/**
	 * 计划开始时间
	 */
	public void setPlanStartTime(java.util.Date planStartTime) {
		set("planStartTime", planStartTime);
	}
	
	/**
	 * 计划开始时间
	 */
	public java.util.Date getPlanStartTime() {
		return getDate("planStartTime");
	}
	
	/**
	 * 计划结束时间
	 */
	public void setPlanEndTime(java.util.Date planEndTime) {
		set("planEndTime", planEndTime);
	}
	
	/**
	 * 计划结束时间
	 */
	public java.util.Date getPlanEndTime() {
		return getDate("planEndTime");
	}
	
	/**
	 * 实际开始时间
	 */
	public void setActualStartDate(java.util.Date actualStartDate) {
		set("actualStartDate", actualStartDate);
	}
	
	/**
	 * 实际开始时间
	 */
	public java.util.Date getActualStartDate() {
		return getDate("actualStartDate");
	}
	
	/**
	 * 实际结束时间
	 */
	public void setActualFinishDate(java.util.Date actualFinishDate) {
		set("actualFinishDate", actualFinishDate);
	}
	
	/**
	 * 实际结束时间
	 */
	public java.util.Date getActualFinishDate() {
		return getDate("actualFinishDate");
	}
	
	/**
	 * 订单状态
	 */
	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("orderStatus", orderStatus);
	}
	
	/**
	 * 订单状态
	 */
	public java.lang.Integer getOrderStatus() {
		return getInt("orderStatus");
	}
	
	/**
	 * 客户所属省份
	 */
	public void setBuyerProvince(java.lang.String buyerProvince) {
		set("buyerProvince", buyerProvince);
	}
	
	/**
	 * 客户所属省份
	 */
	public java.lang.String getBuyerProvince() {
		return getStr("buyerProvince");
	}
	
	/**
	 * 数据拥有方
	 */
	public void setOwnerId(java.lang.String ownerId) {
		set("ownerId", ownerId);
	}
	
	/**
	 * 数据拥有方
	 */
	public java.lang.String getOwnerId() {
		return getStr("ownerId");
	}
	
	/**
	 * 数据可见方
	 */
	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}
	
	/**
	 * 数据可见方
	 */
	public java.lang.String getOpenId() {
		return getStr("openId");
	}
	
	/**
	 * 波形信息
	 */
	public void setWavyStatus(java.lang.Byte wavyStatus) {
		set("wavyStatus", wavyStatus);
	}
	
	/**
	 * 波形信息
	 */
	public java.lang.Byte getWavyStatus() {
		return getByte("wavyStatus");
	}
	
	/**
	 * 标志位
	 */
	public void setFlag(java.lang.String flag) {
		set("flag", flag);
	}
	
	/**
	 * 标志位
	 */
	public java.lang.String getFlag() {
		return getStr("flag");
	}
	
	/**
	 * 类型
	 */
	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	/**
	 * 类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}
	
	/**
	 * 状态
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	/**
	 * 状态
	 */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}
	
	/**
	 * 是否删除（0:未删除,1:已删除）
	 */
	public void setIsdelete(java.lang.Integer isdelete) {
		set("isdelete", isdelete);
	}
	
	/**
	 * 是否删除（0:未删除,1:已删除）
	 */
	public java.lang.Integer getIsdelete() {
		return getInt("isdelete");
	}
	
	/**
	 * 备注
	 */
	public void setMemo(java.lang.String memo) {
		set("memo", memo);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getMemo() {
		return getStr("memo");
	}
	
}

