package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysusermenu<M extends BaseSysusermenu<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 菜单id关联sysmenu表
	 */
	public void setMenuid(java.lang.Integer menuid) {
		set("menuid", menuid);
	}
	
	/**
	 * 菜单id关联sysmenu表
	 */
	public java.lang.Integer getMenuid() {
		return getInt("menuid");
	}
	
	/**
	 * 用户id关联sysuser表
	 */
	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}
	
	/**
	 * 用户id关联sysuser表
	 */
	public java.lang.Integer getUserid() {
		return getInt("userid");
	}
	
}

