package com.xlerp.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUploadLog<M extends BaseSysUploadLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}
	
	/**
	 * 接口名，对应后端interface
	 */
	public void setInterfaceName(java.lang.String interfaceName) {
		set("interfaceName", interfaceName);
	}
	
	/**
	 * 接口名，对应后端interface
	 */
	public java.lang.String getInterfaceName() {
		return getStr("interfaceName");
	}
	
	/**
	 * 接口描述，描述上传的什么数据
	 */
	public void setInterfaceDescribe(java.lang.String interfaceDescribe) {
		set("interfaceDescribe", interfaceDescribe);
	}
	
	/**
	 * 接口描述，描述上传的什么数据
	 */
	public java.lang.String getInterfaceDescribe() {
		return getStr("interfaceDescribe");
	}
	
	/**
	 * 上传的api地址
	 */
	public void setUploadUrl(java.lang.String uploadUrl) {
		set("uploadUrl", uploadUrl);
	}
	
	/**
	 * 上传的api地址
	 */
	public java.lang.String getUploadUrl() {
		return getStr("uploadUrl");
	}
	
	/**
	 * 上传内容，包括headers和body
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	/**
	 * 上传内容，包括headers和body
	 */
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 上传返回结果
	 */
	public void setResult(java.lang.String result) {
		set("result", result);
	}
	
	/**
	 * 上传返回结果
	 */
	public java.lang.String getResult() {
		return getStr("result");
	}
	
	/**
	 * 上传状态，0成功，1失败
	 */
	public void setUploadStatus(java.lang.Byte uploadStatus) {
		set("uploadStatus", uploadStatus);
	}
	
	/**
	 * 上传状态，0成功，1失败
	 */
	public java.lang.Byte getUploadStatus() {
		return getByte("uploadStatus");
	}
	
	/**
	 * 上传开始时间
	 */
	public void setUploadStartTime(java.util.Date uploadStartTime) {
		set("uploadStartTime", uploadStartTime);
	}
	
	/**
	 * 上传开始时间
	 */
	public java.util.Date getUploadStartTime() {
		return getDate("uploadStartTime");
	}
	
	/**
	 * 上传结束时间
	 */
	public void setUploadFinishTime(java.util.Date uploadFinishTime) {
		set("uploadFinishTime", uploadFinishTime);
	}
	
	/**
	 * 上传结束时间
	 */
	public java.util.Date getUploadFinishTime() {
		return getDate("uploadFinishTime");
	}
	
}

